/**
 * FASHION industry themes — v0.5
 * 40 themes covering Lifestyle / TVC / Editorial / Product modes.
 */

import type { ThemePreset } from "../themes";

export const FASHION_THEMES: ThemePreset[] = [
  // ========================================================================
  // LIFESTYLE (10)
  // ========================================================================
  {
    id: "fs_streetstyle_y2k",
    category: "fashion_lifestyle",
    name: "Streetstyle Y2K Sài Gòn",
    description: "Cô gái mặc outfit Y2K cargo + crop top + chunky sneakers dạo phố Sài Gòn, vibe 2000s",
    descriptionEn: "Young woman in Y2K outfit (cargo pants, crop top, chunky sneakers) walking Saigon streets, early 2000s revival aesthetic",
    cameraStyle: "DOCUMENTARY", time: "afternoon", mood: ["edgy", "trendy", "youthful"],
    emoji: "🦋", mode: "lifestyle", industry: "fashion",
  },
  {
    id: "fs_mirror_selfie_ootd",
    category: "fashion_lifestyle",
    name: "Mirror selfie OOTD",
    description: "Cô gái mirror selfie tại closet, OOTD đầy đủ, điện thoại cầm tay, vibe IG fashion",
    descriptionEn: "Young woman taking mirror selfie at home closet, full OOTD outfit visible, phone in hand, Instagram fashion blogger vibe",
    cameraStyle: "DOCUMENTARY", time: "indoor", mood: ["trendy", "self-expression", "casual"],
    emoji: "🪞", mode: "lifestyle", industry: "fashion",
  },
  {
    id: "fs_cafe_outdoor_tote",
    category: "fashion_lifestyle",
    name: "Cafe outdoor tote bag",
    description: "Cô gái ngồi cafe outdoor cầm tote bag canvas trắng, áo polo + denim shorts",
    descriptionEn: "Young woman at outdoor cafe with white canvas tote bag, polo shirt and denim shorts, casual chic lifestyle",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["chic", "casual", "minimal"],
    emoji: "👜", mode: "lifestyle", industry: "fashion",
  },
  {
    id: "fs_walking_autumn_hanoi",
    category: "fashion_lifestyle",
    name: "Walking phố Hà Nội mùa thu",
    description: "Cô gái mặc trench coat camel walking phố Hà Nội mùa thu, lá vàng rơi, scarf len",
    descriptionEn: "Young woman in camel trench coat walking Hanoi old quarter in autumn, falling yellow leaves, wool scarf, vintage romantic mood",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["romantic", "vintage", "autumn"],
    emoji: "🍁", mode: "lifestyle", industry: "fashion",
  },
  {
    id: "fs_beach_bikini",
    category: "fashion_lifestyle",
    name: "Beach bikini summer",
    description: "Cô gái áo bikini hồng tại beach Phú Quốc, oversized straw hat, vibe summer",
    descriptionEn: "Young woman in pink bikini set at Phu Quoc beach, oversized straw hat, sunglasses, vibrant summer fashion vibe",
    cameraStyle: "BOKEH", time: "midday", mood: ["summer", "tropical", "fresh"],
    emoji: "🏖", mode: "lifestyle", industry: "fashion",
  },
  {
    id: "fs_pyjamas_hygge",
    category: "fashion_lifestyle",
    name: "Pyjamas hygge cuối tuần",
    description: "Cô gái mặc silk pyjamas màu pastel ngồi giường cuối tuần, cầm cốc cocoa, không khí cozy",
    descriptionEn: "Young woman in pastel silk pajamas on bed weekend morning, holding cocoa mug, cozy hygge weekend lifestyle aesthetic",
    cameraStyle: "BOKEH", time: "midday", mood: ["cozy", "soft", "intimate"],
    emoji: "🥞", mode: "lifestyle", industry: "fashion",
  },
  {
    id: "fs_chinatown_modern_aodai",
    category: "fashion_lifestyle",
    name: "Phố Tàu Q5 áo dài cách tân",
    description: "Cô gái áo dài cách tân pastel dạo phố Tàu Quận 5 Sài Gòn, đèn lồng đỏ, vibe Đông Dương",
    descriptionEn: "Young woman in modern pastel ao dai walking Saigon Chinatown District 5, red lanterns, Indochine modern fusion fashion",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["traditional", "modern", "elegant"],
    emoji: "🏮", mode: "lifestyle", industry: "fashion",
  },
  {
    id: "fs_office_lookbook",
    category: "fashion_lifestyle",
    name: "Office look blazer",
    description: "Cô gái mặc oversized blazer + tank top + trousers, briefcase, vibe office lookbook",
    descriptionEn: "Young woman in oversized blazer, tank top, wide-leg trousers with briefcase, modern office lookbook fashion",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["professional", "chic", "modern"],
    emoji: "👔", mode: "lifestyle", industry: "fashion",
  },
  {
    id: "fs_picnic_summer",
    category: "fashion_lifestyle",
    name: "Picnic dress summer",
    description: "Cô gái mặc đầm hoa summer picnic công viên, basket cầm tay, hat rơm",
    descriptionEn: "Young woman in floral summer dress at park picnic, holding wicker basket, straw hat, soft summer fashion lifestyle",
    cameraStyle: "BOKEH", time: "midday", mood: ["fresh", "summer", "feminine"],
    emoji: "🌷", mode: "lifestyle", industry: "fashion",
  },
  {
    id: "fs_layered_winter",
    category: "fashion_lifestyle",
    name: "Layered winter Đà Lạt",
    description: "Cô gái mặc layered outfit winter (sweater + scarf + coat) tại Đà Lạt, sương mù",
    descriptionEn: "Young woman in layered winter outfit (sweater, scarf, long coat) at misty Da Lat, foggy mountain background, winter fashion",
    cameraStyle: "BOKEH", time: "overcast", mood: ["cozy", "winter", "moody"],
    emoji: "🧣", mode: "lifestyle", industry: "fashion",
  },

  // ========================================================================
  // TVC COMMERCIAL (10)
  // ========================================================================
  {
    id: "fs_tvc_holding_handbag",
    category: "fashion_tvc",
    name: "Cầm handbag premium",
    description: "Cô gái cầm handbag luxury hi-end ngang ngực, side profile, lighting drama studio",
    descriptionEn: "Young woman holding premium luxury handbag at chest level, elegant side profile, dramatic studio lighting, luxury fashion brand TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "elegant", "premium"],
    emoji: "👜", mode: "tvc_commercial", industry: "fashion",
  },
  {
    id: "fs_tvc_sneaker_close",
    category: "fashion_tvc",
    name: "Sneaker detail close-up",
    description: "Close-up cô gái mặc sneakers Adidas đứng nghiêng chân, leg sang trọng, lighting clean",
    descriptionEn: "Close-up of young woman wearing Adidas Samba sneakers in side stance, elegant leg pose, clean studio lighting, sneaker fashion TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["edgy", "premium", "stylish"],
    emoji: "👟", mode: "tvc_commercial", industry: "fashion",
  },
  {
    id: "fs_tvc_jewelry_neck",
    category: "fashion_tvc",
    name: "Jewelry close-up neck",
    description: "Close-up cô gái đeo necklace gold trên cổ, side profile, lighting black background",
    descriptionEn: "Close-up of young woman wearing gold necklace on neck, elegant side profile, black background dramatic lighting, jewelry TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "elegant", "premium"],
    emoji: "💍", mode: "tvc_commercial", industry: "fashion",
  },
  {
    id: "fs_tvc_perfume_bottle",
    category: "fashion_tvc",
    name: "Perfume bottle giơ cao",
    description: "Cô gái cầm chai nước hoa pha lê giơ ngang ngực, satin background, vibe luxury",
    descriptionEn: "Young woman holding crystal perfume bottle at chest level, satin background, luxury perfume fashion TVC, glamorous",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "glamorous", "elegant"],
    emoji: "🌸", mode: "tvc_commercial", industry: "fashion",
  },
  {
    id: "fs_tvc_watch_wrist",
    category: "fashion_tvc",
    name: "Watch wrist showcase",
    description: "Hand model cận cảnh cổ tay đeo đồng hồ luxury, ngón tay relaxed, lighting drama",
    descriptionEn: "Hand model close-up of wrist wearing luxury timepiece, relaxed fingers, dramatic lighting, watch fashion TVC product showcase",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "premium", "elegant"],
    emoji: "⌚", mode: "tvc_commercial", industry: "fashion",
  },
  {
    id: "fs_tvc_sunglasses_pose",
    category: "fashion_tvc",
    name: "Sunglasses fashion pose",
    description: "Cô gái đeo sunglasses, một tay chạm vào kính chỉnh, side profile, vibe high fashion",
    descriptionEn: "Young woman wearing designer sunglasses, one hand adjusting frames, side profile pose, high fashion editorial TVC",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["edgy", "high-fashion", "confident"],
    emoji: "🕶", mode: "tvc_commercial", industry: "fashion",
  },
  {
    id: "fs_tvc_dress_twirl",
    category: "fashion_tvc",
    name: "Dress twirl motion",
    description: "Cô gái xoay người, váy bay flowing, motion blur skirt, lighting cinematic",
    descriptionEn: "Young woman twirling, dress flowing in motion, dramatic skirt motion blur, cinematic lighting, fashion TVC dress showcase",
    cameraStyle: "BOKEH", time: "indoor", mood: ["dynamic", "elegant", "feminine"],
    emoji: "💃", mode: "tvc_commercial", industry: "fashion",
  },
  {
    id: "fs_tvc_male_suit",
    category: "fashion_tvc",
    name: "Nam vest đen cầm tie",
    description: "Anh chàng vest đen cầm cravat đỏ, mỉm cười tự tin, background xám sang trọng",
    descriptionEn: "Young man in black tuxedo holding red tie, confident smile, sophisticated grey background, premium menswear fashion TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["sophisticated", "luxury", "masculine"],
    emoji: "🤵", mode: "tvc_commercial", industry: "fashion",
  },
  {
    id: "fs_tvc_couple_runway",
    category: "fashion_tvc",
    name: "Cặp đôi runway pose",
    description: "Cặp đôi cùng pose runway, cô gái áo dài đỏ, anh vest đen, background black hi-end",
    descriptionEn: "Couple in runway pose, woman in red ao dai, man in black tuxedo, hi-end black background, premium fashion couple TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "elegant", "premium"],
    emoji: "💑", mode: "tvc_commercial", industry: "fashion",
  },
  {
    id: "fs_tvc_kids_fashion",
    category: "fashion_tvc",
    name: "Trẻ em cute fashion",
    description: "Bé gái mặc đầm dễ thương, mỉm cười tay cầm túi xách mini, vibe kids fashion",
    descriptionEn: "Cute young girl in adorable dress, smiling holding mini handbag, sweet kids fashion TVC, soft pastel background",
    cameraStyle: "BOKEH", time: "indoor", mood: ["cute", "playful", "sweet"],
    emoji: "👧", mode: "tvc_commercial", industry: "fashion",
  },

  // ========================================================================
  // EDITORIAL FASHION (10)
  // ========================================================================
  {
    id: "fs_ed_high_fashion",
    category: "fashion_editorial",
    name: "High-fashion magazine pose",
    description: "Cô gái pose dramatic editorial, váy haute couture, lighting cinematic dark, vibe Vogue",
    descriptionEn: "Young woman in dramatic editorial pose, haute couture dress, cinematic dark lighting, Vogue magazine spread aesthetic",
    cameraStyle: "BOKEH", time: "indoor", mood: ["dramatic", "luxury", "editorial"],
    emoji: "📰", mode: "editorial_fashion", industry: "fashion",
  },
  {
    id: "fs_ed_walking_motion",
    category: "fashion_editorial",
    name: "Walking confidently street",
    description: "Cô gái mặc trench coat walking confidently down street, motion blur background, hi-fashion",
    descriptionEn: "Young woman in trench coat walking confidently down street, motion blur background, high-fashion editorial street style",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["confident", "edgy", "editorial"],
    emoji: "🚶‍♀️", mode: "editorial_fashion", industry: "fashion",
  },
  {
    id: "fs_ed_colored_wall",
    category: "fashion_editorial",
    name: "Side profile colored wall",
    description: "Cô gái side profile against colored wall đỏ rực, váy đen, vibe minimalist editorial",
    descriptionEn: "Young woman in side profile against vibrant red wall, black dress, minimalist editorial fashion composition",
    cameraStyle: "BOKEH", time: "indoor", mood: ["minimalist", "bold", "editorial"],
    emoji: "🟥", mode: "editorial_fashion", industry: "fashion",
  },
  {
    id: "fs_ed_studio_spotlight",
    category: "fashion_editorial",
    name: "Studio spotlight full body",
    description: "Cô gái pose full body trong studio black với spotlight chiếu xuống dramatic",
    descriptionEn: "Young woman full body pose in black studio with dramatic spotlight from above, high-fashion editorial silhouette",
    cameraStyle: "BOKEH", time: "indoor", mood: ["dramatic", "editorial", "luxury"],
    emoji: "💡", mode: "editorial_fashion", industry: "fashion",
  },
  {
    id: "fs_ed_handbag_close",
    category: "fashion_editorial",
    name: "Handbag detail editorial",
    description: "Cô gái cầm handbag close-up, body partially visible, focus chi tiết bag",
    descriptionEn: "Young woman holding handbag in close-up shot, body partially visible, focus on bag details, fashion editorial product story",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "detailed", "editorial"],
    emoji: "👜", mode: "editorial_fashion", industry: "fashion",
  },
  {
    id: "fs_ed_skirt_motion",
    category: "fashion_editorial",
    name: "Twirling skirt motion",
    description: "Cô gái xoay làm váy bay tầng tầng motion blur, dramatic lighting, background đen",
    descriptionEn: "Young woman twirling making layered skirt swirl in motion blur, dramatic lighting, black background, dynamic fashion editorial",
    cameraStyle: "BOKEH", time: "indoor", mood: ["dynamic", "editorial", "dramatic"],
    emoji: "🌪", mode: "editorial_fashion", industry: "fashion",
  },
  {
    id: "fs_ed_sneaker_foot",
    category: "fashion_editorial",
    name: "Sneaker detail foot pose",
    description: "Cô gái nâng chân pose để show sneaker close-up, leg long elegant, lighting drama",
    descriptionEn: "Young woman lifting leg in pose to showcase sneaker close-up, long elegant leg lines, dramatic lighting, editorial fashion footwear",
    cameraStyle: "BOKEH", time: "indoor", mood: ["edgy", "editorial", "dynamic"],
    emoji: "👟", mode: "editorial_fashion", industry: "fashion",
  },
  {
    id: "fs_ed_fashion_week",
    category: "fashion_editorial",
    name: "Fashion week street style",
    description: "Cô gái fashion week outfit dạo phố Paris/Milan style, paparazzi vibe, motion",
    descriptionEn: "Young woman in fashion week street style outfit walking Paris/Milan style street, paparazzi candid vibe, motion captured",
    cameraStyle: "DOCUMENTARY", time: "afternoon", mood: ["editorial", "trendy", "street"],
    emoji: "📸", mode: "editorial_fashion", industry: "fashion",
  },
  {
    id: "fs_ed_model_lay",
    category: "fashion_editorial",
    name: "Model laying editorial",
    description: "Cô gái nằm pose editorial trên silk màu đỏ, váy bay flowing, vibe magazine spread",
    descriptionEn: "Young woman laying in editorial pose on red silk fabric, dress flowing artistically, fashion magazine spread aesthetic",
    cameraStyle: "BOKEH", time: "indoor", mood: ["editorial", "sensual", "luxury"],
    emoji: "🛏", mode: "editorial_fashion", industry: "fashion",
  },
  {
    id: "fs_ed_male_editorial",
    category: "fashion_editorial",
    name: "Nam editorial dramatic",
    description: "Anh chàng vest oversized pose editorial dramatic, jaw sharp, lighting black-blue",
    descriptionEn: "Young man in oversized blazer in dramatic editorial pose, sharp jawline, black-blue dramatic lighting, masculine fashion editorial",
    cameraStyle: "BOKEH", time: "indoor", mood: ["editorial", "masculine", "dramatic"],
    emoji: "🤵", mode: "editorial_fashion", industry: "fashion",
  },

  // ========================================================================
  // PRODUCT PHOTOGRAPHY (10)
  // ========================================================================
  {
    id: "fs_pp_outfit_flatlay",
    category: "fashion_product",
    name: "Outfit flat lay",
    description: "Outfit flat lay top-down: áo + quần + giày + bag + accessories trên background trắng",
    descriptionEn: "Top-down outfit flat lay: shirt, pants, shoes, bag, accessories arranged on white background, fashion outfit product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["organized", "minimal", "complete"],
    emoji: "📐", mode: "product_photo", industry: "fashion",
  },
  {
    id: "fs_pp_handbag_silk",
    category: "fashion_product",
    name: "Handbag trên silk",
    description: "Handbag luxury trên silk fabric đỏ, lighting drama side, hi-end product photography",
    descriptionEn: "Luxury handbag on red silk fabric, dramatic side lighting, hi-end product photography, magazine quality",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "elegant", "premium"],
    emoji: "👜", mode: "product_photo", industry: "fashion",
  },
  {
    id: "fs_pp_sneakers_macro",
    category: "fashion_product",
    name: "Sneakers macro shot",
    description: "Macro shot Adidas Samba sneakers trên carbon fiber, lighting cool blue dramatic",
    descriptionEn: "Macro shot of Adidas Samba sneakers on carbon fiber surface, cool blue dramatic lighting, premium sneaker product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["edgy", "premium", "tech-fashion"],
    emoji: "👟", mode: "product_photo", industry: "fashion",
  },
  {
    id: "fs_pp_jewelry_silk",
    category: "fashion_product",
    name: "Jewelry trên silk fabric",
    description: "Bộ jewelry vàng trên silk đen, gradient lighting, marco shot, hi-end",
    descriptionEn: "Gold jewelry collection on black silk fabric, gradient lighting, macro detailed shot, hi-end luxury jewelry product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "elegant", "premium"],
    emoji: "💎", mode: "product_photo", industry: "fashion",
  },
  {
    id: "fs_pp_sunglasses_marble",
    category: "fashion_product",
    name: "Sunglasses trên marble",
    description: "Sunglasses cao cấp trên marble trắng, lighting clean, top-down composition",
    descriptionEn: "Premium designer sunglasses on white marble surface, clean lighting, top-down composition, premium accessories photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["clean", "premium", "minimal"],
    emoji: "🕶", mode: "product_photo", industry: "fashion",
  },
  {
    id: "fs_pp_perfume_silk",
    category: "fashion_product",
    name: "Perfume trên silk pink",
    description: "Chai nước hoa trên silk hồng pastel, hoa hồng tươi trang trí, lighting mềm",
    descriptionEn: "Perfume bottle on pastel pink silk, fresh roses decorating, soft diffused lighting, romantic feminine fashion product",
    cameraStyle: "BOKEH", time: "indoor", mood: ["romantic", "feminine", "luxury"],
    emoji: "🌹", mode: "product_photo", industry: "fashion",
  },
  {
    id: "fs_pp_watch_box_open",
    category: "fashion_product",
    name: "Watch trong hộp mở",
    description: "Đồng hồ luxury trong hộp gỗ mở, gold accents, lighting drama",
    descriptionEn: "Luxury watch in open wooden presentation box, gold accents, dramatic spotlight lighting, hi-end watch product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "premium", "exclusive"],
    emoji: "⌚", mode: "product_photo", industry: "fashion",
  },
  {
    id: "fs_pp_clothes_hanger",
    category: "fashion_product",
    name: "Quần áo trên hanger",
    description: "5 outfit khác nhau treo trên hanger đẹp, background trắng, lighting clean",
    descriptionEn: "Five different outfits hanging on premium wooden hangers, white background, clean professional lighting, fashion catalog photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["organized", "professional", "minimal"],
    emoji: "👔", mode: "product_photo", industry: "fashion",
  },
  {
    id: "fs_pp_belt_buckle",
    category: "fashion_product",
    name: "Belt buckle close-up",
    description: "Close-up belt buckle vàng trên leather đen, lighting drama, hi-end accessories",
    descriptionEn: "Close-up of gold belt buckle on black leather strap, dramatic lighting, hi-end accessories product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "edgy", "premium"],
    emoji: "👔", mode: "product_photo", industry: "fashion",
  },
  {
    id: "fs_pp_scarf_silk",
    category: "fashion_product",
    name: "Silk scarf flowing",
    description: "Scarf silk flowing trong air freeze frame, lighting drama, color vibrant",
    descriptionEn: "Silk scarf flowing in mid-air freeze-frame, dramatic lighting, vibrant colors visible, premium accessories fashion product",
    cameraStyle: "BOKEH", time: "indoor", mood: ["dynamic", "luxury", "elegant"],
    emoji: "🧣", mode: "product_photo", industry: "fashion",
  },
];
