/**
 * F&B (Đồ ăn, đồ uống) industry themes — v0.5
 * 50 themes covering Lifestyle / TVC / Product Photography modes.
 */

import type { ThemePreset } from "../themes";

export const FNB_THEMES: ThemePreset[] = [
  // ========================================================================
  // LIFESTYLE (15)
  // ========================================================================
  {
    id: "fb_morning_coffee_home",
    category: "fnb_lifestyle",
    name: "Pha cà phê sáng tại nhà",
    description: "Cô gái đang pha cà phê tại quầy bếp nhà, máy espresso nhả khói, ly espresso vàng",
    descriptionEn: "Young woman brewing coffee at home kitchen counter, espresso machine steaming, golden espresso shot in cup, morning sunlight through window",
    cameraStyle: "BOKEH", time: "midday", mood: ["cozy", "morning", "aromatic"],
    emoji: "☕", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_brunch_cafe_latte",
    category: "fnb_lifestyle",
    name: "Brunch cafe latte art",
    description: "Cô gái ngồi cafe outdoor, trên bàn có ly cafe latte art tim, bánh croissant, ánh sáng ấm",
    descriptionEn: "Young woman at outdoor cafe table, latte with heart art and croissant on table, warm afternoon lighting, food blogger aesthetic",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["chill", "aesthetic", "warm"],
    emoji: "🥐", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_picnic_juice",
    category: "fnb_lifestyle",
    name: "Picnic công viên với juice",
    description: "Cô gái ngồi picnic công viên cỏ xanh, cầm chai juice cam tươi, sandwich và hoa quả",
    descriptionEn: "Young woman at park picnic on green grass, holding fresh orange juice bottle, sandwich and fruits on blanket, golden afternoon light",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["fresh", "outdoor", "summer"],
    emoji: "🧺", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_rooftop_cocktail",
    category: "fnb_lifestyle",
    name: "Cocktail rooftop bar",
    description: "Cô gái ngồi rooftop bar Sài Gòn cầm ly cocktail, hoàng hôn vàng cam phía sau, váy đen",
    descriptionEn: "Young woman at Saigon rooftop bar holding cocktail glass, golden orange sunset behind, black dress, sophisticated evening vibe",
    cameraStyle: "BOKEH", time: "golden_hour", mood: ["luxe", "sophisticated", "urban"],
    emoji: "🍸", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_birthday_cake",
    category: "fnb_lifestyle",
    name: "Cắt bánh sinh nhật",
    description: "Cô gái cắt bánh sinh nhật trắng có nến, bạn bè vây quanh hát, khói nến bay",
    descriptionEn: "Young woman cutting white birthday cake with candles, friends around singing, candle smoke rising, joyful celebration",
    cameraStyle: "DOCUMENTARY", time: "indoor", mood: ["celebration", "warm", "joyful"],
    emoji: "🎂", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_pho_street",
    category: "fnb_lifestyle",
    name: "Phở vỉa hè cười tươi",
    description: "Cô gái ngồi ăn phở vỉa hè Hà Nội, đang lùa sợi phở, mỉm cười, tô phở bốc khói",
    descriptionEn: "Young woman eating pho at Hanoi sidewalk stall, chopsticks lifting noodles, bright smile, steaming pho bowl, authentic Vietnamese street food",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["authentic", "happy", "local"],
    emoji: "🍜", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_family_dinner",
    category: "fnb_lifestyle",
    name: "Family dinner đông người",
    description: "Gia đình 6-8 người quây quần bàn ăn dinner, nhiều món Việt Nam trên bàn, không khí ấm cúng",
    descriptionEn: "Family of 6-8 people gathered around dinner table, multiple Vietnamese dishes spread, warm intimate family atmosphere, wooden dining room",
    cameraStyle: "DOCUMENTARY", time: "indoor", mood: ["family", "warm", "communal"],
    emoji: "👨‍👩‍👧‍👦", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_beer_cheers",
    category: "fnb_lifestyle",
    name: "Cụng ly bia 1-2-3 dzô",
    description: "Nhóm bạn cụng ly bia vàng vỉa hè Sài Gòn, tay giơ cao hô '1, 2, 3 dzô', đèn vàng đêm",
    descriptionEn: "Group of friends clinking golden beer glasses high at Saigon sidewalk, raising glasses in '1, 2, 3 cheers' Vietnamese toast, warm yellow night lights",
    cameraStyle: "DOCUMENTARY", time: "night", mood: ["lively", "social", "joyful"],
    emoji: "🍻", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_boba_walking",
    category: "fnb_lifestyle",
    name: "Boba tea trên đường phố",
    description: "Cô gái cầm ly boba tea sữa nâu vừa đi vừa hút ống hút, đường phố Sài Gòn",
    descriptionEn: "Young woman walking and sipping brown sugar boba tea through straw, Saigon city street, casual everyday vibe",
    cameraStyle: "DOCUMENTARY", time: "afternoon", mood: ["trendy", "casual", "urban"],
    emoji: "🧋", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_wine_romantic",
    category: "fnb_lifestyle",
    name: "Pour wine romantic dinner",
    description: "Cô gái ngồi bàn ăn romantic, đối diện bạn trai đang pour rượu vang đỏ vào ly",
    descriptionEn: "Young woman at romantic dinner table, partner pouring red wine into her glass, candlelight, intimate restaurant atmosphere",
    cameraStyle: "BOKEH", time: "night", mood: ["romantic", "elegant", "intimate"],
    emoji: "🍷", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_morning_smoothie",
    category: "fnb_lifestyle",
    name: "Smoothie buổi sáng",
    description: "Cô gái sau khi tập thể dục cầm chai smoothie hồng tươi, áo workout, mồ hôi nhẹ",
    descriptionEn: "Young woman post-workout holding pink smoothie bottle, workout outfit, light sweat glow, healthy lifestyle",
    cameraStyle: "BOKEH", time: "midday", mood: ["healthy", "fresh", "energetic"],
    emoji: "🥤", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_kbbq_friends",
    category: "fnb_lifestyle",
    name: "KBBQ với bạn bè",
    description: "Nhóm bạn 4-5 người ăn KBBQ Hàn Quốc, thịt nướng trên bếp than, kim chi và soju",
    descriptionEn: "Group of 4-5 friends eating Korean BBQ, marinated meat on charcoal grill, kimchi and soju on table, lively Korean restaurant atmosphere",
    cameraStyle: "DOCUMENTARY", time: "indoor", mood: ["lively", "trendy", "social"],
    emoji: "🥩", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_breakfast_in_bed",
    category: "fnb_lifestyle",
    name: "Breakfast in bed",
    description: "Cô gái ngồi giường mặc pyjama, khay breakfast trên đùi: pancake, juice cam, hoa hồng",
    descriptionEn: "Young woman in bed wearing pajamas, breakfast tray on lap with pancakes, orange juice, single rose, lazy Sunday morning vibe",
    cameraStyle: "BOKEH", time: "midday", mood: ["cozy", "lazy", "luxurious"],
    emoji: "🥞", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_street_food_market",
    category: "fnb_lifestyle",
    name: "Chợ street food",
    description: "Cô gái dạo street food market Sài Gòn buổi tối, cầm xiên thịt nướng, đèn neon đỏ vàng",
    descriptionEn: "Young woman at Saigon night street food market, holding grilled meat skewer, vibrant neon red and yellow lights, bustling atmosphere",
    cameraStyle: "DOCUMENTARY", time: "night", mood: ["vibrant", "local", "exciting"],
    emoji: "🍢", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_tea_zen",
    category: "fnb_lifestyle",
    name: "Trà thiền zen",
    description: "Cô gái mặc áo dài lam ngồi pha trà sen tại trà đạo, không gian zen, lá rơi",
    descriptionEn: "Young woman in light blue ao dai brewing lotus tea at Vietnamese tea ceremony, zen atmosphere, falling leaves, traditional teaware",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["zen", "traditional", "serene"],
    emoji: "🍵", mode: "lifestyle", industry: "fnb",
  },

  // ========================================================================
  // TVC COMMERCIAL (15)
  // ========================================================================
  {
    id: "fb_tvc_juice_cinematic",
    category: "fnb_tvc",
    name: "Giơ chai juice cinematic",
    description: "Cô gái giơ chai nước ép cam tươi dưới ánh nắng vàng, drops mọng nước, hoa quả bay xung quanh",
    descriptionEn: "Young woman holding fresh orange juice bottle under golden sunlight, water droplets glistening, fruits floating around in cinematic freeze-frame",
    cameraStyle: "BOKEH", time: "golden_hour", mood: ["fresh", "vibrant", "cinematic"],
    emoji: "🥤", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_beer_clink",
    category: "fnb_tvc",
    name: "Cụng lon bia trước camera",
    description: "Cô gái và anh chàng cụng lon bia vàng trước camera, splash bia bay, vibe summer party",
    descriptionEn: "Young woman and man clinking gold beer cans toward camera, beer splash freeze frame, summer party TVC vibe, dynamic motion",
    cameraStyle: "BOKEH", time: "indoor", mood: ["energetic", "celebratory", "summer"],
    emoji: "🍺", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_burger_bite",
    category: "fnb_tvc",
    name: "Cắn burger slow-motion",
    description: "Close-up cô gái cắn burger to, sốt chảy slow-motion freeze, mắt nhắm thưởng thức",
    descriptionEn: "Close-up of young woman taking big bite of burger, sauce dripping in slow-motion freeze, eyes closed in enjoyment, mouthwatering shot",
    cameraStyle: "BOKEH", time: "indoor", mood: ["indulgent", "dynamic", "appetizing"],
    emoji: "🍔", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_espresso_sip",
    category: "fnb_tvc",
    name: "Espresso savoring",
    description: "Cô gái cầm tách espresso nhỏ nhâm nhi, mắt nhắm thưởng thức, side profile, vibe luxury",
    descriptionEn: "Young woman holding small espresso cup savoring, eyes closed in enjoyment, elegant side profile, warm luxury cafe lighting",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "indulgent", "warm"],
    emoji: "☕", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_cereal_pour",
    category: "fnb_tvc",
    name: "Đổ ngũ cốc slow pour",
    description: "Cô gái đổ ngũ cốc vào bát sữa slow-motion, splash sữa, breakfast morning TVC",
    descriptionEn: "Young woman pouring cereal into milk bowl slow-motion, milk splash droplets frozen, bright morning TVC kitchen",
    cameraStyle: "BOKEH", time: "midday", mood: ["fresh", "wholesome", "morning"],
    emoji: "🥣", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_cocktail_pour",
    category: "fnb_tvc",
    name: "Pour shot cocktail",
    description: "Bartender pour shot rượu vào ly cocktail trang trí với hoa quả, slow motion, neon background",
    descriptionEn: "Bartender pouring liquor shot into cocktail glass with fruit garnish, slow motion freeze, neon-lit cocktail bar background",
    cameraStyle: "BOKEH", time: "night", mood: ["sophisticated", "edgy", "vibrant"],
    emoji: "🍹", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_pizza_pull",
    category: "fnb_tvc",
    name: "Pizza cheese pull",
    description: "Cô gái lấy miếng pizza, cheese kéo dài stringy hot, mắt sáng lên enjoy",
    descriptionEn: "Young woman lifting pizza slice with stretchy hot cheese pull, eyes brightening with delight, appetizing cheese strings",
    cameraStyle: "BOKEH", time: "indoor", mood: ["indulgent", "appetizing", "warm"],
    emoji: "🍕", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_milk_pour",
    category: "fnb_tvc",
    name: "Đổ sữa vào ly trong",
    description: "Slow-motion đổ sữa trắng vào ly thủy tinh trong, splash droplets, background trắng pure",
    descriptionEn: "Slow-motion pouring white milk into clear glass, splash droplets frozen mid-air, pure white background, premium dairy TVC aesthetic",
    cameraStyle: "BOKEH", time: "indoor", mood: ["fresh", "pure", "premium"],
    emoji: "🥛", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_chocolate_melt",
    category: "fnb_tvc",
    name: "Chocolate melting",
    description: "Close-up chocolate đang tan chảy lỏng, cô gái dùng spoon nâng chocolate, eyes nhắm enjoy",
    descriptionEn: "Close-up of melting chocolate flowing, young woman lifting spoon of chocolate, eyes closed savoring, indulgent dessert TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["indulgent", "rich", "sensual"],
    emoji: "🍫", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_water_fresh",
    category: "fnb_tvc",
    name: "Nước khoáng splash",
    description: "Cô gái uống chai nước khoáng, water splash bay khỏi miệng chai, fresh outdoor",
    descriptionEn: "Young woman drinking mineral water bottle, water splash spraying from bottle mouth, fresh outdoor athletic TVC",
    cameraStyle: "BOKEH", time: "midday", mood: ["fresh", "energetic", "pure"],
    emoji: "💧", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_ice_cream_lick",
    category: "fnb_tvc",
    name: "Ice cream cone lick",
    description: "Cô gái cầm ice cream cone hồng, lưỡi chạm vào kem, vibe summer playful",
    descriptionEn: "Young woman holding pink ice cream cone, tongue touching ice cream playfully, summer playful TVC vibe, vibrant colors",
    cameraStyle: "BOKEH", time: "midday", mood: ["playful", "summer", "youthful"],
    emoji: "🍦", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_sushi_chopstick",
    category: "fnb_tvc",
    name: "Sushi chopstick lift",
    description: "Close-up đôi đũa nâng miếng sushi, soy sauce chảy nhẹ, plate đen sang trọng",
    descriptionEn: "Close-up of chopsticks lifting sushi piece, soy sauce dripping subtly, elegant black plate, premium Japanese restaurant TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "elegant", "japanese"],
    emoji: "🍣", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_drink_glow",
    category: "fnb_tvc",
    name: "Drink glow back-lit",
    description: "Ly đồ uống được back-light xuyên qua, màu vàng cam glow, cô gái cầm ngang ngực",
    descriptionEn: "Drink glass back-lit with golden orange glow shining through liquid, young woman holding at chest, dramatic premium beverage TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "dramatic", "warm"],
    emoji: "✨", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_couple_dinner",
    category: "fnb_tvc",
    name: "Cặp đôi cùng dùng bữa",
    description: "Cặp đôi cùng cười và cụng ly wine, plate sang trọng trên bàn, ánh nến warm",
    descriptionEn: "Couple laughing and clinking wine glasses, elegant dinner plates on table, warm candlelight, premium dining TVC",
    cameraStyle: "BOKEH", time: "night", mood: ["romantic", "luxury", "warm"],
    emoji: "🍷", mode: "tvc_commercial", industry: "fnb",
  },
  {
    id: "fb_tvc_family_meal",
    category: "fnb_tvc",
    name: "Gia đình bữa cơm thương hiệu",
    description: "Gia đình 4 người mỉm cười xung quanh bàn ăn với sản phẩm đặt giữa, ấm cúng",
    descriptionEn: "Family of 4 smiling around dinner table with branded product placed centrally, warm family TVC atmosphere, wholesome",
    cameraStyle: "BOKEH", time: "indoor", mood: ["family", "wholesome", "warm"],
    emoji: "👨‍👩‍👧", mode: "tvc_commercial", industry: "fnb",
  },

  // ========================================================================
  // PRODUCT PHOTOGRAPHY (15) — no subject
  // ========================================================================
  {
    id: "fb_pp_beer_can_ice",
    category: "fnb_product",
    name: "Lon bia trên đá lạnh",
    description: "Lon bia vàng trên ice cubes, water condensation, lighting cool blue, premium beer photography",
    descriptionEn: "Gold beer can on ice cubes, water condensation droplets, cool blue dramatic lighting, premium beer product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["fresh", "premium", "cool"],
    emoji: "🍺", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_sushi_wood",
    category: "fnb_product",
    name: "Sushi platter trên ván gỗ",
    description: "Plate sushi 6 cuốn xếp đẹp trên ván gỗ đen, soy sauce, wasabi, chopsticks, top-down",
    descriptionEn: "Sushi platter of 6 pieces beautifully arranged on dark wood board, soy sauce, wasabi, chopsticks, top-down minimal composition",
    cameraStyle: "BOKEH", time: "indoor", mood: ["minimal", "premium", "japanese"],
    emoji: "🍣", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_cocktail_garnish",
    category: "fnb_product",
    name: "Cocktail với hoa quả trang trí",
    description: "Ly cocktail với hoa quả trang trí, mint, ice cube, background gradient màu",
    descriptionEn: "Cocktail glass with elaborate fruit garnish, fresh mint, ice cubes, colorful gradient background, premium bar product shot",
    cameraStyle: "BOKEH", time: "indoor", mood: ["sophisticated", "vibrant", "premium"],
    emoji: "🍹", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_mooncake_box",
    category: "fnb_product",
    name: "Hộp bánh trung thu",
    description: "Hộp bánh trung thu sang trọng đặt cạnh ấm trà, hoa cúc, lighting vàng warm",
    descriptionEn: "Luxury mooncake gift box beside teapot, chrysanthemum flowers, warm golden lighting, premium festival product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["festive", "luxury", "traditional"],
    emoji: "🥮", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_pho_steam",
    category: "fnb_product",
    name: "Phở bốc khói cinematic",
    description: "Tô phở Việt Nam bốc khói, basil tươi, lighting drama, top-down 45° shot",
    descriptionEn: "Vietnamese pho bowl steaming hot, fresh basil leaves, dramatic lighting, 45-degree top-down composition, food magazine quality",
    cameraStyle: "BOKEH", time: "indoor", mood: ["authentic", "appetizing", "warm"],
    emoji: "🍜", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_burger_drip",
    category: "fnb_product",
    name: "Burger drip slow-motion",
    description: "Burger lifted với cheese melt và sauce drip, freeze frame, background đen",
    descriptionEn: "Premium burger lifted mid-air with melted cheese and sauce dripping, freeze-frame moment, black studio background, hero food shot",
    cameraStyle: "BOKEH", time: "indoor", mood: ["indulgent", "appetizing", "dramatic"],
    emoji: "🍔", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_acai_bowl",
    category: "fnb_product",
    name: "Acai bowl với fruits",
    description: "Acai bowl tím trang trí với fruits, granola, hoa edible, top-down minimal",
    descriptionEn: "Purple acai bowl decorated with fresh fruits, granola, edible flowers, top-down minimal composition, healthy lifestyle product",
    cameraStyle: "BOKEH", time: "midday", mood: ["healthy", "vibrant", "fresh"],
    emoji: "🍓", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_tiramisu_cross",
    category: "fnb_product",
    name: "Tiramisu cross-section",
    description: "Lát tiramisu cắt cross-section thấy layers, cocoa powder rắc, plate trắng",
    descriptionEn: "Tiramisu slice cut showing cross-section layers, dusted with cocoa powder, white plate, restaurant dessert photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["indulgent", "elegant", "premium"],
    emoji: "🍰", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_coffee_bean",
    category: "fnb_product",
    name: "Coffee bean với chocolate",
    description: "Coffee beans rang đậm xếp với chocolate squares, ly espresso, lighting warm",
    descriptionEn: "Roasted dark coffee beans arranged with chocolate squares, espresso cup, warm tungsten lighting, artisanal coffee product",
    cameraStyle: "BOKEH", time: "indoor", mood: ["artisanal", "warm", "rich"],
    emoji: "☕", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_cocktail_tower",
    category: "fnb_product",
    name: "Cocktail tower neon",
    description: "3 ly cocktail xếp tower, neon background tím xanh, drama lighting",
    descriptionEn: "Three cocktail glasses stacked tower style, purple-blue neon background, dramatic lighting, club/bar premium beverage photography",
    cameraStyle: "BOKEH", time: "night", mood: ["edgy", "vibrant", "modern"],
    emoji: "🍸", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_bread_artisan",
    category: "fnb_product",
    name: "Bánh mì artisan",
    description: "Ổ bánh mì artisan vàng nâu cắt half, bột mì rắc, marble background",
    descriptionEn: "Artisanal golden brown bread loaf cut in half, flour dusted, marble background, bakery rustic premium product",
    cameraStyle: "BOKEH", time: "indoor", mood: ["rustic", "artisanal", "warm"],
    emoji: "🥖", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_juice_pour",
    category: "fnb_product",
    name: "Pour orange juice",
    description: "Đổ nước cam tươi vào ly thủy tinh, fruits xung quanh, freeze frame splash",
    descriptionEn: "Pouring fresh orange juice into glass, surrounded by fresh fruits, freeze-frame splash droplets, vibrant juice product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["fresh", "vibrant", "healthy"],
    emoji: "🍊", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_chocolate_box",
    category: "fnb_product",
    name: "Hộp chocolate luxury",
    description: "Hộp chocolate cao cấp mở ra thấy 12 viên xếp gọn, gold ribbon, marble đen",
    descriptionEn: "Luxury chocolate box opened showing 12 truffles arranged, gold ribbon, black marble background, premium gift product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "indulgent", "elegant"],
    emoji: "🍫", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_smoothie_bottles",
    category: "fnb_product",
    name: "Bộ smoothies 5 vị",
    description: "5 chai smoothies màu khác nhau xếp gradient, fruits trang trí, top-down clean",
    descriptionEn: "Five smoothie bottles of different colors arranged in gradient, decorative fruits, top-down clean composition, healthy lifestyle product line",
    cameraStyle: "BOKEH", time: "indoor", mood: ["healthy", "colorful", "fresh"],
    emoji: "🥤", mode: "product_photo", industry: "fnb",
  },
  {
    id: "fb_pp_pizza_topdown",
    category: "fnb_product",
    name: "Pizza top-down hero",
    description: "Pizza nguyên cái top-down trên ván gỗ, cheese melt, basil tươi, lighting drama",
    descriptionEn: "Whole pizza top-down on wooden board, melted cheese, fresh basil leaves, dramatic side lighting, hero food photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["appetizing", "rustic", "indulgent"],
    emoji: "🍕", mode: "product_photo", industry: "fnb",
  },

  // ========================================================================
  // ADDITIONAL LIFESTYLE (5)
  // ========================================================================
  {
    id: "fb_phin_drip",
    category: "fnb_lifestyle",
    name: "Phin cà phê Việt nhỏ giọt",
    description: "Cô gái ngồi cafe Việt với phin cà phê đang nhỏ giọt vào ly có sữa đặc, không khí truyền thống",
    descriptionEn: "Young woman at Vietnamese cafe with phin coffee filter dripping into glass with condensed milk, traditional Vietnamese coffee atmosphere",
    cameraStyle: "DOCUMENTARY", time: "afternoon", mood: ["traditional", "authentic", "slow"],
    emoji: "☕", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_che_via_he",
    category: "fnb_lifestyle",
    name: "Chè vỉa hè ba màu",
    description: "Cô gái ngồi quán chè vỉa hè Sài Gòn ăn chè ba màu, ly thủy tinh, đèn vàng đêm",
    descriptionEn: "Young woman at Saigon sidewalk dessert stall eating tri-color che dessert, glass cup, warm yellow night lights",
    cameraStyle: "DOCUMENTARY", time: "night", mood: ["local", "sweet", "casual"],
    emoji: "🍧", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_banh_mi",
    category: "fnb_lifestyle",
    name: "Bánh mì vỉa hè",
    description: "Cô gái cầm ổ bánh mì pate vỉa hè cắn miếng đầu tiên, đường phố sáng",
    descriptionEn: "Young woman holding Vietnamese banh mi sandwich taking first bite at street stall, morning street scene",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["authentic", "happy", "local"],
    emoji: "🥖", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_hotpot_winter",
    category: "fnb_lifestyle",
    name: "Lẩu nóng ngày mưa",
    description: "Nhóm bạn ăn lẩu Thái nóng nồi đỏ bốc khói tại quán nhỏ ngày mưa, ấm áp",
    descriptionEn: "Group of friends eating spicy Thai hotpot with steaming red broth at small restaurant on rainy day, cozy warm atmosphere",
    cameraStyle: "DOCUMENTARY", time: "indoor", mood: ["cozy", "warm", "social"],
    emoji: "🍲", mode: "lifestyle", industry: "fnb",
  },
  {
    id: "fb_matcha_dessert",
    category: "fnb_lifestyle",
    name: "Matcha dessert cafe",
    description: "Cô gái ngồi cafe matcha-themed Nhật Bản, dessert matcha xanh và latte, vibe minimalist",
    descriptionEn: "Young woman at Japanese matcha-themed cafe, green matcha dessert and latte on table, minimalist Japanese aesthetic",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["minimalist", "japanese", "trendy"],
    emoji: "🍵", mode: "lifestyle", industry: "fnb",
  },
];
