/**
 * SKINCARE / MỸ PHẨM industry themes — v0.5
 *
 * 50 themes covering Lifestyle / TVC / Product Photography modes.
 * Designed for skincare, makeup, beauty content creators.
 */

import type { ThemePreset } from "../themes";

export const SKINCARE_THEMES: ThemePreset[] = [
  // ========================================================================
  // LIFESTYLE MODE (15 themes)
  // ========================================================================
  {
    id: "sk_morning_routine",
    category: "skincare_lifestyle",
    name: "Routine sáng soi gương",
    description: "Cô gái đang đứng trước gương vanity buổi sáng, đang vỗ nhẹ toner lên má, ánh sáng tự nhiên qua cửa sổ, robe trắng",
    descriptionEn: "Young woman at vanity mirror in morning, gently patting toner on cheeks with cotton pad, soft natural window light, in white robe, dewy fresh skin texture visible",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["fresh", "intimate", "morning"],
    emoji: "🪞",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_vanity_ringlight",
    category: "skincare_lifestyle",
    name: "Bàn vanity với ring light",
    description: "Cô gái ngồi trước bàn trang điểm có ring light, đang apply serum lên cổ, sản phẩm mỹ phẩm xếp gọn gàng",
    descriptionEn: "Young woman at vanity table with ring light, applying serum to neck, organized cosmetics arranged on table, soft glow lighting",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["aesthetic", "trendy", "soft"],
    emoji: "💡",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_sheet_mask",
    category: "skincare_lifestyle",
    name: "Mask sheet thư giãn",
    description: "Cô gái đắp mask sheet trắng trên mặt, nằm thư giãn trên gối, mắt nhắm nhẹ, không khí spa tại nhà",
    descriptionEn: "Young woman lying on pillow with white sheet mask on face, eyes gently closed, relaxed home spa atmosphere",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["relaxed", "self-care", "soft"],
    emoji: "🧖‍♀️",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_korean_pat",
    category: "skincare_lifestyle",
    name: "Pat-pat Korean style",
    description: "Cô gái pat-pat sản phẩm dưỡng lên má theo Korean skincare style, tay nhẹ nhàng, glass skin nổi bật",
    descriptionEn: "Young woman pat-patting skincare product onto cheeks Korean skincare style, gentle hand movements, prominent glass skin effect, dewy radiant",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["dewy", "korean", "fresh"],
    emoji: "✨",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_gua_sha",
    category: "skincare_lifestyle",
    name: "Massage gua sha",
    description: "Cô gái đang massage mặt với đá gua sha hồng, di chuyển dọc xương gò má, làn da căng mịn",
    descriptionEn: "Young woman massaging face with rose quartz gua sha stone, gliding along cheekbone, healthy plump skin, focused expression",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["wellness", "ritual", "elegant"],
    emoji: "🪨",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_sunscreen_beach",
    category: "skincare_lifestyle",
    name: "Bôi sunscreen trước khi đi biển",
    description: "Cô gái đang bôi kem chống nắng lên cánh tay tại ban công nhìn ra biển, áo bikini xanh, hoàng hôn",
    descriptionEn: "Young woman applying sunscreen to her arm on beachfront balcony, blue bikini, golden hour glow, sea visible behind",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["summer", "tropical", "fresh"],
    emoji: "🏖",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_lip_balm",
    category: "skincare_lifestyle",
    name: "Bôi lip balm cận cảnh",
    description: "Cô gái cận cảnh đang bôi lip balm trong suốt lên môi, môi căng mọng glossy, hơi thở nhẹ",
    descriptionEn: "Close-up of young woman applying clear lip balm to lips, plump glossy lips, soft breath visible, intimate beauty shot",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["intimate", "glossy", "feminine"],
    emoji: "👄",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_cleanse_face",
    category: "skincare_lifestyle",
    name: "Rửa mặt buổi tối",
    description: "Cô gái đang rửa mặt với foam cleanser trắng, bọt phủ mặt, mỉm cười nhẹ, phòng tắm modern",
    descriptionEn: "Young woman cleansing face with white foam cleanser, foam covering face, gentle smile, modern minimalist bathroom",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["fresh", "clean", "intimate"],
    emoji: "🫧",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_eye_cream",
    category: "skincare_lifestyle",
    name: "Bôi kem mắt detail",
    description: "Cô gái cận cảnh đang dùng ngón áp út tap kem mắt vào vùng dưới mắt, môi mím nhẹ",
    descriptionEn: "Close-up of young woman tapping eye cream under eye with ring finger, lips slightly pursed, focused care",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["detail", "ritual", "soft"],
    emoji: "👁",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_makeup_natural",
    category: "skincare_lifestyle",
    name: "Cafe natural makeup",
    description: "Cô gái ngồi cafe với natural makeup sạch sẽ, da glass skin Korean style, ánh sáng cửa sổ, ly cà phê",
    descriptionEn: "Young woman at cafe with clean natural makeup, Korean glass skin, soft window light, coffee cup beside",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["aesthetic", "natural", "fresh"],
    emoji: "☕",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_tone_dewy_window",
    category: "skincare_lifestyle",
    name: "Glass skin bên cửa sổ",
    description: "Cô gái nghiêng đầu bên cửa sổ ánh sáng vàng, glass skin căng bóng, không makeup nặng",
    descriptionEn: "Young woman tilting head by warm window light, glowing dewy glass skin, no heavy makeup, intimate portrait",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["dewy", "glowing", "intimate"],
    emoji: "🌟",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_friends_routine",
    category: "skincare_lifestyle",
    name: "Skincare cùng bạn thân",
    description: "Hai cô gái cùng nhau đắp mask sheet, nằm trên giường cười đùa, headband cute, không khí slumber party",
    descriptionEn: "Two young women applying sheet masks together on bed, laughing, cute headbands, slumber party atmosphere",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["fun", "friendship", "playful"],
    emoji: "👯‍♀️",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_after_shower",
    category: "skincare_lifestyle",
    name: "Body lotion sau tắm",
    description: "Cô gái mặc khăn tắm trắng đang bôi body lotion lên cánh tay, tóc ướt, da mịn",
    descriptionEn: "Young woman in white towel applying body lotion to arm, wet hair, smooth healthy skin, post-shower atmosphere",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["fresh", "soft", "intimate"],
    emoji: "🛁",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_hand_cream",
    category: "skincare_lifestyle",
    name: "Bôi kem tay",
    description: "Cô gái ngồi bàn làm việc đang bôi hand cream, móng tay làm gel nude, laptop phía sau",
    descriptionEn: "Young woman at desk applying hand cream, nude gel manicure visible, laptop in background, soft office light",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["working", "self-care", "soft"],
    emoji: "🤲",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_makeup_remove",
    category: "skincare_lifestyle",
    name: "Tẩy trang cuối ngày",
    description: "Cô gái đang dùng bông tẩy trang lau makeup, một nửa mặt sạch một nửa còn makeup, before-after style",
    descriptionEn: "Young woman wiping makeup off face with cotton pad, half clean / half makeup before-after style, focused expression",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["honest", "ritual", "calm"],
    emoji: "💆‍♀️",
    mode: "lifestyle",
    industry: "skincare",
  },

  // ========================================================================
  // TVC COMMERCIAL MODE (15 themes)
  // ========================================================================
  {
    id: "sk_tvc_serum_hold_high",
    category: "skincare_tvc",
    name: "Giơ serum trước mặt TVC",
    description: "Cô gái giơ chai serum lên ngang ngực, mỉm cười tự tin, background gradient pastel mềm mại, lighting studio mềm",
    descriptionEn: "Young woman holding serum bottle prominently at chest level, confident smile, soft pastel gradient background, professional studio softbox lighting, glowing dewy skin",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["confident", "premium", "polished"],
    emoji: "🧴",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_two_hands_cream",
    category: "skincare_tvc",
    name: "Hai tay nâng hộp kem",
    description: "Cô gái cầm hộp kem dưỡng bằng hai tay nâng nhẹ trước ngực, ánh sáng vàng ấm, vibe luxury",
    descriptionEn: "Young woman cradling cream jar with both hands at chest level, warm golden lighting, luxury beauty vibe, gentle smile",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["luxury", "elegant", "warm"],
    emoji: "🤲",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_droplet_palm",
    category: "skincare_tvc",
    name: "Giọt serum trên lòng bàn tay",
    description: "Cô gái nhìn xuống một giọt serum vàng nhỏ giọt vào lòng bàn tay, focus vào droplet, slow motion freeze",
    descriptionEn: "Young woman looking down at golden serum droplet falling into her palm, dramatic focus on the droplet, slow-motion freeze frame aesthetic",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["premium", "scientific", "dramatic"],
    emoji: "💧",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_apply_cheek",
    category: "skincare_tvc",
    name: "Bôi cream lên má side profile",
    description: "Side profile cô gái đang bôi cream lên má bằng đầu ngón tay, mắt nhắm nhẹ, glowing skin",
    descriptionEn: "Side profile of young woman applying cream to cheek with fingertip, eyes gently closed, radiant glowing skin, premium TVC composition",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["serene", "luxury", "intimate"],
    emoji: "💆",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_half_mask",
    category: "skincare_tvc",
    name: "Half face mask sheet",
    description: "Cô gái với nửa mặt đắp mask sheet, nửa kia đã glowing, before-after concept rõ ràng, lighting studio",
    descriptionEn: "Young woman with half face wearing sheet mask, other half showing glowing radiant result, clear before-after concept, studio lighting",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["transformation", "scientific", "polished"],
    emoji: "🪞",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_skinfluencer",
    category: "skincare_tvc",
    name: "Skinfluencer giơ product",
    description: "Cô gái cầm sản phẩm ngang ngực, mỉm cười tươi nhìn camera, background vintage cosmetic shop",
    descriptionEn: "Young woman holding skincare product at chest level, bright smile to camera, vintage cosmetics shop background, skinfluencer vibe",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["friendly", "trendy", "approachable"],
    emoji: "💁‍♀️",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_water_splash",
    category: "skincare_tvc",
    name: "Water splash với serum",
    description: "Cô gái với water splash xung quanh mặt, freeze frame, da căng mọng tươi mới, holding sản phẩm",
    descriptionEn: "Young woman with water splash frozen around face, holding skincare product, fresh dewy radiant skin, dramatic freeze-frame TVC",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["fresh", "dramatic", "energy"],
    emoji: "💦",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_routine_steps",
    category: "skincare_tvc",
    name: "Giơ 3 sản phẩm step routine",
    description: "Cô gái giơ 3 sản phẩm xếp ngang trước ngực (cleanser, toner, serum), mỉm cười, background trắng minimal",
    descriptionEn: "Young woman holding 3 skincare products arranged horizontally at chest (cleanser, toner, serum), confident smile, minimal white background",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["organized", "premium", "clean"],
    emoji: "📦",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_glow_portrait",
    category: "skincare_tvc",
    name: "Portrait glowing skin với product",
    description: "Cô gái cận portrait với glowing dewy skin, cầm chai serum gần má, ánh sáng vàng dramatic",
    descriptionEn: "Close-up portrait of young woman with glowing dewy skin, holding serum bottle near cheek, dramatic warm golden lighting",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["luxury", "dramatic", "glowing"],
    emoji: "✨",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_smile_cream",
    category: "skincare_tvc",
    name: "Cười tươi cầm cream",
    description: "Cô gái cười tươi rạng rỡ, một tay cầm hộp kem dưỡng giơ ngang vai, background hồng pastel",
    descriptionEn: "Young woman with bright radiant smile, one hand holding cream jar at shoulder level, soft pink pastel background, fresh youthful energy",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["joyful", "youthful", "fresh"],
    emoji: "😊",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_lipstick_apply",
    category: "skincare_tvc",
    name: "Apply lipstick close-up",
    description: "Close-up cận cảnh cô gái apply lipstick lên môi, son rouge đỏ tươi, môi căng mọng, gương phản chiếu",
    descriptionEn: "Extreme close-up of young woman applying red lipstick, vibrant red lip color, plump lips, mirror reflection visible",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["sensual", "bold", "vibrant"],
    emoji: "💋",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_perfume_spray",
    category: "skincare_tvc",
    name: "Xịt nước hoa cận cổ",
    description: "Cô gái nghiêng cổ xịt nước hoa, mist visible trong không khí, đeo trang sức nhẹ, side profile",
    descriptionEn: "Young woman tilting neck spraying perfume, mist visible in air, light jewelry, elegant side profile, dramatic golden lighting",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["sensual", "elegant", "luxury"],
    emoji: "💨",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_powder_brush",
    category: "skincare_tvc",
    name: "Phủ phấn brush close-up",
    description: "Close-up cô gái cầm cọ trang điểm phủ phấn nhẹ lên má, particles bay trong không khí, mắt nhắm",
    descriptionEn: "Close-up of young woman applying powder with brush to cheek, powder particles floating in air, eyes closed serene, dramatic backlight",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["dreamy", "serene", "luxury"],
    emoji: "🖌",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_male_grooming",
    category: "skincare_tvc",
    name: "Nam giơ men's skincare",
    description: "Anh chàng cầm chai men's skincare giơ ngang ngực, side profile, sharp jawline, lighting cool blue",
    descriptionEn: "Young man holding men's skincare bottle at chest level, sharp side profile jawline, cool blue cinematic lighting, masculine premium vibe",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["masculine", "premium", "edgy"],
    emoji: "🧔",
    mode: "tvc_commercial",
    industry: "skincare",
  },
  {
    id: "sk_tvc_couple_routine",
    category: "skincare_tvc",
    name: "Cặp đôi cùng skincare",
    description: "Cặp đôi cùng đứng trước gương, cô gái apply cream cho anh chàng, không khí ấm cúng",
    descriptionEn: "Couple together at bathroom mirror, woman applying cream on man's face, warm intimate bathroom atmosphere, lifestyle skincare for couples",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["romantic", "warm", "modern"],
    emoji: "💑",
    mode: "tvc_commercial",
    industry: "skincare",
  },

  // ========================================================================
  // PRODUCT PHOTOGRAPHY MODE (15 themes — no subject)
  // ========================================================================
  {
    id: "sk_pp_marble_white",
    category: "skincare_product",
    name: "Marble trắng minimalist",
    description: "Sản phẩm trên marble trắng minimalist, lá xanh nhỏ trang trí, lighting studio softbox, top-down shot",
    descriptionEn: "Skincare product on white marble surface, small green leaves decorating, studio softbox lighting, clean minimalist top-down composition",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["clean", "premium", "minimalist"],
    emoji: "⬜",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_water_droplets",
    category: "skincare_product",
    name: "Water droplets trên product",
    description: "Sản phẩm với water droplets nhỏ trên bề mặt, hi-end product photography, lighting trắng pure",
    descriptionEn: "Skincare product covered in small water droplets, premium product photography, pure white lighting, hi-res macro",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["fresh", "premium", "clean"],
    emoji: "💧",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_pink_pastel",
    category: "skincare_product",
    name: "Pastel hồng dreamy",
    description: "Sản phẩm trên background pastel hồng nhẹ với ribbon và hoa hồng khô, lighting mềm",
    descriptionEn: "Skincare product on soft pastel pink background with silk ribbons and dried roses, soft diffused lighting, romantic dreamy aesthetic",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["romantic", "feminine", "dreamy"],
    emoji: "🌸",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_serum_drop_macro",
    category: "skincare_product",
    name: "Macro serum drop",
    description: "Macro shot giọt serum vàng dropping vào sản phẩm, freeze frame, lighting cinematic",
    descriptionEn: "Macro shot of golden serum droplet falling into product, freeze frame moment, cinematic dramatic lighting, hi-res detail",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["dramatic", "scientific", "premium"],
    emoji: "💛",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_wood_natural",
    category: "skincare_product",
    name: "Wood natural background",
    description: "Sản phẩm trên ván gỗ natural, hoa khô lavender, lighting vàng ấm, vibe organic",
    descriptionEn: "Skincare product on natural wood plank with dried lavender, warm golden lighting, organic natural aesthetic",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["organic", "natural", "warm"],
    emoji: "🪵",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_floating_premium",
    category: "skincare_product",
    name: "Floating premium product",
    description: "Sản phẩm float lửng giữa không trung, gradient background tím xanh, lighting dramatic premium",
    descriptionEn: "Skincare product floating mid-air against blue-purple gradient background, dramatic premium lighting, sci-fi luxury aesthetic",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["premium", "futuristic", "dramatic"],
    emoji: "🛸",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_routine_flatlay",
    category: "skincare_product",
    name: "Routine flat lay",
    description: "Top-down flat lay 5-7 sản phẩm skincare xếp grid, hoa cỏ trang trí, marble background",
    descriptionEn: "Top-down flat lay of 5-7 skincare products arranged in clean grid, decorative flowers and leaves, marble background, organized aesthetic",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["organized", "aesthetic", "complete"],
    emoji: "📐",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_bathroom_shelf",
    category: "skincare_product",
    name: "Bathroom shelf styled",
    description: "Sản phẩm trên kệ tắm marble, gương tròn, cây xanh nhỏ, lifestyle nhưng styled",
    descriptionEn: "Skincare product on marble bathroom shelf, round mirror, small plant, styled lifestyle product photography",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["lifestyle", "premium", "spa"],
    emoji: "🚿",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_ingredients",
    category: "skincare_product",
    name: "Product với ingredients",
    description: "Sản phẩm cùng ingredients tươi (lá trà xanh, hoa, vitamin), background trắng, top-down",
    descriptionEn: "Skincare product with fresh ingredients (green tea leaves, flowers, vitamins), white background, top-down composition showcasing natural origins",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["natural", "scientific", "fresh"],
    emoji: "🌿",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_gold_luxury",
    category: "skincare_product",
    name: "Gold accents luxury",
    description: "Sản phẩm với gold accents, background đen velvet, lighting dramatic, vibe luxury hi-end",
    descriptionEn: "Skincare product with gold accents, black velvet background, dramatic spot lighting, hi-end luxury aesthetic",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["luxury", "premium", "dramatic"],
    emoji: "🥇",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_pastel_geometric",
    category: "skincare_product",
    name: "Geometric pastel shapes",
    description: "Sản phẩm cùng geometric pastel shapes (khối hồng, lavender), composition modern minimalist",
    descriptionEn: "Skincare product with geometric pastel shapes (pink, lavender, mint blocks), modern minimalist composition, soft studio lighting",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["modern", "playful", "trendy"],
    emoji: "🔺",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_skincare_set",
    category: "skincare_product",
    name: "Skincare set giftbox",
    description: "Sản phẩm trong giftbox sang trọng, ribbon đỏ, hoa hồng khô, ánh sáng vàng warm holiday",
    descriptionEn: "Skincare set in luxury gift box with red ribbon, dried roses, warm golden holiday lighting, festive premium",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["festive", "luxury", "warm"],
    emoji: "🎁",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_glass_skin_macro",
    category: "skincare_product",
    name: "Macro skin texture cream",
    description: "Macro shot cream texture trên glass surface, sticky stretchy texture, dramatic lighting",
    descriptionEn: "Macro shot of cream texture on glass surface, sticky stretchy hydrating texture, dramatic side lighting, scientific premium feel",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["scientific", "premium", "tactile"],
    emoji: "🔬",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_lipstick_collection",
    category: "skincare_product",
    name: "Bộ sưu tập lipstick",
    description: "Tất cả son rouge xếp gradient màu từ hồng nhạt đến đỏ đậm, marble background, hi-end fashion",
    descriptionEn: "Lipstick collection arranged in color gradient from light pink to deep red, marble background, hi-end fashion magazine style",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["chic", "vibrant", "luxury"],
    emoji: "💄",
    mode: "product_photo",
    industry: "skincare",
  },
  {
    id: "sk_pp_ad_campaign_pure",
    category: "skincare_product",
    name: "Ad campaign pure white",
    description: "Sản phẩm 1 mình giữa khung hình background trắng pure, lighting clean, vibe ad campaign Vogue",
    descriptionEn: "Single skincare product centered against pure white background, clean professional lighting, Vogue ad campaign aesthetic",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["pure", "premium", "iconic"],
    emoji: "⚪",
    mode: "product_photo",
    industry: "skincare",
  },

  // ========================================================================
  // ADDITIONAL LIFESTYLE (5 themes)
  // ========================================================================
  {
    id: "sk_morning_dew",
    category: "skincare_lifestyle",
    name: "Buổi sáng dewy",
    description: "Cô gái vừa thức dậy, vén tóc, glass skin tự nhiên, nắng buổi sáng qua cửa sổ chiếu vào",
    descriptionEn: "Young woman just waking up, brushing hair aside, natural glass skin, soft morning sunlight through window",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["fresh", "natural", "morning"],
    emoji: "🌅",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_outdoor_glow",
    category: "skincare_lifestyle",
    name: "Outdoor glow tự nhiên",
    description: "Cô gái ngoài trời ánh nắng vàng cuối ngày, gió nhẹ, glass skin highlights, nhìn xa xăm",
    descriptionEn: "Young woman outdoors at golden hour, gentle wind, glass skin highlights catching light, gazing into distance, ethereal natural beauty",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["dreamy", "natural", "glowing"],
    emoji: "🌻",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_no_makeup_selfie",
    category: "skincare_lifestyle",
    name: "No-makeup selfie",
    description: "Cô gái cầm điện thoại tự sướng selfie không makeup, da bare skin glowing, biểu cảm tự nhiên",
    descriptionEn: "Young woman taking phone selfie no makeup, bare glowing skin, natural authentic expression, intimate self-portrait",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["authentic", "real", "fresh"],
    emoji: "📱",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_dermatologist_clinic",
    category: "skincare_lifestyle",
    name: "Tư vấn da tại clinic",
    description: "Cô gái ngồi tại derma clinic đối diện bác sĩ da liễu, ánh sáng trắng sạch, không khí professional",
    descriptionEn: "Young woman at dermatologist clinic consulting with skin specialist, clean white lighting, professional medical atmosphere",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["professional", "trustworthy", "clean"],
    emoji: "🩺",
    mode: "lifestyle",
    industry: "skincare",
  },
  {
    id: "sk_bedtime_routine",
    category: "skincare_lifestyle",
    name: "Routine đêm trước ngủ",
    description: "Cô gái tóc cột bun, mặc đồ pyjama silk, đang bôi night cream trên giường, đèn ngủ vàng ấm",
    descriptionEn: "Young woman with hair in bun, silk pajamas, applying night cream while sitting on bed, warm bedside lamp glow",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["cozy", "ritual", "intimate"],
    emoji: "🌙",
    mode: "lifestyle",
    industry: "skincare",
  },
];
