/**
 * TECH industry themes — v0.5
 * 40 themes covering Lifestyle / TVC / Product Photography modes.
 * Especially relevant for DungThichVar smart glasses content.
 */

import type { ThemePreset } from "../themes";

export const TECH_THEMES: ThemePreset[] = [
  // ========================================================================
  // LIFESTYLE (15)
  // ========================================================================
  {
    id: "tc_smart_glasses_walk",
    category: "tech_lifestyle",
    name: "Smart glasses dạo phố",
    description: "Anh chàng đeo smart glasses Ray-Ban Meta dạo phố Sài Gòn, mỉm cười, áo polo trắng",
    descriptionEn: "Young man wearing Ray-Ban Meta smart glasses walking through Saigon city street, slight smile, white polo shirt, urban modern lifestyle",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["modern", "urban", "tech"],
    emoji: "🕶", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_vision_pro_workspace",
    category: "tech_lifestyle",
    name: "Vision Pro workspace",
    description: "Anh chàng đeo Apple Vision Pro tại workspace tối, RGB lighting xanh, virtual screens phía trước",
    descriptionEn: "Young man wearing Apple Vision Pro at dark workspace with blue RGB lighting, suggested virtual screens floating ahead, futuristic productivity",
    cameraStyle: "BOKEH", time: "night", mood: ["futuristic", "tech", "focused"],
    emoji: "🥽", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_ar_glasses_cafe",
    category: "tech_lifestyle",
    name: "AR glasses outdoor cafe",
    description: "Cô gái đeo AR glasses ngồi cafe outdoor sang trọng, ánh sáng vàng, laptop phía trước",
    descriptionEn: "Young woman wearing AR smart glasses at upscale outdoor cafe, golden lighting, laptop on table, modern productivity lifestyle",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["sophisticated", "modern", "productive"],
    emoji: "👓", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_headphones_running",
    category: "tech_lifestyle",
    name: "Headphones chạy bộ",
    description: "Anh chàng đeo headphones Bose chạy bộ ven Hồ Tây sáng sớm, áo workout Nike",
    descriptionEn: "Young man wearing Bose headphones running along West Lake Hanoi at early morning, Nike workout outfit, fresh active lifestyle",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["energetic", "athletic", "fresh"],
    emoji: "🎧", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_livestream_gimbal",
    category: "tech_lifestyle",
    name: "Livestream với gimbal",
    description: "Cô gái cầm điện thoại trên gimbal đang livestream review sản phẩm tại cafe trendy",
    descriptionEn: "Young woman holding phone on gimbal stabilizer livestreaming product review at trendy cafe, content creator workflow",
    cameraStyle: "DOCUMENTARY", time: "indoor", mood: ["creator", "modern", "professional"],
    emoji: "📱", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_gaming_setup_rgb",
    category: "tech_lifestyle",
    name: "Gaming setup RGB",
    description: "Anh chàng ngồi gaming setup với RGB lighting xanh tím, headset gaming, mechanical keyboard",
    descriptionEn: "Young man at gaming setup with blue-purple RGB lighting, gaming headset, mechanical keyboard, dual monitors, focused gaming session",
    cameraStyle: "BOKEH", time: "night", mood: ["edgy", "tech", "immersive"],
    emoji: "🎮", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_apple_watch_running",
    category: "tech_lifestyle",
    name: "Apple Watch đang chạy bộ",
    description: "Cô gái cận cảnh tay đang chạy bộ kiểm tra Apple Watch, hiển thị heart rate",
    descriptionEn: "Close-up of young woman's wrist while running, checking Apple Watch displaying heart rate, athletic outfit visible, fitness lifestyle",
    cameraStyle: "BOKEH", time: "midday", mood: ["athletic", "modern", "active"],
    emoji: "⌚", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_ipad_drawing",
    category: "tech_lifestyle",
    name: "iPad Pro vẽ digital art",
    description: "Cô gái ngồi cafe vẽ digital art trên iPad Pro với Apple Pencil, sketches phía xung quanh",
    descriptionEn: "Young woman at cafe drawing digital art on iPad Pro with Apple Pencil, sketches around, creative artist lifestyle",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["creative", "modern", "focused"],
    emoji: "🎨", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_airpods_metro",
    category: "tech_lifestyle",
    name: "AirPods Pro trên metro",
    description: "Cô gái đeo AirPods Pro trắng ngồi trên metro Sài Gòn, đọc sách, vibe modern commuter",
    descriptionEn: "Young woman wearing white AirPods Pro on Saigon metro, reading book, modern urban commuter vibe",
    cameraStyle: "DOCUMENTARY", time: "indoor", mood: ["modern", "urban", "calm"],
    emoji: "🚇", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_vr_gaming",
    category: "tech_lifestyle",
    name: "VR headset chơi game",
    description: "Anh chàng đeo VR Quest đang chơi game tại phòng khách, motion blur tay vung",
    descriptionEn: "Young man wearing Meta Quest VR headset playing game in living room, motion blur on swinging arms, immersive gaming lifestyle",
    cameraStyle: "BOKEH", time: "indoor", mood: ["immersive", "tech", "playful"],
    emoji: "🥽", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_phone_film",
    category: "tech_lifestyle",
    name: "Quay phim bằng điện thoại",
    description: "Cô gái cầm điện thoại quay video TikTok ngoài phố, ring light gắn trên gimbal",
    descriptionEn: "Young woman filming TikTok video on phone outdoors, ring light attached to gimbal, content creator street workflow",
    cameraStyle: "DOCUMENTARY", time: "afternoon", mood: ["creator", "trendy", "casual"],
    emoji: "🎥", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_macbook_cafe",
    category: "tech_lifestyle",
    name: "MacBook làm việc cafe",
    description: "Cô gái ngồi cafe Đà Lạt làm việc trên MacBook Pro, ánh sáng cửa sổ ấm",
    descriptionEn: "Young woman working on MacBook Pro at Da Lat cafe, warm window light, productive remote work lifestyle",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["productive", "cozy", "focused"],
    emoji: "💻", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_tablet_kid",
    category: "tech_lifestyle",
    name: "Trẻ con dùng tablet học",
    description: "Bé học bài trên tablet với headphones, mẹ ngồi cạnh, không khí học tại nhà",
    descriptionEn: "Child learning on tablet with kids headphones, mother sitting beside helping, home education modern lifestyle",
    cameraStyle: "BOKEH", time: "indoor", mood: ["family", "educational", "modern"],
    emoji: "👶", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_drone_flying",
    category: "tech_lifestyle",
    name: "Bay drone outdoor",
    description: "Anh chàng cầm điều khiển drone bay drone trên cánh đồng lúa, sky xanh",
    descriptionEn: "Young man holding drone remote controller flying drone over rice fields, clear blue sky, outdoor tech lifestyle",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["adventure", "tech", "fresh"],
    emoji: "🚁", mode: "lifestyle", industry: "tech",
  },
  {
    id: "tc_e_scooter",
    category: "tech_lifestyle",
    name: "Xe điện e-scooter phố",
    description: "Cô gái đi e-scooter điện trên phố Sài Gòn buổi chiều, tóc bay trong gió",
    descriptionEn: "Young woman riding electric e-scooter through Saigon streets in afternoon, hair flowing in wind, modern urban mobility",
    cameraStyle: "DOCUMENTARY", time: "afternoon", mood: ["modern", "urban", "fresh"],
    emoji: "🛴", mode: "lifestyle", industry: "tech",
  },

  // ========================================================================
  // TVC COMMERCIAL (15)
  // ========================================================================
  {
    id: "tc_tvc_iphone_spotlight",
    category: "tech_tvc",
    name: "Giơ iPhone dưới spotlight",
    description: "Anh chàng giơ iPhone 16 Pro ngang ngực dưới spotlight đen, glass màn hình glow nhẹ",
    descriptionEn: "Young man holding iPhone 16 Pro at chest level under dramatic spotlight, screen glowing subtly, premium tech TVC, dark background",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "dramatic", "tech"],
    emoji: "📱", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_glasses_two_hands",
    category: "tech_tvc",
    name: "Cầm smart glasses hai tay",
    description: "Anh chàng cầm cặp smart glasses bằng hai tay giơ ngang ngực, gradient background tím xanh",
    descriptionEn: "Young man holding smart glasses with both hands at chest level, blue-purple gradient background, premium tech product TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "futuristic", "polished"],
    emoji: "🕶", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_glasses_side_profile",
    category: "tech_tvc",
    name: "Đeo glasses side profile",
    description: "Anh chàng đeo smart glasses side profile, blue light reflection trên mắt kính, jaw sharp",
    descriptionEn: "Young man wearing smart glasses in sharp side profile, blue light reflection on glass lens, defined jawline, masculine tech TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["edgy", "premium", "futuristic"],
    emoji: "💙", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_apple_ecosystem",
    category: "tech_tvc",
    name: "Apple ecosystem combo",
    description: "Cô gái ngồi desk với MacBook + iPhone + AirPods + Apple Watch, all-in-one shot",
    descriptionEn: "Young woman at desk with MacBook, iPhone, AirPods, and Apple Watch all visible, ecosystem combo TVC, premium clean workspace",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "organized", "modern"],
    emoji: "🍎", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_watch_hand",
    category: "tech_tvc",
    name: "Hand model với smartwatch",
    description: "Close-up cánh tay model nâng cổ tay đeo smartwatch chỉ giờ, lighting drama",
    descriptionEn: "Close-up of model's wrist showcasing smartwatch face displaying time, dramatic studio lighting, premium watch product TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "elegant", "tech"],
    emoji: "⌚", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_headphones_listen",
    category: "tech_tvc",
    name: "Đeo headphones nghe nhạc",
    description: "Cô gái đeo over-ear headphones, mắt nhắm enjoy, sound waves visualized phía sau",
    descriptionEn: "Young woman wearing over-ear headphones, eyes closed enjoying music, sound waves subtly visualized behind, premium audio TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["immersive", "premium", "serene"],
    emoji: "🎧", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_phone_camera",
    category: "tech_tvc",
    name: "iPhone camera shot",
    description: "Cô gái cầm iPhone giơ chụp ảnh phong cảnh, tay khác chỉnh setting, vibe content creator",
    descriptionEn: "Young woman holding iPhone capturing landscape photo, other hand adjusting settings, content creator photography TVC",
    cameraStyle: "BOKEH", time: "golden_hour", mood: ["creative", "premium", "outdoor"],
    emoji: "📸", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_glasses_kid",
    category: "tech_tvc",
    name: "Trẻ em đeo smart glasses học",
    description: "Bé đeo smart glasses học educational AR, mỉm cười enjoy, không khí gia đình ấm",
    descriptionEn: "Child wearing smart glasses experiencing educational AR content, smile of delight, warm family atmosphere TVC, parent in soft focus",
    cameraStyle: "BOKEH", time: "indoor", mood: ["educational", "warm", "innovative"],
    emoji: "👦", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_couple_workspace",
    category: "tech_tvc",
    name: "Cặp đôi cùng workspace",
    description: "Cặp đôi cùng làm việc tại home office, mỗi người dùng MacBook, smart glasses",
    descriptionEn: "Couple working together at home office, each on MacBook, smart glasses on table, modern remote work couple TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["modern", "productive", "warm"],
    emoji: "💑", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_pro_creator",
    category: "tech_tvc",
    name: "Pro creator setup",
    description: "Anh chàng pro YouTuber tại studio setup hoàn chỉnh, camera + ring light + microphone",
    descriptionEn: "Young man pro YouTuber at full studio setup with camera, ring light, microphone, premium content creator TVC vibe",
    cameraStyle: "BOKEH", time: "indoor", mood: ["professional", "creative", "tech"],
    emoji: "🎬", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_athlete_watch",
    category: "tech_tvc",
    name: "Athlete với smartwatch",
    description: "Athlete chuyên nghiệp kiểm tra smartwatch sau workout, mồ hôi, gym background",
    descriptionEn: "Professional athlete checking smartwatch metrics after workout, sweat glistening, gym background, fitness tech TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["athletic", "professional", "energetic"],
    emoji: "💪", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_phone_unbox",
    category: "tech_tvc",
    name: "Mở hộp iPhone unboxing",
    description: "Cô gái mở hộp iPhone mới trên bàn trắng, slow-motion lifting, camera focus product",
    descriptionEn: "Young woman unboxing new iPhone on white surface, slow-motion lifting motion, camera focused on product, premium unboxing TVC",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "exciting", "clean"],
    emoji: "📦", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_drone_pilot",
    category: "tech_tvc",
    name: "Drone pilot ngoài trời",
    description: "Anh chàng cầm drone DJI nâng lên trước mặt, drone chuẩn bị cất cánh, sky background",
    descriptionEn: "Young man holding DJI drone aloft about to launch, sky background, premium drone product TVC, adventurous outdoor",
    cameraStyle: "BOKEH", time: "midday", mood: ["adventure", "premium", "tech"],
    emoji: "🚁", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_glasses_man_walk",
    category: "tech_tvc",
    name: "Nam đeo glasses walking",
    description: "Anh chàng vest đen đeo smart glasses bước về phía camera, urban background blur",
    descriptionEn: "Young man in black blazer wearing smart glasses walking toward camera, urban background motion blur, sophisticated tech TVC",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["sophisticated", "modern", "confident"],
    emoji: "🚶", mode: "tvc_commercial", industry: "tech",
  },
  {
    id: "tc_tvc_smart_home",
    category: "tech_tvc",
    name: "Smart home control panel",
    description: "Cô gái ngồi sofa cầm tablet điều khiển smart home, đèn nhà thay đổi màu",
    descriptionEn: "Young woman on sofa controlling smart home from tablet, home lights changing colors, modern smart home TVC",
    cameraStyle: "BOKEH", time: "night", mood: ["modern", "futuristic", "comfortable"],
    emoji: "🏠", mode: "tvc_commercial", industry: "tech",
  },

  // ========================================================================
  // PRODUCT PHOTOGRAPHY (10) — no subject
  // ========================================================================
  {
    id: "tc_pp_glasses_gradient",
    category: "tech_product",
    name: "Smart glasses gradient",
    description: "Cặp smart glasses trên gradient tím xanh, lighting dramatic, hi-end product",
    descriptionEn: "Smart glasses against blue-purple gradient background, dramatic premium lighting, hi-end tech product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "futuristic", "tech"],
    emoji: "🕶", mode: "product_photo", industry: "tech",
  },
  {
    id: "tc_pp_iphone_box_dark",
    category: "tech_product",
    name: "iPhone box trên nền đen",
    description: "Hộp iPhone đen sang trọng trên background đen velvet, lighting drama spot",
    descriptionEn: "Premium iPhone black box on black velvet background, dramatic spot lighting, luxury Apple product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "luxury", "minimal"],
    emoji: "📦", mode: "product_photo", industry: "tech",
  },
  {
    id: "tc_pp_headphones_case",
    category: "tech_product",
    name: "Headphones với case mở",
    description: "Headphones cao cấp với case mở phía sau, accessories xếp gọn, lighting clean",
    descriptionEn: "Premium headphones with open carry case behind, accessories arranged neatly, clean studio lighting, audio product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "organized", "clean"],
    emoji: "🎧", mode: "product_photo", industry: "tech",
  },
  {
    id: "tc_pp_floating_premium",
    category: "tech_product",
    name: "Floating tech product",
    description: "Sản phẩm tech float lửng giữa không trung, gradient background, gravity defying composition",
    descriptionEn: "Tech product floating mid-air, gradient background, gravity-defying composition, premium futuristic photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["futuristic", "premium", "dramatic"],
    emoji: "🛸", mode: "product_photo", industry: "tech",
  },
  {
    id: "tc_pp_ecosystem_flatlay",
    category: "tech_product",
    name: "Tech ecosystem flat lay",
    description: "Top-down flat lay MacBook + iPhone + AirPods + Apple Watch + Pencil, tổ chức gọn gàng",
    descriptionEn: "Top-down flat lay of MacBook, iPhone, AirPods, Apple Watch, Pencil, neatly organized, premium ecosystem product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["organized", "premium", "ecosystem"],
    emoji: "📐", mode: "product_photo", industry: "tech",
  },
  {
    id: "tc_pp_glasses_led_glow",
    category: "tech_product",
    name: "Smart glasses LED glow",
    description: "Smart glasses với LED nhỏ glow xanh trên gọng, background đen, dramatic close-up",
    descriptionEn: "Smart glasses with small blue LED glow on frame, black background, dramatic close-up, futuristic AR glasses product",
    cameraStyle: "BOKEH", time: "indoor", mood: ["futuristic", "edgy", "tech"],
    emoji: "💡", mode: "product_photo", industry: "tech",
  },
  {
    id: "tc_pp_smartwatch_strap",
    category: "tech_product",
    name: "Smartwatch với straps",
    description: "Smartwatch với 5 strap colors xếp xung quanh, marble background, premium accessories",
    descriptionEn: "Smartwatch with 5 colorful straps arranged around, marble background, premium accessories collection product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "stylish", "organized"],
    emoji: "⌚", mode: "product_photo", industry: "tech",
  },
  {
    id: "tc_pp_keyboard_mechanical",
    category: "tech_product",
    name: "Mechanical keyboard RGB",
    description: "Mechanical keyboard với RGB lighting, top-down macro shot, gaming aesthetic",
    descriptionEn: "Mechanical gaming keyboard with vibrant RGB lighting, top-down macro shot, gaming aesthetic, premium peripherals photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["gaming", "edgy", "vibrant"],
    emoji: "⌨️", mode: "product_photo", industry: "tech",
  },
  {
    id: "tc_pp_drone_carbon",
    category: "tech_product",
    name: "Drone trên carbon fiber",
    description: "DJI drone đặt trên carbon fiber surface, propellers visible, lighting drama đen-xanh",
    descriptionEn: "DJI drone placed on carbon fiber surface, propellers clearly visible, dramatic black-blue lighting, premium drone product photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["premium", "tech", "edgy"],
    emoji: "🚁", mode: "product_photo", industry: "tech",
  },
  {
    id: "tc_pp_phone_water_splash",
    category: "tech_product",
    name: "Phone water splash",
    description: "Smartphone với water splash freeze frame xung quanh, demonstrating water resistance",
    descriptionEn: "Smartphone with water splash freeze-frame surrounding it, demonstrating water resistance, premium tech product TVC photography",
    cameraStyle: "BOKEH", time: "indoor", mood: ["dramatic", "premium", "fresh"],
    emoji: "💦", mode: "product_photo", industry: "tech",
  },
];
