/**
 * TRAVEL / LIFESTYLE new themes — v0.5
 * 30 NEW themes (227 themes cũ tự động map vào industry "travel" qua merger)
 */

import type { ThemePreset } from "../themes";

export const TRAVEL_NEW_THEMES: ThemePreset[] = [
  // ========================================================================
  // LIFESTYLE TRAVEL (30) — themes mới chưa có trong 227 cũ
  // ========================================================================
  {
    id: "tv_boarding_flight",
    category: "travel_lifestyle",
    name: "Boarding flight passport",
    description: "Cô gái cầm passport và boarding pass tại sảnh sân bay Tân Sơn Nhất, vali kéo, vibe travel",
    descriptionEn: "Young woman holding passport and boarding pass at Tan Son Nhat airport hall, rolling suitcase, travel anticipation vibe",
    cameraStyle: "BOKEH", time: "indoor", mood: ["travel", "modern", "exciting"],
    emoji: "✈️", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_hotel_checkin",
    category: "travel_lifestyle",
    name: "Hotel check-in moment",
    description: "Cô gái cầm chìa khóa hotel cao cấp tại reception, vali bên cạnh, lobby sang trọng",
    descriptionEn: "Young woman holding luxury hotel key card at reception, suitcase beside, sophisticated marble lobby, premium travel experience",
    cameraStyle: "BOKEH", time: "indoor", mood: ["luxury", "anticipating", "modern"],
    emoji: "🏨", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_resort_breakfast",
    category: "travel_lifestyle",
    name: "Resort breakfast bãi biển",
    description: "Cô gái mặc đầm trắng ăn breakfast tại resort bãi biển Phú Quốc, fruits, ocean view",
    descriptionEn: "Young woman in white dress having breakfast at Phu Quoc beachfront resort, fresh fruits, ocean view, luxury vacation morning",
    cameraStyle: "BOKEH", time: "midday", mood: ["luxury", "vacation", "fresh"],
    emoji: "🌴", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_cruise_sunset",
    category: "travel_lifestyle",
    name: "Cruise deck sunset",
    description: "Cô gái áo voan trắng đứng deck du thuyền lúc hoàng hôn vàng cam, gió biển bay tóc",
    descriptionEn: "Young woman in white chiffon dress on cruise ship deck at golden sunset, sea wind blowing hair, romantic luxury cruise vacation",
    cameraStyle: "BOKEH", time: "golden_hour", mood: ["romantic", "luxury", "scenic"],
    emoji: "🛳", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_balloon_mocchau",
    category: "travel_lifestyle",
    name: "Hot air balloon Mộc Châu",
    description: "Cô gái áo trắng đứng trên thảm hoa cải Mộc Châu cùng hot air balloons phía sau",
    descriptionEn: "Young woman in white among yellow rapeseed fields of Moc Chau with hot air balloons rising behind, scenic Northern Vietnam adventure",
    cameraStyle: "BOKEH", time: "midday", mood: ["adventure", "scenic", "vibrant"],
    emoji: "🎈", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_camping_tent",
    category: "travel_lifestyle",
    name: "Camping tent núi rừng",
    description: "Cô gái mặc áo flannel ngồi trước tent camping núi cao, lửa trại nhỏ, sao đêm",
    descriptionEn: "Young woman in flannel shirt sitting before mountain camping tent, small campfire, starry night sky, outdoor adventure travel",
    cameraStyle: "DOCUMENTARY", time: "night", mood: ["adventure", "cozy", "nature"],
    emoji: "⛺", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_spa_retreat",
    category: "travel_lifestyle",
    name: "Spa retreat resort",
    description: "Cô gái mặc khăn tắm đang massage tại spa resort, trà thảo dược cạnh, không khí zen",
    descriptionEn: "Young woman in spa towel during massage treatment at resort spa, herbal tea beside, zen atmosphere, luxury wellness travel",
    cameraStyle: "BOKEH", time: "indoor", mood: ["relaxed", "luxury", "wellness"],
    emoji: "💆‍♀️", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_cooking_class",
    category: "travel_lifestyle",
    name: "Cooking class du lịch",
    description: "Cô gái cầm đồ nghề học cooking class tại Hội An, làm phở, giáo viên hướng dẫn",
    descriptionEn: "Young woman with apron learning Vietnamese cooking class in Hoi An, making pho, instructor guiding, immersive travel experience",
    cameraStyle: "DOCUMENTARY", time: "indoor", mood: ["immersive", "cultural", "authentic"],
    emoji: "👩‍🍳", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_local_market",
    category: "travel_lifestyle",
    name: "Local market Bali",
    description: "Cô gái dạo chợ địa phương Bali style, sạp bán fruit nhiệt đới và gia vị, không khí lịch sử",
    descriptionEn: "Young woman exploring local Balinese-style market with tropical fruit stalls and spices, authentic immersive travel atmosphere",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["authentic", "vibrant", "cultural"],
    emoji: "🛒", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_night_market_thai",
    category: "travel_lifestyle",
    name: "Night market Thái",
    description: "Cô gái dạo night market Bangkok, đèn neon đỏ vàng, đồ ăn streetfood Thái",
    descriptionEn: "Young woman walking Bangkok night market, vibrant red and yellow neon lights, Thai street food stalls, exciting nightlife travel",
    cameraStyle: "DOCUMENTARY", time: "night", mood: ["vibrant", "exotic", "exciting"],
    emoji: "🏮", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_passport_stamp",
    category: "travel_lifestyle",
    name: "Passport stamp close-up",
    description: "Close-up passport mở thấy nhiều stamps khác nhau, vé máy bay cạnh, vibe travel collector",
    descriptionEn: "Close-up of open passport showing multiple country stamps, boarding passes beside, travel collector aesthetic",
    cameraStyle: "BOKEH", time: "indoor", mood: ["nostalgic", "adventurous", "achievement"],
    emoji: "🛂", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_train_journey",
    category: "travel_lifestyle",
    name: "Train journey window",
    description: "Cô gái nhìn qua cửa sổ tàu hỏa SE7 phong cảnh Việt Nam, sách trên đùi",
    descriptionEn: "Young woman looking through window of SE7 Vietnamese reunification train, scenic countryside passing by, book on lap, slow travel vibe",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["contemplative", "scenic", "slow"],
    emoji: "🚆", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_bus_phuot",
    category: "travel_lifestyle",
    name: "Phượt xe máy đường núi",
    description: "Cặp đôi đi phượt xe máy đường đèo Hà Giang, mũ bảo hiểm full face, áo gió",
    descriptionEn: "Couple on motorcycle adventure road trip through Ha Giang mountain pass, full-face helmets, windbreaker jackets, adventurous travel",
    cameraStyle: "DOCUMENTARY", time: "afternoon", mood: ["adventure", "scenic", "freedom"],
    emoji: "🏍", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_temple_kyoto",
    category: "travel_lifestyle",
    name: "Temple Kyoto kimono",
    description: "Cô gái mặc kimono dạo Fushimi Inari shrine Kyoto, hàng ngàn cổng đỏ tori",
    descriptionEn: "Young woman in kimono walking Fushimi Inari shrine in Kyoto, thousands of red torii gates, traditional Japanese travel experience",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["traditional", "cultural", "scenic"],
    emoji: "⛩", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_kayak_lagoon",
    category: "travel_lifestyle",
    name: "Kayak lagoon Hạ Long",
    description: "Cô gái chèo kayak qua hang động Hạ Long, vách đá karst hùng vĩ phía trên",
    descriptionEn: "Young woman kayaking through Ha Long Bay grotto, towering karst limestone cliffs above, adventurous nature travel",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["adventure", "scenic", "natural"],
    emoji: "🛶", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_road_trip_car",
    category: "travel_lifestyle",
    name: "Road trip xe convertible",
    description: "Cô gái lái xe convertible đường ven biển Mũi Né, tóc bay trong gió, hat",
    descriptionEn: "Young woman driving convertible car along Mui Ne coastal road, hair flowing in wind, sun hat, scenic ocean drive vacation",
    cameraStyle: "DOCUMENTARY", time: "afternoon", mood: ["freedom", "adventure", "summer"],
    emoji: "🚗", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_snorkel_underwater",
    category: "travel_lifestyle",
    name: "Snorkel Côn Đảo",
    description: "Cô gái mặc đồ snorkel với mặt nạ và ống thở tại bãi biển Côn Đảo, fish reef",
    descriptionEn: "Young woman in snorkeling gear with mask and snorkel at Con Dao beach, coral reef visible, marine adventure travel",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["adventure", "tropical", "marine"],
    emoji: "🤿", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_yoga_beach",
    category: "travel_lifestyle",
    name: "Yoga sunrise bãi biển",
    description: "Cô gái yoga pose tree pose tại bãi biển sunrise, sand vàng, sóng nhẹ phía xa",
    descriptionEn: "Young woman in yoga tree pose at beach during sunrise, golden sand, gentle waves in distance, wellness retreat travel",
    cameraStyle: "BOKEH", time: "golden_hour", mood: ["wellness", "serene", "fresh"],
    emoji: "🧘‍♀️", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_wine_tour",
    category: "travel_lifestyle",
    name: "Wine tour Đà Lạt",
    description: "Cô gái thử rượu vang tại winery Đà Lạt, vườn nho phía sau, ly rượu đỏ",
    descriptionEn: "Young woman wine tasting at Da Lat winery, vineyard behind, red wine glass in hand, sophisticated wine country travel",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["sophisticated", "scenic", "luxury"],
    emoji: "🍷", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_safari_jeep",
    category: "travel_lifestyle",
    name: "Safari jeep hoang dã",
    description: "Cô gái ngồi jeep safari nhìn voi rừng tại vườn quốc gia Yok Đôn, khaki outfit",
    descriptionEn: "Young woman on safari jeep watching wild elephant at Yok Don National Park Vietnam, khaki safari outfit, wildlife adventure travel",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["adventure", "wildlife", "exotic"],
    emoji: "🐘", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_skiing_mountain",
    category: "travel_lifestyle",
    name: "Skiing núi Nhật Bản",
    description: "Cô gái mặc đồ ski color đứng đỉnh núi Niseko Nhật, tuyết phủ phía sau",
    descriptionEn: "Young woman in colorful ski outfit atop Niseko Japan mountain, snow-covered slopes behind, winter sports travel",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["adventure", "winter", "exhilarating"],
    emoji: "⛷", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_thermal_onsen",
    category: "travel_lifestyle",
    name: "Onsen thermal Nhật",
    description: "Cô gái thư giãn trong onsen Nhật Bản, hơi nước bay, ryokan view núi tuyết",
    descriptionEn: "Young woman relaxing in Japanese onsen hot spring bath, steam rising, ryokan with snowy mountain view, wellness travel Japan",
    cameraStyle: "BOKEH", time: "indoor", mood: ["relaxed", "exotic", "wellness"],
    emoji: "♨️", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_hike_mountain",
    category: "travel_lifestyle",
    name: "Hiking trekking Fansipan",
    description: "Cô gái mặc trekking outfit đứng đỉnh Fansipan, mây phủ chân, lá cờ Việt Nam",
    descriptionEn: "Young woman in trekking outfit atop Fansipan peak, clouds below feet, Vietnam flag, achievement adventure travel",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["adventure", "achievement", "majestic"],
    emoji: "⛰", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_diving_reef",
    category: "travel_lifestyle",
    name: "Diving coral reef",
    description: "Cô gái diver với scuba gear giữa coral reef Phú Quốc, fish schools xung quanh",
    descriptionEn: "Young woman diver with scuba gear among Phu Quoc coral reef, fish schools surrounding, underwater marine adventure",
    cameraStyle: "DOCUMENTARY", time: "midday", mood: ["adventure", "marine", "exotic"],
    emoji: "🐠", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_villa_pool",
    category: "travel_lifestyle",
    name: "Villa pool tropical",
    description: "Cô gái mặc bikini đỏ ngồi mép infinity pool villa, biển xanh phía sau, luxury",
    descriptionEn: "Young woman in red bikini at edge of villa infinity pool, blue ocean horizon behind, luxury tropical vacation",
    cameraStyle: "BOKEH", time: "midday", mood: ["luxury", "tropical", "summer"],
    emoji: "🏖", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_lighthouse",
    category: "travel_lifestyle",
    name: "Lighthouse Đại Lãnh",
    description: "Cô gái mặc đầm voan trắng đứng trên đỉnh đèn biển Đại Lãnh Phú Yên, ocean view",
    descriptionEn: "Young woman in white chiffon dress at top of Dai Lanh lighthouse Phu Yen, panoramic ocean view, scenic Vietnamese coastal travel",
    cameraStyle: "BOKEH", time: "afternoon", mood: ["scenic", "romantic", "remote"],
    emoji: "🗼", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_temple_angkor",
    category: "travel_lifestyle",
    name: "Angkor Wat sunrise",
    description: "Cô gái mặc áo trắng đứng trước Angkor Wat lúc bình minh, mặt trời lên phía sau temple",
    descriptionEn: "Young woman in white standing before Angkor Wat at sunrise, sun rising behind ancient temple silhouette, scenic Cambodia travel",
    cameraStyle: "BOKEH", time: "golden_hour", mood: ["spiritual", "majestic", "exotic"],
    emoji: "🛕", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_iceberg_norway",
    category: "travel_lifestyle",
    name: "Norway fjord boat",
    description: "Cô gái áo khoác len đứng trên thuyền fjord Na Uy, mountains tuyết hai bên, lighting moody",
    descriptionEn: "Young woman in wool coat on boat through Norway fjord, snowy mountains on both sides, moody atmospheric Scandinavian travel",
    cameraStyle: "BOKEH", time: "overcast", mood: ["moody", "scenic", "remote"],
    emoji: "🏔", mode: "lifestyle", industry: "travel",
  },
  {
    id: "tv_aurora_viewing",
    category: "travel_lifestyle",
    name: "Aurora ngắm bắc cực quang",
    description: "Cô gái mặc đồ thermal đứng ngắm aurora xanh tím ở Iceland, snow background",
    descriptionEn: "Young woman in thermal gear watching green-purple aurora borealis in Iceland, snow landscape, magical northern lights travel",
    cameraStyle: "DOCUMENTARY", time: "night", mood: ["magical", "scenic", "remote"],
    emoji: "🌌", mode: "lifestyle", industry: "travel",
  },
];
