/**
 * KSP Image - Themes Catalog
 *
 * 12 categories with ~120 sub-themes total.
 * Each theme provides:
 * - Vietnamese description (idea.raw)
 * - Pre-translated English (avoids API call for these)
 * - Recommended camera style (BOKEH or DOCUMENTARY)
 * - Time/lighting hint
 * - Mood tags
 *
 * Free-form ideas typed by users still get translated via Gemini API.
 */

import type { CameraStyle } from "../types";
import { ADDITIONAL_THEMES } from "./themesAdditional";


export interface ThemePreset {
  id: string;
  category: string;
  name: string;
  /** Vietnamese description (what user sees) */
  description: string;
  /** Pre-translated EN (used in prompt assembly) */
  descriptionEn: string;
  /** Recommended camera style */
  cameraStyle: CameraStyle;
  /** Time / lighting */
  time?:
    | "golden_hour"
    | "blue_hour"
    | "midday"
    | "afternoon"
    | "night"
    | "overcast"
    | "indoor";
  /** Mood tags */
  mood?: string[];
  /** Emoji for UI */
  emoji: string;
  /** NEW v0.5: which mode this theme is designed for (defaults to "lifestyle" for old themes) */
  mode?: "lifestyle" | "tvc_commercial" | "product_photo" | "editorial_fashion";
  /** NEW v0.5: which industry this theme belongs to (defaults to "travel" for old themes) */
  industry?: "skincare" | "fnb" | "tech" | "fashion" | "travel" | "general";
}

export interface ThemeCategory {
  id: string;
  name: string;
  emoji: string;
  description: string;
}

// ============================================================================
// CATEGORIES (12 main groups)
// ============================================================================

export const THEME_CATEGORIES: ThemeCategory[] = [
  { id: "season", name: "Theo Mùa", emoji: "🌸", description: "Xuân, Hạ, Thu, Đông" },
  { id: "festival", name: "Lễ Hội & Sự Kiện", emoji: "🎊", description: "Tết, Trung Thu, Vu Lan..." },
  { id: "location", name: "Địa Điểm Việt Nam", emoji: "🇻🇳", description: "Hà Nội, Sài Gòn, Hội An..." },
  { id: "outfit", name: "Trang Phục Truyền Thống", emoji: "👗", description: "Áo dài, áo bà ba, dân tộc" },
  { id: "lifestyle", name: "Đời Sống", emoji: "☕", description: "Cafe, ẩm thực, công sở" },
  { id: "travel", name: "Du Lịch & Nghỉ Dưỡng", emoji: "🏖", description: "Biển, resort, sân bay" },
  { id: "sport", name: "Thể Thao & Năng Động", emoji: "💪", description: "Pickleball, gym, yoga..." },
  { id: "career", name: "Công Việc / Nghề Nghiệp", emoji: "💼", description: "Office, y tế, giáo viên" },
  { id: "time", name: "Khung Giờ Đặc Trưng", emoji: "🌃", description: "Bình minh, hoàng hôn, đêm" },
  { id: "cinema", name: "Phong Cách Điện Ảnh", emoji: "🎬", description: "Wong Kar Wai, Ghibli, Y2K" },
  { id: "vehicle", name: "Phương Tiện", emoji: "🛵", description: "Vespa, xe đạp, tàu hỏa" },
  { id: "style", name: "Phong Cách Biên Tập", emoji: "🎨", description: "Cottagecore, old money, dark academia" },
];

// ============================================================================
// THEMES (120 items)
// ============================================================================

const BASE_THEMES: ThemePreset[] = [
  // ===== 1. SEASON (mùa) =====
  {
    id: "spring_hanoi_peach",
    category: "season",
    name: "Hoa đào Hà Nội",
    description: "Cô gái mặc áo dài đỏ đứng giữa rừng hoa đào nở rộ ở Nhật Tân, Hà Nội, mùa xuân đầu năm",
    descriptionEn: "Young woman in red ao dai standing among blooming peach blossoms at Nhat Tan, Hanoi, early spring",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["dreamy", "spring", "traditional"],
    emoji: "🌸",
  },
  {
    id: "spring_southern_apricot",
    category: "season",
    name: "Hoa mai vàng miền Nam",
    description: "Cô gái áo dài vàng đứng cạnh cây mai vàng nở rộ trong sân nhà miền Nam dịp Tết",
    descriptionEn: "Young woman in yellow ao dai beside a blooming yellow apricot tree in a Southern Vietnamese courtyard during Tet",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["festive", "warm", "traditional"],
    emoji: "🌼",
  },
  {
    id: "spring_ban_flower",
    category: "season",
    name: "Hoa ban Tây Bắc",
    description: "Cô gái dân tộc đứng giữa rừng hoa ban trắng nở rộ ở vùng núi Tây Bắc",
    descriptionEn: "Young ethnic woman standing among white Bauhinia (ban) flowers blooming in the Northwestern mountains of Vietnam",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["serene", "ethnic", "natural"],
    emoji: "🌷",
  },
  {
    id: "spring_dalat_garden",
    category: "season",
    name: "Vườn hoa Đà Lạt mùa xuân",
    description: "Cô gái dạo bộ trong vườn hoa Đà Lạt với cẩm tú cầu xanh tím nở rộ vào mùa xuân",
    descriptionEn: "Young woman strolling through Da Lat flower garden with blooming blue and purple hydrangeas in spring",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["romantic", "fresh", "dreamy"],
    emoji: "💐",
  },
  {
    id: "spring_canola_mocchau",
    category: "season",
    name: "Đồng cải vàng Mộc Châu",
    description: "Cô gái áo trắng chạy giữa cánh đồng hoa cải vàng rực ở Mộc Châu, Sơn La",
    descriptionEn: "Young woman in white running through a vibrant yellow canola flower field in Moc Chau, Son La",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["joyful", "free", "bright"],
    emoji: "🌻",
  },
  {
    id: "summer_phuquoc_beach",
    category: "season",
    name: "Bãi biển Phú Quốc",
    description: "Cô gái mặc áo tắm xanh đứng trên bãi cát trắng Phú Quốc, sóng biển vỗ nhẹ, hoàng hôn vàng",
    descriptionEn: "Young woman in blue swimsuit standing on white sand of Phu Quoc beach, gentle waves, golden sunset",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["summer", "tropical", "relaxed"],
    emoji: "🏖",
  },
  {
    id: "summer_phoenix_school",
    category: "season",
    name: "Phượng đỏ sân trường",
    description: "Cô gái áo dài trắng nữ sinh đứng dưới tán phượng đỏ rực sân trường, mùa hè cuối năm học",
    descriptionEn: "Young schoolgirl in white ao dai uniform standing under bright red phoenix flowers in schoolyard, end of summer school year",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["nostalgic", "youthful", "summer"],
    emoji: "🌺",
  },
  {
    id: "summer_lotus_dongthap",
    category: "season",
    name: "Hoa sen Đồng Tháp",
    description: "Cô gái áo bà ba ngồi cạnh hồ sen Đồng Tháp Mười, hoa sen hồng nở rộ, ánh sáng tự nhiên",
    descriptionEn: "Young woman in traditional ao ba ba sitting beside lotus pond in Dong Thap Muoi, pink lotus flowers blooming, natural light",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["serene", "rural", "traditional"],
    emoji: "🪷",
  },
  {
    id: "summer_hoian_bougainvillea",
    category: "season",
    name: "Hoa giấy Hội An",
    description: "Cô gái dạo bộ phố cổ Hội An với hoa giấy hồng tím nở rộ trên tường vàng cổ kính",
    descriptionEn: "Young woman strolling Hoi An old town with pink and purple bougainvillea blooming on ancient yellow walls",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["romantic", "vintage", "warm"],
    emoji: "💮",
  },
  {
    id: "autumn_mucangchai",
    category: "season",
    name: "Lúa chín Mù Cang Chải",
    description: "Cô gái dân tộc Mông đứng trên ruộng bậc thang lúa chín vàng ở Mù Cang Chải",
    descriptionEn: "Young Hmong ethnic woman standing on golden rice terraces of Mu Cang Chai during harvest season",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["authentic", "ethnic", "vibrant"],
    emoji: "🌾",
  },
  {
    id: "autumn_hanoi_yellow",
    category: "season",
    name: "Lá vàng Hà Nội",
    description: "Cô gái mặc áo măng tô dạo bộ phố Phan Đình Phùng Hà Nội mùa thu, lá vàng rơi rụng",
    descriptionEn: "Young woman in beige trench coat strolling Phan Dinh Phung Street in Hanoi autumn, yellow leaves falling",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["nostalgic", "elegant", "autumn"],
    emoji: "🍂",
  },
  {
    id: "autumn_buckwheat_hagiang",
    category: "season",
    name: "Tam giác mạch Hà Giang",
    description: "Cô gái đứng giữa cánh đồng hoa tam giác mạch tím hồng ở Hà Giang vào mùa thu",
    descriptionEn: "Young woman standing in a field of pink-purple buckwheat flowers in Ha Giang during autumn",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["dreamy", "remote", "vibrant"],
    emoji: "🌸",
  },
  {
    id: "winter_sapa",
    category: "season",
    name: "Sapa sương mù",
    description: "Cô gái mặc áo len dày đứng giữa Sapa sương mù dày đặc, đồi núi mờ ảo phía sau",
    descriptionEn: "Young woman in thick wool coat standing in heavy mist of Sapa, mountains barely visible in background",
    cameraStyle: "BOKEH",
    time: "overcast",
    mood: ["misty", "cold", "ethereal"],
    emoji: "❄️",
  },
  {
    id: "winter_dalat",
    category: "season",
    name: "Đà Lạt mùa đông",
    description: "Cô gái mặc áo khoác len dạo bộ rừng thông Đà Lạt sương sớm mùa đông",
    descriptionEn: "Young woman in wool jacket walking through pine forest of Da Lat in early winter morning mist",
    cameraStyle: "BOKEH",
    time: "overcast",
    mood: ["cozy", "dreamy", "winter"],
    emoji: "🌲",
  },
  {
    id: "winter_dahlia",
    category: "season",
    name: "Hoa dã quỳ vàng",
    description: "Cô gái dạo giữa cánh đồng hoa dã quỳ vàng rực ở Đà Lạt vào tháng 11",
    descriptionEn: "Young woman walking through bright yellow wild sunflower (da quy) field in Da Lat in November",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["warm", "wildflower", "autumn"],
    emoji: "🌻",
  },

  // ===== 2. FESTIVAL (lễ hội) =====
  {
    id: "tet_nguyenhue_flower",
    category: "festival",
    name: "Đường hoa Nguyễn Huệ",
    description: "Cô gái áo dài đỏ đứng tạo dáng tại đường hoa Nguyễn Huệ Sài Gòn dịp Tết, đèn lồng và hoa rực rỡ",
    descriptionEn: "Young woman in red ao dai posing at Nguyen Hue flower street in Saigon during Tet, vibrant lanterns and flowers",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["festive", "vibrant", "traditional"],
    emoji: "🧧",
  },
  {
    id: "tet_flower_market",
    category: "festival",
    name: "Chợ hoa Tết",
    description: "Cô gái áo dài hồng đi chợ hoa Tết với cành đào, không khí Tết Hà Nội nhộn nhịp",
    descriptionEn: "Young woman in pink ao dai shopping at Tet flower market carrying peach blossom branches, bustling Hanoi Tet atmosphere",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["festive", "lively", "traditional"],
    emoji: "🌸",
  },
  {
    id: "tet_aodai_apricot",
    category: "festival",
    name: "Áo dài bên cây mai",
    description: "Cô gái áo dài lụa vàng đứng cạnh cây mai vàng nở rộ trong sân nhà cổ ngày Tết",
    descriptionEn: "Young woman in yellow silk ao dai beside a fully blooming yellow apricot tree in an old house courtyard during Tet",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["traditional", "warm", "elegant"],
    emoji: "🌼",
  },
  {
    id: "tet_banh_chung",
    category: "festival",
    name: "Gói bánh chưng Tết",
    description: "Cô gái cùng gia đình gói bánh chưng vuông trên chiếu, lá dong xanh, gạo nếp trắng, dịp Tết Bắc Bộ",
    descriptionEn: "Young woman with family wrapping square banh chung on a mat, green dong leaves, white sticky rice, Northern Vietnamese Tet",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["family", "traditional", "warm"],
    emoji: "🍙",
  },
  {
    id: "tet_lixi",
    category: "festival",
    name: "Lì xì Tết",
    description: "Cô gái áo dài đỏ tươi cười nhận bao lì xì đỏ, không khí Tết ấm cúng tại nhà",
    descriptionEn: "Young woman in bright red ao dai smiling while receiving red lucky money envelope, warm cozy Tet atmosphere at home",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["festive", "warm", "joyful"],
    emoji: "🧧",
  },
  {
    id: "midautumn_hangma",
    category: "festival",
    name: "Phố Hàng Mã đèn lồng",
    description: "Cô gái áo dài dạo phố Hàng Mã Hà Nội mùa Trung Thu, đèn lồng đủ màu treo dày đặc",
    descriptionEn: "Young woman in ao dai strolling Hang Ma street in Hanoi during Mid-Autumn Festival, colorful lanterns hung densely",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["festive", "vibrant", "traditional"],
    emoji: "🏮",
  },
  {
    id: "midautumn_mooncake_tea",
    category: "festival",
    name: "Bánh trung thu + trà",
    description: "Cô gái ngồi pha trà sen, bên cạnh đĩa bánh trung thu vàng, không khí Trung Thu cổ điển",
    descriptionEn: "Young woman brewing lotus tea beside a plate of golden mooncakes, classic Mid-Autumn Festival atmosphere",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["traditional", "elegant", "cozy"],
    emoji: "🥮",
  },
  {
    id: "vulan_pagoda",
    category: "festival",
    name: "Áo dài lam đi chùa",
    description: "Cô gái mặc áo dài lam tay cầm hoa sen đi lễ chùa cổ vào mùa Vu Lan",
    descriptionEn: "Young woman in light blue ao dai holding lotus flower visiting an ancient pagoda during Vu Lan festival",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["serene", "spiritual", "traditional"],
    emoji: "🪷",
  },
  {
    id: "christmas_notredame",
    category: "festival",
    name: "Giáng sinh Đức Bà",
    description: "Cô gái áo len ấm đứng trước nhà thờ Đức Bà Sài Gòn đêm Giáng Sinh, đèn trang trí lung linh",
    descriptionEn: "Young woman in warm sweater standing before Notre-Dame Cathedral of Saigon on Christmas night, sparkling decorative lights",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["festive", "winter", "warm"],
    emoji: "🎄",
  },
  {
    id: "halloween_buivien",
    category: "festival",
    name: "Halloween Bùi Viện",
    description: "Cô gái mặc costume Halloween dạo phố Tây Bùi Viện đêm Halloween, đèn neon rực rỡ",
    descriptionEn: "Young woman in Halloween costume strolling Bui Vien Western street on Halloween night, vibrant neon lights",
    cameraStyle: "DOCUMENTARY",
    time: "night",
    mood: ["edgy", "vibrant", "urban"],
    emoji: "🎃",
  },

  // ===== 3. LOCATION (địa điểm) =====
  {
    id: "loc_hoankiem",
    category: "location",
    name: "Hồ Hoàn Kiếm",
    description: "Cô gái dạo bộ quanh Hồ Hoàn Kiếm Hà Nội, Tháp Rùa phía sau, sương sớm mùa thu",
    descriptionEn: "Young woman strolling around Hoan Kiem Lake in Hanoi, Turtle Tower in background, autumn morning mist",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["nostalgic", "peaceful", "iconic"],
    emoji: "🏛",
  },
  {
    id: "loc_train_street",
    category: "location",
    name: "Phố đường tàu Hà Nội",
    description: "Cô gái đứng trên đường ray xe lửa cũ phố cổ Hà Nội, dây điện chằng chịt, người dân đời thường",
    descriptionEn: "Young woman standing on old railway tracks in Hanoi old quarter, tangled electrical wires overhead, everyday locals",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["authentic", "vintage", "documentary"],
    emoji: "🚂",
  },
  {
    id: "loc_sapa_terrace",
    category: "location",
    name: "Sapa ruộng bậc thang",
    description: "Cô gái mặc áo dân tộc Mông đứng trên ruộng bậc thang Sapa, núi non hùng vĩ phía sau",
    descriptionEn: "Young Hmong woman standing on Sapa rice terraces, majestic mountains in background",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["authentic", "ethnic", "majestic"],
    emoji: "⛰",
  },
  {
    id: "loc_hagiang_pass",
    category: "location",
    name: "Đèo Mã Pí Lèng",
    description: "Cô gái đứng trên đèo Mã Pí Lèng Hà Giang, sông Nho Quế xanh ngọc bên dưới",
    descriptionEn: "Young woman standing at Ma Pi Leng pass in Ha Giang, emerald Nho Que river flowing below",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["majestic", "adventure", "remote"],
    emoji: "🏔",
  },
  {
    id: "loc_halong",
    category: "location",
    name: "Vịnh Hạ Long",
    description: "Cô gái đứng trên du thuyền nhìn ra vịnh Hạ Long, các đảo đá vôi nổi giữa biển xanh",
    descriptionEn: "Young woman standing on cruise ship looking over Ha Long Bay, limestone karsts rising from emerald waters",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["majestic", "scenic", "iconic"],
    emoji: "🏞",
  },
  {
    id: "loc_ninhbinh",
    category: "location",
    name: "Tam Cốc Ninh Bình",
    description: "Cô gái áo dài lụa ngồi thuyền nhỏ qua Tam Cốc Ninh Bình, núi đá vôi và lúa chín hai bên",
    descriptionEn: "Young woman in silk ao dai sitting on small boat through Tam Coc Ninh Binh, limestone mountains and golden rice on both sides",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["serene", "scenic", "traditional"],
    emoji: "🚣",
  },
  {
    id: "loc_hoian_oldtown",
    category: "location",
    name: "Phố cổ Hội An",
    description: "Cô gái áo dài dạo bộ phố cổ Hội An đêm, đèn lồng đủ màu treo dọc phố, nhà cổ vàng",
    descriptionEn: "Young woman in ao dai strolling Hoi An old town at night, colorful lanterns hanging along streets, ancient yellow houses",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["romantic", "vintage", "magical"],
    emoji: "🏮",
  },
  {
    id: "loc_golden_bridge",
    category: "location",
    name: "Cầu Vàng Đà Nẵng",
    description: "Cô gái đứng trên Cầu Vàng Đà Nẵng, hai bàn tay đá khổng lồ nâng cây cầu vàng, mây phủ phía sau",
    descriptionEn: "Young woman standing on Golden Bridge Da Nang, giant stone hands lifting the golden bridge, clouds in background",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["iconic", "majestic", "tourist"],
    emoji: "🌉",
  },
  {
    id: "loc_hue_imperial",
    category: "location",
    name: "Đại Nội Huế",
    description: "Cô gái áo dài tím Huế đi qua sân Đại Nội cổ kính, kiến trúc cung đình triều Nguyễn",
    descriptionEn: "Young woman in Hue purple ao dai walking through ancient Imperial City courtyard, Nguyen dynasty palace architecture",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["royal", "traditional", "elegant"],
    emoji: "👑",
  },
  {
    id: "loc_huong_river",
    category: "location",
    name: "Sông Hương Huế",
    description: "Cô gái áo dài tím ngồi thuyền rồng trên sông Hương Huế, hoàng hôn tím nhẹ",
    descriptionEn: "Young woman in purple ao dai sitting on dragon boat on Perfume River in Hue, soft purple sunset",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["romantic", "traditional", "cinematic"],
    emoji: "🛶",
  },
  {
    id: "loc_notredame_saigon",
    category: "location",
    name: "Nhà thờ Đức Bà Sài Gòn",
    description: "Cô gái áo dài trắng đứng trước nhà thờ Đức Bà Sài Gòn vào hoàng hôn, tà áo bay nhẹ",
    descriptionEn: "Young woman in white ao dai before Notre-Dame Cathedral of Saigon at golden hour, ao dai panels softly flowing",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["romantic", "iconic", "elegant"],
    emoji: "⛪",
  },
  {
    id: "loc_post_office",
    category: "location",
    name: "Bưu điện Sài Gòn",
    description: "Cô gái áo trắng đứng trong sảnh Bưu điện Trung tâm Sài Gòn cổ kính, bản đồ và kiến trúc Pháp",
    descriptionEn: "Young woman in white blouse standing inside historic Saigon Central Post Office hall, French colonial architecture and old maps",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["vintage", "iconic", "elegant"],
    emoji: "🏛",
  },
  {
    id: "loc_nguyen_hue_walk",
    category: "location",
    name: "Phố đi bộ Nguyễn Huệ",
    description: "Cô gái dạo phố đi bộ Nguyễn Huệ Sài Gòn buổi tối, tòa Bitexco và đèn neon rực rỡ",
    descriptionEn: "Young woman strolling Nguyen Hue walking street in Saigon at night, Bitexco tower and vibrant neon lights",
    cameraStyle: "DOCUMENTARY",
    time: "night",
    mood: ["urban", "vibrant", "modern"],
    emoji: "🌃",
  },
  {
    id: "loc_landmark81",
    category: "location",
    name: "Landmark 81",
    description: "Cô gái mặc đầm đen đứng trong căn hộ cao tầng nhìn ra tòa Landmark 81 Sài Gòn ban đêm",
    descriptionEn: "Young woman in black dress standing in high-rise apartment with view of Landmark 81 Saigon at night",
    cameraStyle: "DOCUMENTARY",
    time: "night",
    mood: ["luxe", "modern", "moody"],
    emoji: "🏙",
  },
  {
    id: "loc_phuquoc_island",
    category: "location",
    name: "Phú Quốc",
    description: "Cô gái áo tắm trắng đi trên cầu gỗ ra biển Phú Quốc, nước biển xanh ngọc trong veo",
    descriptionEn: "Young woman in white swimsuit walking along wooden pier into Phu Quoc sea, crystal-clear emerald water",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["tropical", "luxe", "summer"],
    emoji: "🏝",
  },
  {
    id: "loc_caoring_market",
    category: "location",
    name: "Chợ nổi Cái Răng",
    description: "Cô gái áo bà ba đứng trên thuyền tại chợ nổi Cái Răng Cần Thơ, các thuyền bán trái cây xung quanh",
    descriptionEn: "Young woman in ao ba ba standing on boat at Cai Rang floating market in Can Tho, fruit-selling boats around",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["authentic", "rural", "lively"],
    emoji: "⛵",
  },
  {
    id: "loc_dalat_hill",
    category: "location",
    name: "Đồi chè Cầu Đất Đà Lạt",
    description: "Cô gái áo trắng đứng giữa đồi chè xanh ngút ngàn ở Cầu Đất Đà Lạt, sương sớm",
    descriptionEn: "Young woman in white standing among endless green tea hills at Cau Dat Da Lat, early morning mist",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["serene", "rural", "fresh"],
    emoji: "🍃",
  },
  {
    id: "loc_mocchau_canola",
    category: "location",
    name: "Mộc Châu đồi cải",
    description: "Cô gái dân tộc đi giữa đồi hoa cải vàng rực ở Mộc Châu Sơn La",
    descriptionEn: "Young ethnic woman walking through bright yellow canola flower hills in Moc Chau Son La",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["rural", "vibrant", "fresh"],
    emoji: "🌼",
  },

  // ===== 4. OUTFIT (trang phục) =====
  {
    id: "outfit_aodai_white",
    category: "outfit",
    name: "Áo dài trắng nữ sinh",
    description: "Cô gái nữ sinh mặc áo dài trắng tinh khôi, cặp sách trên tay, đứng giữa sân trường có cây phượng",
    descriptionEn: "Young schoolgirl in pristine white ao dai with school bag, standing in schoolyard with phoenix tree",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["youthful", "innocent", "traditional"],
    emoji: "👩‍🎓",
  },
  {
    id: "outfit_aodai_wedding",
    category: "outfit",
    name: "Áo dài cưới đỏ",
    description: "Cô dâu mặc áo dài cưới đỏ thêu rồng phụng vàng, cài hoa cài đầu, không khí lễ cưới truyền thống",
    descriptionEn: "Bride in red traditional wedding ao dai with gold dragon and phoenix embroidery, hair ornament, traditional wedding atmosphere",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["traditional", "festive", "elegant"],
    emoji: "👰",
  },
  {
    id: "outfit_aodai_modern",
    category: "outfit",
    name: "Áo dài cách tân",
    description: "Cô gái mặc áo dài cách tân ngắn với quần culottes, phong cách hiện đại trẻ trung",
    descriptionEn: "Young woman in modern shortened ao dai paired with culottes, youthful contemporary style",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["modern", "chic", "youthful"],
    emoji: "👗",
  },
  {
    id: "outfit_ao_ba_ba",
    category: "outfit",
    name: "Áo bà ba miền Tây",
    description: "Cô gái mặc áo bà ba đen quần đen ngồi trên cầu khỉ ở miệt vườn miền Tây Nam Bộ",
    descriptionEn: "Young woman in black ao ba ba and black trousers sitting on monkey bridge in Mekong Delta orchard",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["rural", "traditional", "authentic"],
    emoji: "🌾",
  },
  {
    id: "outfit_ao_tu_than",
    category: "outfit",
    name: "Áo tứ thân miền Bắc",
    description: "Cô gái mặc áo tứ thân truyền thống Bắc Bộ với khăn mỏ quạ và yếm, tại làng cổ Đường Lâm",
    descriptionEn: "Young woman in traditional Northern four-panel dress with crow-bill headscarf and yem bib, at Duong Lam ancient village",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["traditional", "vintage", "rural"],
    emoji: "🎎",
  },
  {
    id: "outfit_yem_quanho",
    category: "outfit",
    name: "Yếm đào Quan Họ",
    description: "Cô gái Quan Họ Bắc Ninh mặc áo tứ thân và yếm đào, nón quai thao, hát đối đáp bên hồ sen",
    descriptionEn: "Young Quan Ho Bac Ninh singer in four-panel dress with peach yem and quai thao hat, performing duet by lotus pond",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["traditional", "cultural", "elegant"],
    emoji: "🎶",
  },
  {
    id: "outfit_hmong",
    category: "outfit",
    name: "Trang phục dân tộc Mông",
    description: "Cô gái dân tộc Mông mặc trang phục truyền thống thêu hoa văn rực rỡ, đứng trên ruộng bậc thang",
    descriptionEn: "Young Hmong ethnic woman in traditional embroidered colorful costume, standing on rice terraces",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["ethnic", "vibrant", "authentic"],
    emoji: "🪡",
  },
  {
    id: "outfit_red_dao",
    category: "outfit",
    name: "Trang phục Dao Đỏ",
    description: "Cô gái dân tộc Dao Đỏ mặc trang phục đỏ thêu cầu kỳ với khăn đội đầu đỏ tại Sapa",
    descriptionEn: "Young Red Dao ethnic woman in elaborate red embroidered costume with red headdress at Sapa",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["ethnic", "majestic", "traditional"],
    emoji: "🧣",
  },

  // ===== 5. LIFESTYLE (đời sống) =====
  {
    id: "life_cafe_vintage_saigon",
    category: "lifestyle",
    name: "Cafe vintage Sài Gòn",
    description: "Cô gái ngồi trong quán cafe phong cách vintage Sài Gòn, cốc cà phê sữa đá, ánh sáng tự nhiên qua cửa sổ",
    descriptionEn: "Young woman sitting in vintage Saigon-style cafe with iced milk coffee, natural light through window",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["vintage", "cozy", "lifestyle"],
    emoji: "☕",
  },
  {
    id: "life_cafe_korean",
    category: "lifestyle",
    name: "Cafe Hàn Quốc minimalist",
    description: "Cô gái ngồi trong quán cafe phong cách Hàn Quốc minimalist, cây xanh và đồ gỗ, ánh sáng tự nhiên",
    descriptionEn: "Young woman in Korean-style minimalist cafe with greenery and wooden furniture, natural light",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["aesthetic", "cozy", "minimalist"],
    emoji: "🍵",
  },
  {
    id: "life_cafe_rooftop",
    category: "lifestyle",
    name: "Cafe sân thượng",
    description: "Cô gái ngồi cafe trên sân thượng nhìn xuống đường phố Sài Gòn, tòa nhà cao tầng phía xa",
    descriptionEn: "Young woman at rooftop cafe overlooking Saigon streets, high-rise buildings in distance",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["urban", "modern", "relaxed"],
    emoji: "🌆",
  },
  {
    id: "life_pho_street",
    category: "lifestyle",
    name: "Phở vỉa hè Hà Nội",
    description: "Cô gái ngồi ăn phở ở quán vỉa hè phố cổ Hà Nội, biển hiệu đỏ ghi 'Phở Hà Nội', ghế nhựa thấp",
    descriptionEn: "Young woman eating pho at Hanoi old quarter sidewalk stall, red 'Pho Hanoi' signboard, low plastic stools",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["authentic", "local", "documentary"],
    emoji: "🍜",
  },
  {
    id: "life_bun_bo",
    category: "lifestyle",
    name: "Bún bò gánh",
    description: "Cô gái ngồi ăn bún bò Huế ở gánh hàng rong vỉa hè, không khí ẩm thực đường phố Việt",
    descriptionEn: "Young woman eating bun bo Hue at street vendor cart, Vietnamese street food atmosphere",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["authentic", "local", "warm"],
    emoji: "🥢",
  },
  {
    id: "life_banh_mi",
    category: "lifestyle",
    name: "Bánh mì sáng",
    description: "Cô gái cầm ổ bánh mì thịt tươi ngon trên tay, đứng trước xe bánh mì Sài Gòn buổi sáng",
    descriptionEn: "Young woman holding fresh banh mi sandwich, standing before Saigon banh mi cart in morning",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["authentic", "local", "fresh"],
    emoji: "🥖",
  },
  {
    id: "life_milk_tea",
    category: "lifestyle",
    name: "Trà sữa hot trend",
    description: "Cô gái cầm ly trà sữa trân châu đứng trước quán trà sữa hot trend Sài Gòn, decoration đẹp mắt",
    descriptionEn: "Young woman holding bubble milk tea cup standing before trendy Saigon milk tea shop, aesthetic decor",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["trendy", "youthful", "lifestyle"],
    emoji: "🧋",
  },
  {
    id: "life_ben_thanh",
    category: "lifestyle",
    name: "Chợ Bến Thành",
    description: "Cô gái áo dài đi mua sắm tại chợ Bến Thành Sài Gòn, sạp hàng đa dạng phía sau",
    descriptionEn: "Young woman in ao dai shopping at Ben Thanh market in Saigon, diverse stalls in background",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["local", "lively", "iconic"],
    emoji: "🛍",
  },
  {
    id: "life_dongxuan",
    category: "lifestyle",
    name: "Chợ Đồng Xuân",
    description: "Cô gái dạo chợ Đồng Xuân Hà Nội, không khí buôn bán nhộn nhịp, hàng hóa đủ loại",
    descriptionEn: "Young woman walking through Dong Xuan market in Hanoi, bustling trade atmosphere, diverse goods",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["lively", "authentic", "local"],
    emoji: "🏪",
  },
  {
    id: "life_office_modern",
    category: "lifestyle",
    name: "Văn phòng IT modern",
    description: "Cô gái mặc áo sơ mi trắng làm việc tại văn phòng IT modern, laptop, cây xanh, ánh sáng tự nhiên",
    descriptionEn: "Young woman in white blouse working at modern IT office, laptop, greenery, natural light",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["professional", "modern", "clean"],
    emoji: "💻",
  },
  {
    id: "life_coworking",
    category: "lifestyle",
    name: "Co-working space",
    description: "Cô gái làm việc tại co-working space hiện đại với laptop, cốc cà phê, không gian mở thân thiện",
    descriptionEn: "Young woman working at modern co-working space with laptop, coffee cup, friendly open space",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["modern", "productive", "casual"],
    emoji: "🖥",
  },

  // ===== 6. TRAVEL =====
  {
    id: "travel_resort",
    category: "travel",
    name: "Resort sang trọng",
    description: "Cô gái mặc áo tắm đứng cạnh hồ bơi vô cực resort sang trọng, biển xanh phía xa",
    descriptionEn: "Young woman in swimsuit by infinity pool of luxury resort, blue sea in distance",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["luxe", "relaxed", "tropical"],
    emoji: "🏖",
  },
  {
    id: "travel_seaview_room",
    category: "travel",
    name: "Phòng khách sạn view biển",
    description: "Cô gái ngồi trên giường phòng khách sạn nhìn ra view biển qua cửa sổ lớn, ánh sáng buổi sáng",
    descriptionEn: "Young woman on hotel bed with view of sea through large window, morning light",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["luxe", "peaceful", "fresh"],
    emoji: "🛏",
  },
  {
    id: "travel_vnairlines_cabin",
    category: "travel",
    name: "Cabin Vietnam Airlines",
    description: "Cô gái ngồi ghế hạng thương gia Vietnam Airlines, ghế xanh đỏ logo VN, cửa sổ máy bay phía sau",
    descriptionEn: "Young woman in Vietnam Airlines business class seat, blue and red VN-logo seats, airplane window behind",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["luxe", "modern", "travel"],
    emoji: "✈️",
  },
  {
    id: "travel_airport",
    category: "travel",
    name: "Sân bay Tân Sơn Nhất",
    description: "Cô gái kéo vali đi qua sảnh sân bay Tân Sơn Nhất hiện đại, biển chỉ dẫn và máy bay phía xa",
    descriptionEn: "Young woman pulling suitcase through modern Tan Son Nhat airport hall, signage and aircraft visible",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["travel", "modern", "movement"],
    emoji: "🛄",
  },
  {
    id: "travel_halong_cruise",
    category: "travel",
    name: "Du thuyền Hạ Long",
    description: "Cô gái đứng trên du thuyền 5 sao vịnh Hạ Long, các đảo đá vôi hùng vĩ phía sau",
    descriptionEn: "Young woman on 5-star cruise ship in Ha Long Bay, majestic limestone karsts in background",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["luxe", "scenic", "adventure"],
    emoji: "🛳",
  },

  // ===== 7. SPORT =====
  {
    id: "sport_pickleball",
    category: "sport",
    name: "Pickleball indoor",
    description: "Cô gái mặc đồ thể thao chơi pickleball trong sân nhà thi đấu, vợt trong tay, ánh sáng đèn nhà thi đấu",
    descriptionEn: "Young woman in sportswear playing pickleball in indoor arena, paddle in hand, fluorescent arena lighting",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["athletic", "energetic", "competitive"],
    emoji: "🏓",
  },
  {
    id: "sport_tennis",
    category: "sport",
    name: "Tennis sân đất nện",
    description: "Cô gái cầm vợt tennis chuẩn bị đánh trên sân đất nện màu cam, áo skort tennis trắng",
    descriptionEn: "Young woman holding tennis racket preparing to swing on orange clay court, white tennis skort outfit",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["athletic", "energetic", "sporty"],
    emoji: "🎾",
  },
  {
    id: "sport_volleyball_beach",
    category: "sport",
    name: "Bóng chuyền bãi biển",
    description: "Cô gái mặc bikini chơi bóng chuyền bãi biển Phú Quốc, lưới và bóng chuyền vàng",
    descriptionEn: "Young woman in bikini playing beach volleyball in Phu Quoc, net and yellow volleyball visible",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["athletic", "summer", "energetic"],
    emoji: "🏐",
  },
  {
    id: "sport_yoga_rooftop",
    category: "sport",
    name: "Yoga sân thượng",
    description: "Cô gái tập yoga động tác chiến binh trên sân thượng buổi sáng, view thành phố phía sau",
    descriptionEn: "Young woman in warrior yoga pose on rooftop in morning, city view in background",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["zen", "fresh", "morning"],
    emoji: "🧘",
  },
  {
    id: "sport_gym",
    category: "sport",
    name: "Gym workout",
    description: "Cô gái mặc đồ gym tập tạ trong phòng gym hiện đại, gương lớn, máy tập đầy đủ",
    descriptionEn: "Young woman in gym attire lifting weights in modern gym, large mirrors, full equipment",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["athletic", "strong", "fit"],
    emoji: "🏋️‍♀️",
  },
  {
    id: "sport_boxing",
    category: "sport",
    name: "Boxing / Muay Thai",
    description: "Cô gái mặc set boxing hồng đeo găng tay đứng tạo dáng trước bao cát, không khí phòng tập võ",
    descriptionEn: "Young woman in pink boxing set with gloves posing before punching bag, martial arts gym atmosphere",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["strong", "edgy", "athletic"],
    emoji: "🥊",
  },
  {
    id: "sport_cycling",
    category: "sport",
    name: "Đua xe đạp",
    description: "Cô gái đạp xe thể thao trên đường biển Đà Nẵng, áo cycling và mũ bảo hiểm",
    descriptionEn: "Young woman cycling sports bike along Da Nang seaside road, cycling jersey and helmet",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["energetic", "outdoor", "free"],
    emoji: "🚴",
  },
  {
    id: "sport_trekking",
    category: "sport",
    name: "Trekking leo núi",
    description: "Cô gái balo trekking đứng trên đỉnh núi Fansipan, mây phủ phía dưới, không khí chinh phục",
    descriptionEn: "Young woman with trekking backpack on top of Fansipan mountain, clouds below, conquering atmosphere",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["adventure", "majestic", "free"],
    emoji: "🥾",
  },

  // ===== 8. CAREER =====
  {
    id: "career_business",
    category: "career",
    name: "Nữ doanh nhân office",
    description: "Cô gái mặc blazer đen ngồi ở phòng họp công ty, laptop và slide trình chiếu phía sau",
    descriptionEn: "Young woman in black blazer in corporate meeting room, laptop and presentation slides behind",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["professional", "confident", "modern"],
    emoji: "💼",
  },
  {
    id: "career_doctor",
    category: "career",
    name: "Bác sĩ áo trắng",
    description: "Cô gái bác sĩ mặc áo blouse trắng, ống nghe đeo cổ, đứng tại hành lang bệnh viện hiện đại",
    descriptionEn: "Young woman doctor in white coat with stethoscope, standing in modern hospital corridor",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["professional", "caring", "clean"],
    emoji: "👩‍⚕️",
  },
  {
    id: "career_teacher",
    category: "career",
    name: "Giáo viên đứng lớp",
    description: "Cô gái giáo viên mặc áo dài đứng trước bảng đen viết phấn, học sinh ngồi phía dưới",
    descriptionEn: "Young woman teacher in ao dai standing before blackboard with chalk, students seated below",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["traditional", "educational", "warm"],
    emoji: "👩‍🏫",
  },
  {
    id: "career_flight_attendant",
    category: "career",
    name: "Tiếp viên hàng không",
    description: "Cô gái tiếp viên hàng không Vietnam Airlines mặc áo dài đỏ chuyên nghiệp, đứng trong cabin",
    descriptionEn: "Young Vietnam Airlines flight attendant in professional red ao dai uniform, standing in cabin",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["professional", "elegant", "iconic"],
    emoji: "💂",
  },
  {
    id: "career_barista",
    category: "career",
    name: "Barista pha chế",
    description: "Cô gái barista pha cà phê espresso tại quán cafe, máy pha cà phê chuyên nghiệp, tạp dề đen",
    descriptionEn: "Young woman barista brewing espresso at cafe, professional espresso machine, black apron",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["focused", "craft", "warm"],
    emoji: "☕",
  },
  {
    id: "career_livestream",
    category: "career",
    name: "Influencer livestream",
    description: "Cô gái influencer ngồi livestream tại bàn trang điểm có ringlight, sản phẩm review xung quanh",
    descriptionEn: "Young woman influencer livestreaming at vanity with ring light, products to review around",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["modern", "trendy", "tech"],
    emoji: "📱",
  },
  {
    id: "career_photographer",
    category: "career",
    name: "Photographer cầm máy",
    description: "Cô gái photographer cầm máy ảnh DSLR đeo cổ, đang chụp ảnh trên đường phố Sài Gòn",
    descriptionEn: "Young woman photographer with DSLR camera around neck, shooting photos on Saigon streets",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["creative", "candid", "urban"],
    emoji: "📷",
  },

  // ===== 9. TIME =====
  {
    id: "time_sunrise_beach",
    category: "time",
    name: "Bình minh trên biển",
    description: "Cô gái áo trắng đứng trên bãi biển đón bình minh, mặt trời đang mọc đỏ rực phía chân trời",
    descriptionEn: "Young woman in white standing on beach welcoming sunrise, fiery red sun rising on horizon",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["serene", "fresh", "magical"],
    emoji: "🌅",
  },
  {
    id: "time_golden_hour_field",
    category: "time",
    name: "Hoàng hôn cánh đồng",
    description: "Cô gái dạo bộ trên cánh đồng cỏ vào hoàng hôn vàng cam, ánh nắng xuyên qua tóc",
    descriptionEn: "Young woman strolling grass field at golden hour, sunlight piercing through hair",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["dreamy", "warm", "cinematic"],
    emoji: "🌄",
  },
  {
    id: "time_blue_hour",
    category: "time",
    name: "Chạng vạng Blue Hour",
    description: "Cô gái đứng trên cầu vào chạng vạng, bầu trời xanh tím nhạt, đèn đường vừa lên",
    descriptionEn: "Young woman on bridge during blue hour twilight, soft purple-blue sky, streetlights just on",
    cameraStyle: "BOKEH",
    time: "blue_hour",
    mood: ["melancholic", "moody", "cinematic"],
    emoji: "🌆",
  },
  {
    id: "time_neon_night",
    category: "time",
    name: "Đêm phố thị neon",
    description: "Cô gái đứng giữa phố Sài Gòn đêm, đèn neon đủ màu xanh hồng tím phản chiếu trên đường ướt",
    descriptionEn: "Young woman in Saigon street at night, vibrant pink-purple-blue neon lights reflecting on wet street",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["edgy", "moody", "urban"],
    emoji: "🌃",
  },
  {
    id: "time_misty_dawn",
    category: "time",
    name: "Rạng sáng sương mù",
    description: "Cô gái áo len đi qua rừng thông Đà Lạt rạng sáng sương mù dày đặc, ánh sáng vàng nhạt xuyên qua sương",
    descriptionEn: "Young woman in wool sweater walking through Da Lat pine forest at misty dawn, soft yellow light through fog",
    cameraStyle: "BOKEH",
    time: "overcast",
    mood: ["mystical", "fresh", "ethereal"],
    emoji: "🌫",
  },
  {
    id: "time_full_moon",
    category: "time",
    name: "Đêm trăng rằm",
    description: "Cô gái áo dài trắng ngồi bên hồ sen vào đêm trăng rằm, ánh trăng vàng phản chiếu mặt nước",
    descriptionEn: "Young woman in white ao dai by lotus pond on full moon night, golden moonlight reflecting on water",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["serene", "magical", "traditional"],
    emoji: "🌕",
  },

  // ===== 10. CINEMA =====
  {
    id: "cinema_hk_noir",
    category: "cinema",
    name: "Hong Kong noir 90s",
    description: "Cô gái mặc đầm đỏ ngồi quán mì cổ phong cách Hong Kong noir thập niên 90, đèn neon đỏ vàng",
    descriptionEn: "Young woman in red dress at vintage noodle shop, Hong Kong 90s noir style, red and yellow neon",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["noir", "vintage", "cinematic"],
    emoji: "🎞",
  },
  {
    id: "cinema_wong_kar_wai",
    category: "cinema",
    name: "Wong Kar Wai vintage",
    description: "Cô gái áo dài lụa đứng trong hành lang chật hẹp, ánh đèn vàng mờ ảo, phong cách Wong Kar Wai",
    descriptionEn: "Young woman in silk ao dai in narrow hallway, dim yellow lighting, Wong Kar Wai style",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["nostalgic", "romantic", "cinematic"],
    emoji: "🎬",
  },
  {
    id: "cinema_ghibli",
    category: "cinema",
    name: "Studio Ghibli dreamy",
    description: "Cô gái áo trắng đi giữa cánh đồng cỏ xanh ngút ngàn dưới bầu trời mây trắng phong cách Ghibli",
    descriptionEn: "Young woman in white walking through endless green grass field under fluffy white cloud sky, Ghibli style",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["dreamy", "fresh", "magical"],
    emoji: "🌳",
  },
  {
    id: "cinema_kdrama_cafe",
    category: "cinema",
    name: "K-drama cafe",
    description: "Cô gái mặc áo len pastel ngồi cafe Hàn Quốc đọc sách bên cửa sổ, không khí K-drama lãng mạn",
    descriptionEn: "Young woman in pastel sweater reading book at Korean cafe by window, romantic K-drama atmosphere",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["romantic", "cozy", "kdrama"],
    emoji: "📖",
  },
  {
    id: "cinema_y2k",
    category: "cinema",
    name: "Y2K early 2000s",
    description: "Cô gái mặc đồ Y2K low-rise jeans với crop top, makeup glittery, phong cách đầu năm 2000",
    descriptionEn: "Young woman in Y2K low-rise jeans and crop top, glittery makeup, early 2000s style",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["nostalgic", "playful", "retro"],
    emoji: "💿",
  },
  {
    id: "cinema_film_grain",
    category: "cinema",
    name: "Vintage film grain",
    description: "Cô gái mặc đầm vintage 70s phong cách film grain rõ rệt, tone màu hơi ngả vàng nâu",
    descriptionEn: "Young woman in vintage 70s dress with prominent film grain texture, warm yellow-brown color tone",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["vintage", "nostalgic", "warm"],
    emoji: "📽",
  },

  // ===== 11. VEHICLE =====
  {
    id: "vehicle_honda_vision",
    category: "vehicle",
    name: "Honda Vision",
    description: "Cô gái đeo nón bảo hiểm trắng đứng cạnh Honda Vision 2026 màu titanium silver trên đường nhựa",
    descriptionEn: "Young woman with white half-face helmet beside Honda Vision 2026 in titanium silver on asphalt road",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["youthful", "free", "lifestyle"],
    emoji: "🛵",
  },
  {
    id: "vehicle_vespa_vintage",
    category: "vehicle",
    name: "Vespa vintage",
    description: "Cô gái áo dài cách tân ngồi trên Vespa vintage màu pastel, phố cổ Sài Gòn",
    descriptionEn: "Young woman in modern ao dai on vintage pastel Vespa, Saigon old streets",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["vintage", "chic", "iconic"],
    emoji: "🛵",
  },
  {
    id: "vehicle_bicycle_hoian",
    category: "vehicle",
    name: "Xe đạp Hội An",
    description: "Cô gái áo dài tím đạp xe đạp cổ kem trên phố cổ Hội An, hoa giấy nở rộ bên đường",
    descriptionEn: "Young woman in purple ao dai cycling cream-colored vintage bicycle through Hoi An old streets, bougainvillea blooming",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["romantic", "vintage", "free"],
    emoji: "🚲",
  },
  {
    id: "vehicle_train",
    category: "vehicle",
    name: "Tàu hỏa Bắc Nam",
    description: "Cô gái balo lưng ngồi cửa sổ tàu hỏa Bắc Nam nhìn cảnh đồng quê Việt Nam vụt qua",
    descriptionEn: "Young woman with backpack at North-South train window watching Vietnamese countryside whizz past",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["wanderlust", "nostalgic", "authentic"],
    emoji: "🚂",
  },
  {
    id: "vehicle_xich_lo",
    category: "vehicle",
    name: "Xích lô Sài Gòn",
    description: "Cô gái áo dài ngồi xích lô qua phố cổ Sài Gòn, bác xích lô đạp phía sau",
    descriptionEn: "Young woman in ao dai sitting on xich lo (cyclo) through old Saigon streets, driver pedaling behind",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["traditional", "nostalgic", "iconic"],
    emoji: "🚲",
  },
  {
    id: "vehicle_huong_boat",
    category: "vehicle",
    name: "Thuyền sông Hương",
    description: "Cô gái áo dài tím Huế ngồi thuyền rồng thả lưới trên sông Hương lúc hoàng hôn",
    descriptionEn: "Young woman in Hue purple ao dai on dragon boat on Perfume River at sunset",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["traditional", "romantic", "scenic"],
    emoji: "⛵",
  },

  // ===== 12. STYLE =====
  {
    id: "style_y2k",
    category: "style",
    name: "Y2K nostalgic",
    description: "Cô gái phong cách Y2K với crop top, mini skirt denim, kính nhỏ tinted, phụ kiện cyber",
    descriptionEn: "Young woman in Y2K style with crop top, denim mini skirt, small tinted glasses, cyber accessories",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["nostalgic", "playful", "retro"],
    emoji: "💿",
  },
  {
    id: "style_cottagecore",
    category: "style",
    name: "Cottagecore đồng quê",
    description: "Cô gái mặc đầm hoa nhí trắng dạo trong vườn hoa, giỏ rơm tay cầm, phong cách cottagecore",
    descriptionEn: "Young woman in white floral dress walking through flower garden, straw basket in hand, cottagecore style",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["dreamy", "rural", "wholesome"],
    emoji: "🌼",
  },
  {
    id: "style_old_money",
    category: "style",
    name: "Old money quiet luxury",
    description: "Cô gái mặc áo polo trắng quần khaki phong cách old money quiet luxury, đứng tại biệt thự sang trọng",
    descriptionEn: "Young woman in white polo and khaki pants in old money quiet luxury style, standing at upscale villa",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["luxe", "elegant", "minimalist"],
    emoji: "🏛",
  },
  {
    id: "style_dark_academia",
    category: "style",
    name: "Dark academia",
    description: "Cô gái mặc áo blazer nâu áo sơ mi cổ trắng trong thư viện đại học cổ kính, sách dày phía sau",
    descriptionEn: "Young woman in brown blazer and white-collared shirt in ancient university library, thick books behind",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["scholarly", "moody", "vintage"],
    emoji: "📚",
  },
  {
    id: "style_streetwear",
    category: "style",
    name: "Streetwear Sài Gòn",
    description: "Cô gái mặc oversized hoodie và baggy jeans phong cách streetwear, đứng tại phố vẽ graffiti",
    descriptionEn: "Young woman in oversized hoodie and baggy jeans, streetwear style, standing at graffiti street",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["edgy", "urban", "youthful"],
    emoji: "🛹",
  },
  {
    id: "style_minimalist_korean",
    category: "style",
    name: "Minimalist Hàn Quốc",
    description: "Cô gái mặc áo len trắng và quần kaki phong cách minimalist Hàn Quốc trong studio sạch trắng",
    descriptionEn: "Young woman in white knit sweater and khaki pants in Korean minimalist style in clean white studio",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["clean", "minimalist", "soft"],
    emoji: "🤍",
  },
  {
    id: "style_bohemian",
    category: "style",
    name: "Bohemian phóng khoáng",
    description: "Cô gái mặc đầm maxi hoa, vòng cổ và kính tròn phong cách bohemian, dạo trên bãi biển hoàng hôn",
    descriptionEn: "Young woman in maxi floral dress, layered necklaces and round sunglasses, bohemian style, on beach at sunset",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["free", "warm", "wanderlust"],
    emoji: "🌻",
  },
];


// ============================================================================
// MERGED THEMES (v0.5: 119 base + 108 additional + 200+ industry = 427+ total)
// ============================================================================

import { INDUSTRY_THEMES } from "./themes_industry";

/**
 * Auto-tag legacy themes (BASE + ADDITIONAL) with industry="travel" mode="lifestyle"
 * if they don't already have these fields. This ensures backward compat —
 * old themes still work and become part of "Travel/Lifestyle" industry.
 */
function autoTagLegacy(themes: ThemePreset[]): ThemePreset[] {
  return themes.map((t) => ({
    ...t,
    industry: t.industry || "travel",
    mode: t.mode || "lifestyle",
  }));
}

const LEGACY_THEMES = autoTagLegacy([...BASE_THEMES, ...ADDITIONAL_THEMES]);

export const THEMES: ThemePreset[] = [...LEGACY_THEMES, ...INDUSTRY_THEMES];

// ============================================================================
// HELPERS
// ============================================================================

export function getThemesByCategory(categoryId: string): ThemePreset[] {
  return THEMES.filter((t) => t.category === categoryId);
}

export function searchThemes(query: string): ThemePreset[] {
  const q = query.toLowerCase().trim();
  if (!q) return THEMES;
  return THEMES.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.descriptionEn.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q)
  );
}

export function getThemeById(id: string): ThemePreset | undefined {
  return THEMES.find((t) => t.id === id);
}
