/**
 * Additional themes for v0.4 — ~100 new themes covering:
 * - More VN locations (North/Central/South)
 * - Everyday VN scenes (drinking, sports, transport, weddings, malls)
 * - Countryside scenes (rowing boat, coconut, rice harvest)
 * - More festivals, lifestyle, vehicles
 *
 * Total when merged with existing: ~219 themes
 */

import type { ThemePreset } from "./themes";

export const ADDITIONAL_THEMES: ThemePreset[] = [
  // ============================================================================
  // ===== SEASON (5 more) =====
  // ============================================================================
  {
    id: "spring_dragon_fruit",
    category: "season",
    name: "Vườn thanh long Bình Thuận",
    description: "Cô gái dạo trong vườn thanh long Bình Thuận đang ra hoa trắng vào mùa xuân, hàng cọc bê tông và đèn led đêm",
    descriptionEn: "Young woman walking through a dragon fruit orchard in Binh Thuan during spring flowering season, concrete posts and LED night lights",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["serene", "rural", "tropical"],
    emoji: "🐉",
  },
  {
    id: "summer_phuyen_field",
    category: "season",
    name: "Cánh đồng lúa Tuy Hòa Phú Yên",
    description: "Cô gái áo bà ba đứng giữa cánh đồng lúa chín vàng ở Tuy Hòa Phú Yên, mặt trời lặn đỏ rực phía xa",
    descriptionEn: "Young woman in ao ba ba standing in a golden ripe rice field in Tuy Hoa Phu Yen, fiery red sunset in distance",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["rural", "warm", "nostalgic"],
    emoji: "🌾",
  },
  {
    id: "autumn_lotus_pond",
    category: "season",
    name: "Hồ sen Tây Hồ mùa thu",
    description: "Cô gái áo dài trắng ngồi bên hồ sen Tây Hồ Hà Nội mùa thu sen tàn, lá vàng rơi",
    descriptionEn: "Young woman in white ao dai by West Lake's lotus pond in Hanoi during autumn, withered lotus and falling yellow leaves",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["melancholic", "serene", "vintage"],
    emoji: "🍂",
  },
  {
    id: "winter_haiphong_phoenix",
    category: "season",
    name: "Phố phượng đỏ Hải Phòng",
    description: "Cô gái áo trắng đi dưới hàng phượng đỏ rực đặc trưng phố Hải Phòng vào mùa hè",
    descriptionEn: "Young woman in white walking under iconic red phoenix flower-lined streets of Hai Phong in summer",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["nostalgic", "warm", "iconic"],
    emoji: "🌺",
  },
  {
    id: "autumn_sunflower_nghean",
    category: "season",
    name: "Cánh đồng hướng dương Nghệ An",
    description: "Cô gái dạo giữa cánh đồng hoa hướng dương vàng rực ở Nghĩa Đàn Nghệ An, bầu trời xanh trong",
    descriptionEn: "Young woman walking through a vast yellow sunflower field at Nghia Dan Nghe An, clear blue sky",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["bright", "happy", "warm"],
    emoji: "🌻",
  },

  // ============================================================================
  // ===== FESTIVAL (8 more) =====
  // ============================================================================
  {
    id: "tet_xin_chu",
    category: "festival",
    name: "Xin chữ ông đồ Tết",
    description: "Cô gái áo dài đỏ ngồi xin chữ ông đồ trên phố Văn Miếu Hà Nội ngày Tết, giấy đỏ mực Tàu",
    descriptionEn: "Young woman in red ao dai sitting before a calligrapher receiving lucky calligraphy at Van Mieu street Hanoi during Tet, red paper and Chinese ink",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["traditional", "scholarly", "festive"],
    emoji: "🖌",
  },
  {
    id: "tet_southern_market",
    category: "festival",
    name: "Chợ hoa Tết Sài Gòn",
    description: "Cô gái áo dài đỏ đi chợ hoa Tết Bến Bình Đông Sài Gòn, thuyền chở mai vàng tấp nập",
    descriptionEn: "Young woman in red ao dai at Ben Binh Dong Tet flower market in Saigon, boats laden with yellow apricot blossoms",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["festive", "lively", "southern"],
    emoji: "⛵",
  },
  {
    id: "festival_chua_huong",
    category: "festival",
    name: "Lễ hội chùa Hương",
    description: "Cô gái áo dài lam đi đò trên suối Yến đến chùa Hương dịp lễ hội đầu xuân",
    descriptionEn: "Young woman in light blue ao dai on a small boat along Yen Stream to Huong Pagoda during spring festival",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["spiritual", "serene", "traditional"],
    emoji: "🛶",
  },
  {
    id: "festival_yen_tu",
    category: "festival",
    name: "Hành hương Yên Tử",
    description: "Cô gái áo dài lam leo bậc đá đến chùa Đồng Yên Tử trong sương mây mùa xuân",
    descriptionEn: "Young woman in light blue ao dai climbing stone steps to Dong Pagoda atop Yen Tu mountain through spring mist",
    cameraStyle: "DOCUMENTARY",
    time: "overcast",
    mood: ["spiritual", "mystical", "majestic"],
    emoji: "⛩",
  },
  {
    id: "festival_quan_ho",
    category: "festival",
    name: "Hội Lim Quan Họ",
    description: "Cô gái Bắc Ninh mặc áo tứ thân hát Quan Họ tại hội Lim, nón quai thao và đôi liền anh liền chị",
    descriptionEn: "Bac Ninh woman in four-panel dress singing Quan Ho at Lim Festival, with quai thao hat and traditional folk performance",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["traditional", "cultural", "festive"],
    emoji: "🎵",
  },
  {
    id: "festival_lunar_hoian",
    category: "festival",
    name: "Lễ Nguyên Tiêu Hội An",
    description: "Cô gái áo dài đi thả đèn hoa đăng trên sông Hoài Hội An đêm rằm tháng Giêng",
    descriptionEn: "Young woman in ao dai releasing floating lantern on Hoai River Hoi An on full moon night of first lunar month",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["magical", "spiritual", "romantic"],
    emoji: "🪔",
  },
  {
    id: "festival_ba_chua_xu",
    category: "festival",
    name: "Lễ Bà Chúa Xứ Châu Đốc",
    description: "Cô gái áo bà ba đi lễ Bà Chúa Xứ ở núi Sam Châu Đốc An Giang, không khí lễ hội miền Tây",
    descriptionEn: "Young woman in ao ba ba attending Lady Xu festival at Sam Mountain Chau Doc An Giang, Mekong Delta festival atmosphere",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["spiritual", "southern", "festive"],
    emoji: "🙏",
  },
  {
    id: "festival_ngay_30_4",
    category: "festival",
    name: "Lễ 30/4 phố cờ đỏ",
    description: "Cô gái áo dài đi giữa phố cổ Sài Gòn rợp cờ đỏ sao vàng dịp lễ 30/4",
    descriptionEn: "Young woman in ao dai walking through Saigon old streets lined with red Vietnamese flags during April 30 holiday",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["patriotic", "festive", "iconic"],
    emoji: "🇻🇳",
  },

  // ============================================================================
  // ===== LOCATION — Miền Bắc (15 more) =====
  // ============================================================================
  {
    id: "loc_ba_be_lake",
    category: "location",
    name: "Hồ Ba Bể Bắc Kạn",
    description: "Cô gái dân tộc Tày chèo thuyền độc mộc trên Hồ Ba Bể Bắc Kạn, núi rừng nguyên sơ phía sau",
    descriptionEn: "Young Tay ethnic woman rowing dugout canoe on Ba Be Lake in Bac Kan, pristine forest mountains behind",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["peaceful", "rural", "majestic"],
    emoji: "🛶",
  },
  {
    id: "loc_ban_gioc",
    category: "location",
    name: "Thác Bản Giốc Cao Bằng",
    description: "Cô gái áo dân tộc Nùng đứng trước thác Bản Giốc hùng vĩ ở Cao Bằng, nước trắng xóa đổ xuống",
    descriptionEn: "Young Nung ethnic woman before majestic Ban Gioc waterfall in Cao Bang, cascading white water",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["majestic", "natural", "remote"],
    emoji: "💦",
  },
  {
    id: "loc_dong_van",
    category: "location",
    name: "Cao nguyên đá Đồng Văn",
    description: "Cô gái Mông đứng trên cao nguyên đá Đồng Văn Hà Giang, đá tai mèo trải dài hùng vĩ",
    descriptionEn: "Young Hmong woman on Dong Van karst plateau in Ha Giang, cat-ear limestone formations stretching majestically",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["majestic", "ethnic", "remote"],
    emoji: "🪨",
  },
  {
    id: "loc_pu_luong",
    category: "location",
    name: "Pù Luông Thanh Hóa",
    description: "Cô gái mặc đầm trắng đứng tại resort homestay Pù Luông nhìn ruộng bậc thang xanh ngắt",
    descriptionEn: "Young woman in white dress at Pu Luong homestay resort overlooking lush green rice terraces",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["serene", "rural", "luxe"],
    emoji: "🏞",
  },
  {
    id: "loc_tam_dao",
    category: "location",
    name: "Tam Đảo mờ sương",
    description: "Cô gái mặc áo khoác len đi giữa thị trấn Tam Đảo Vĩnh Phúc mờ sương, kiến trúc Pháp cổ kính",
    descriptionEn: "Young woman in wool coat walking through misty Tam Dao town in Vinh Phuc, French colonial architecture",
    cameraStyle: "BOKEH",
    time: "overcast",
    mood: ["misty", "vintage", "cozy"],
    emoji: "🌫",
  },
  {
    id: "loc_co_to_island",
    category: "location",
    name: "Đảo Cô Tô Quảng Ninh",
    description: "Cô gái áo tắm xanh đứng trên bãi cát trắng đảo Cô Tô Quảng Ninh, biển xanh ngọc trong veo",
    descriptionEn: "Young woman in blue swimsuit on white sand of Co To Island Quang Ninh, crystal emerald sea",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["tropical", "fresh", "summer"],
    emoji: "🏝",
  },
  {
    id: "loc_van_mieu",
    category: "location",
    name: "Văn Miếu Quốc Tử Giám",
    description: "Cô gái áo dài tím dạo Văn Miếu Quốc Tử Giám Hà Nội, sân Khuê Văn Các kiến trúc cổ kính",
    descriptionEn: "Young woman in purple ao dai at Temple of Literature Hanoi, Khue Van Cac courtyard with ancient architecture",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["scholarly", "traditional", "elegant"],
    emoji: "🏯",
  },
  {
    id: "loc_hoang_thanh",
    category: "location",
    name: "Hoàng Thành Thăng Long",
    description: "Cô gái áo dài vàng đứng tại sân Đoan Môn Hoàng Thành Thăng Long Hà Nội, kiến trúc cung đình cổ",
    descriptionEn: "Young woman in yellow ao dai at Doan Mon courtyard of Thang Long Imperial Citadel Hanoi, ancient royal architecture",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["royal", "traditional", "majestic"],
    emoji: "👑",
  },
  {
    id: "loc_ta_hien",
    category: "location",
    name: "Phố bia Tạ Hiện",
    description: "Nhóm bạn ngồi bia hơi vỉa hè phố Tạ Hiện Hà Nội đêm, cốc bia vàng cụng ly, đèn neon",
    descriptionEn: "Group of friends drinking draft beer on sidewalk of Ta Hien Street Hanoi at night, golden beer mugs clinking, neon signs",
    cameraStyle: "DOCUMENTARY",
    time: "night",
    mood: ["lively", "social", "local"],
    emoji: "🍺",
  },
  {
    id: "loc_chua_huong",
    category: "location",
    name: "Chùa Hương",
    description: "Cô gái áo dài lam đi vào động Hương Tích chùa Hương Hà Nội, bậc đá rêu phong",
    descriptionEn: "Young woman in light blue ao dai entering Huong Tich grotto at Huong Pagoda Hanoi, mossy stone steps",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["spiritual", "ancient", "mystical"],
    emoji: "🪨",
  },
  {
    id: "loc_bai_dinh",
    category: "location",
    name: "Chùa Bái Đính",
    description: "Cô gái áo dài lam đi giữa hành lang La Hán chùa Bái Đính Ninh Bình, 500 tượng La Hán hai bên",
    descriptionEn: "Young woman in light blue ao dai walking through Arhat corridor at Bai Dinh Pagoda Ninh Binh, 500 Arhat statues lining both sides",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["spiritual", "majestic", "iconic"],
    emoji: "🙏",
  },
  {
    id: "loc_bat_trang",
    category: "location",
    name: "Làng gốm Bát Tràng",
    description: "Cô gái áo bà ba ngồi vẽ gốm tại làng cổ Bát Tràng Hà Nội, bàn xoay và đất sét trên tay",
    descriptionEn: "Young woman in ao ba ba painting pottery at Bat Trang ancient ceramic village Hanoi, potter's wheel and clay in hand",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["traditional", "craft", "focused"],
    emoji: "🏺",
  },
  {
    id: "loc_duong_lam",
    category: "location",
    name: "Làng cổ Đường Lâm",
    description: "Cô gái áo tứ thân đi giữa con đường gạch cổ làng Đường Lâm Sơn Tây, cổng làng và nhà cổ",
    descriptionEn: "Young woman in four-panel traditional dress on ancient brick path of Duong Lam village in Son Tay, village gate and old houses",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["nostalgic", "vintage", "rural"],
    emoji: "🏘",
  },
  {
    id: "loc_cat_ba",
    category: "location",
    name: "Đảo Cát Bà",
    description: "Cô gái mặc đầm voan trắng đứng trên du thuyền nhìn quần đảo Cát Bà Hải Phòng, biển xanh và đảo đá",
    descriptionEn: "Young woman in white chiffon dress on cruise looking at Cat Ba archipelago in Hai Phong, blue sea and limestone islands",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["scenic", "luxe", "summer"],
    emoji: "🏞",
  },
  {
    id: "loc_mai_chau",
    category: "location",
    name: "Bản Mai Châu Hòa Bình",
    description: "Cô gái áo dân tộc Thái đứng trước nhà sàn truyền thống Mai Châu Hòa Bình, ruộng lúa xanh phía sau",
    descriptionEn: "Young Thai ethnic woman before traditional stilt house in Mai Chau Hoa Binh, green rice fields behind",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["rural", "ethnic", "peaceful"],
    emoji: "🏠",
  },

  // ============================================================================
  // ===== LOCATION — Miền Trung (12 more) =====
  // ============================================================================
  {
    id: "loc_phong_nha",
    category: "location",
    name: "Hang Sơn Đoòng / Phong Nha",
    description: "Cô gái áo trekking đứng tại cửa hang Phong Nha Quảng Bình, ánh sáng xuyên qua khe đá",
    descriptionEn: "Young woman in trekking outfit at entrance of Phong Nha Cave in Quang Binh, sunbeams through rock crevices",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["majestic", "adventure", "mystical"],
    emoji: "🪨",
  },
  {
    id: "loc_lang_co",
    category: "location",
    name: "Bãi biển Lăng Cô",
    description: "Cô gái áo trắng đi dạo bãi biển Lăng Cô Huế, đầm Lập An và núi Bạch Mã phía xa",
    descriptionEn: "Young woman in white walking Lang Co beach in Hue, Lap An lagoon and Bach Ma mountain in distance",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["scenic", "peaceful", "tropical"],
    emoji: "🌊",
  },
  {
    id: "loc_hai_van_pass",
    category: "location",
    name: "Đèo Hải Vân",
    description: "Cô gái mặc áo khoác đứng trên đèo Hải Vân nhìn vịnh Đà Nẵng, mây trắng phủ phía dưới",
    descriptionEn: "Young woman in jacket atop Hai Van pass overlooking Da Nang Bay, white clouds covering below",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["majestic", "scenic", "adventurous"],
    emoji: "⛰",
  },
  {
    id: "loc_ba_na",
    category: "location",
    name: "Bà Nà Hills Đà Nẵng",
    description: "Cô gái áo dài đi bộ trên Cầu Vàng Bà Nà Hills Đà Nẵng, hai bàn tay đá khổng lồ ôm cây cầu vàng",
    descriptionEn: "Young woman in ao dai walking on Golden Bridge at Ba Na Hills Da Nang, giant stone hands cradling the golden bridge",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["iconic", "majestic", "tourist"],
    emoji: "🌉",
  },
  {
    id: "loc_my_son",
    category: "location",
    name: "Thánh địa Mỹ Sơn",
    description: "Cô gái áo dài đỏ đi giữa di tích Chăm Pa Mỹ Sơn Quảng Nam, đền tháp gạch đỏ cổ xưa",
    descriptionEn: "Young woman in red ao dai among ancient Cham temple ruins at My Son Quang Nam, red brick towers",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["historic", "mystical", "cultural"],
    emoji: "🏛",
  },
  {
    id: "loc_my_khe",
    category: "location",
    name: "Bãi biển Mỹ Khê Đà Nẵng",
    description: "Cô gái áo tắm trắng đứng trên bãi biển Mỹ Khê Đà Nẵng, sóng vỗ và bầu trời xanh",
    descriptionEn: "Young woman in white swimsuit on My Khe beach Da Nang, gentle waves and blue sky",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["tropical", "summer", "fresh"],
    emoji: "🏖",
  },
  {
    id: "loc_thien_mu",
    category: "location",
    name: "Chùa Thiên Mụ Huế",
    description: "Cô gái áo dài tím Huế đứng dưới tháp Phước Duyên chùa Thiên Mụ, sông Hương phía xa",
    descriptionEn: "Young woman in Hue purple ao dai before Phuoc Duyen tower of Thien Mu Pagoda, Perfume River in distance",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["spiritual", "iconic", "elegant"],
    emoji: "🛕",
  },
  {
    id: "loc_quy_nhon",
    category: "location",
    name: "Eo Gió Quy Nhơn",
    description: "Cô gái áo voan trắng đứng tại Eo Gió Quy Nhơn Bình Định, vách đá uốn lượn ôm bãi biển",
    descriptionEn: "Young woman in white chiffon at Eo Gio (Wind Strait) Quy Nhon Binh Dinh, curving cliffs embracing the beach",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["scenic", "luxe", "remote"],
    emoji: "🌊",
  },
  {
    id: "loc_mui_ne_dunes",
    category: "location",
    name: "Đồi cát Bay Mũi Né",
    description: "Cô gái áo dài đỏ đứng trên đồi cát vàng Mũi Né Bình Thuận lúc bình minh, sa mạc nhỏ",
    descriptionEn: "Young woman in red ao dai on yellow sand dunes of Mui Ne Binh Thuan at sunrise, mini desert landscape",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["dramatic", "warm", "desert"],
    emoji: "🏜",
  },
  {
    id: "loc_nha_trang_beach",
    category: "location",
    name: "Bãi biển Nha Trang",
    description: "Cô gái áo tắm xanh đi dọc bãi biển Nha Trang Khánh Hòa, hàng dừa và resort hiện đại",
    descriptionEn: "Young woman in blue swimsuit walking along Nha Trang beach Khanh Hoa, palm trees and modern resorts",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["tropical", "luxe", "summer"],
    emoji: "🌴",
  },
  {
    id: "loc_mang_den",
    category: "location",
    name: "Măng Đen Kontum",
    description: "Cô gái áo len ấm đứng giữa rừng thông Măng Đen Kontum, sương sớm bao phủ",
    descriptionEn: "Young woman in warm sweater in pine forest of Mang Den Kontum, early morning mist enveloping",
    cameraStyle: "BOKEH",
    time: "overcast",
    mood: ["serene", "ethereal", "healing"],
    emoji: "🌲",
  },
  {
    id: "loc_buon_ma_thuot",
    category: "location",
    name: "Hồ Lak Buôn Ma Thuột",
    description: "Cô gái áo dân tộc Ê Đê cưỡi voi bên Hồ Lak Đắk Lắk, không gian Tây Nguyên hùng vĩ",
    descriptionEn: "Young Ede ethnic woman riding elephant by Lak Lake in Dak Lak, majestic Central Highlands landscape",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["ethnic", "adventure", "rural"],
    emoji: "🐘",
  },

  // ============================================================================
  // ===== LOCATION — Miền Nam & Miền Tây (15 more) =====
  // ============================================================================
  {
    id: "loc_cu_chi_tunnels",
    category: "location",
    name: "Địa đạo Củ Chi",
    description: "Cô gái áo bộ đội xanh đứng trước cửa địa đạo Củ Chi Sài Gòn, di tích chiến tranh",
    descriptionEn: "Young woman in green soldier uniform before Cu Chi tunnel entrance Saigon, war historical site",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["historic", "rugged", "patriotic"],
    emoji: "⚔️",
  },
  {
    id: "loc_vung_tau_jesus",
    category: "location",
    name: "Tượng Chúa Vũng Tàu",
    description: "Cô gái áo dài trắng đứng trên núi Nhỏ trước tượng Chúa Kitô Vua Vũng Tàu, biển xanh phía dưới",
    descriptionEn: "Young woman in white ao dai on Small Mountain before Christ the King statue in Vung Tau, blue sea below",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["iconic", "spiritual", "majestic"],
    emoji: "✝️",
  },
  {
    id: "loc_ho_tram",
    category: "location",
    name: "Bãi biển Hồ Tràm",
    description: "Cô gái áo tắm hồng đi dạo bãi biển Hồ Tràm Bà Rịa Vũng Tàu, sóng và rừng phi lao",
    descriptionEn: "Young woman in pink swimsuit walking Ho Tram beach Ba Ria Vung Tau, waves and casuarina forest",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["tropical", "peaceful", "summer"],
    emoji: "🌴",
  },
  {
    id: "loc_con_dao",
    category: "location",
    name: "Côn Đảo",
    description: "Cô gái mặc đầm trắng đứng tại bãi Đầm Trầu Côn Đảo, biển ngọc và máy bay phía xa",
    descriptionEn: "Young woman in white dress at Dam Trau beach Con Dao, emerald sea and airplane in distance",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["luxe", "tropical", "remote"],
    emoji: "✈️",
  },
  {
    id: "loc_phu_quy",
    category: "location",
    name: "Đảo Phú Quý",
    description: "Cô gái mặc đầm xanh dưới Cây Cô Đơn ở đảo Phú Quý Bình Thuận, biển và đá núi lửa",
    descriptionEn: "Young woman in green dress under iconic Lonely Tree on Phu Quy Island Binh Thuan, sea and volcanic rocks",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["scenic", "remote", "dramatic"],
    emoji: "🌳",
  },
  {
    id: "loc_tra_su",
    category: "location",
    name: "Rừng tràm Trà Sư",
    description: "Cô gái áo bà ba ngồi xuồng nhỏ chèo qua rừng tràm Trà Sư An Giang, bèo xanh phủ kín mặt nước",
    descriptionEn: "Young woman in ao ba ba on small boat through Tra Su melaleuca forest An Giang, green duckweed covering water surface",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["serene", "rural", "magical"],
    emoji: "🌿",
  },
  {
    id: "loc_thot_not_field",
    category: "location",
    name: "Cánh đồng thốt nốt",
    description: "Cô gái áo bà ba đi giữa cánh đồng thốt nốt An Giang, hàng cây thốt nốt cao vút và đồng lúa vàng",
    descriptionEn: "Young woman in ao ba ba in toddy palm field of An Giang, towering palm trees and golden rice paddy",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["rural", "iconic", "warm"],
    emoji: "🌴",
  },
  {
    id: "loc_tram_chim",
    category: "location",
    name: "Vườn quốc gia Tràm Chim",
    description: "Cô gái áo bà ba xanh ngồi xuồng đi qua Tràm Chim Đồng Tháp mùa nước nổi, sếu và cò bay phía sau",
    descriptionEn: "Young woman in blue ao ba ba on boat through Tram Chim Dong Thap during flood season, cranes and storks flying behind",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["natural", "peaceful", "rural"],
    emoji: "🦩",
  },
  {
    id: "loc_cai_be",
    category: "location",
    name: "Chợ nổi Cái Bè",
    description: "Cô gái áo bà ba đứng trên thuyền tại chợ nổi Cái Bè Tiền Giang, các thuyền bán hàng trao đổi",
    descriptionEn: "Young woman in ao ba ba on boat at Cai Be floating market Tien Giang, exchanging boats with vendors",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["lively", "rural", "authentic"],
    emoji: "🛶",
  },
  {
    id: "loc_ben_tre_coconut",
    category: "location",
    name: "Vườn dừa Bến Tre",
    description: "Cô gái áo bà ba đứng giữa vườn dừa Bến Tre, hàng dừa cao và sông nước phía sau",
    descriptionEn: "Young woman in ao ba ba in coconut grove of Ben Tre, tall coconut trees and river waterway behind",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["rural", "tropical", "warm"],
    emoji: "🥥",
  },
  {
    id: "loc_cao_dai_tay_ninh",
    category: "location",
    name: "Tòa Thánh Cao Đài Tây Ninh",
    description: "Cô gái áo dài trắng đứng trước Tòa Thánh Cao Đài Tây Ninh, kiến trúc rực rỡ ba màu",
    descriptionEn: "Young woman in white ao dai before Cao Dai Holy See in Tay Ninh, vibrant tri-color architecture",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["spiritual", "iconic", "colorful"],
    emoji: "🏛",
  },
  {
    id: "loc_ba_den_mountain",
    category: "location",
    name: "Núi Bà Đen Tây Ninh",
    description: "Cô gái mặc đầm trắng đứng đỉnh núi Bà Đen Tây Ninh sau khi cáp treo, mây trời bao quanh",
    descriptionEn: "Young woman in white dress atop Ba Den Mountain Tay Ninh after cable car ride, clouds surrounding",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["majestic", "spiritual", "scenic"],
    emoji: "🏔",
  },
  {
    id: "loc_camau_tip",
    category: "location",
    name: "Mũi Cà Mau",
    description: "Cô gái áo bà ba đứng tại cột mốc tọa độ Mũi Cà Mau, cuối đất nước hình chữ S",
    descriptionEn: "Young woman in ao ba ba at coordinate marker of Ca Mau Cape, southernmost tip of Vietnam",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["iconic", "historic", "patriotic"],
    emoji: "📍",
  },
  {
    id: "loc_ha_tien",
    category: "location",
    name: "Hà Tiên Kiên Giang",
    description: "Cô gái mặc đầm voan đứng trên Mũi Nai Hà Tiên Kiên Giang, hoàng hôn vàng cam phía biển",
    descriptionEn: "Young woman in chiffon dress on Mui Nai Ha Tien Kien Giang, golden orange sunset over the sea",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["romantic", "scenic", "tropical"],
    emoji: "🌅",
  },
  {
    id: "loc_bui_vien_walk",
    category: "location",
    name: "Phố Tây Bùi Viện đêm",
    description: "Cô gái áo crop top dạo phố Tây Bùi Viện Sài Gòn đêm, đèn neon và quán bar tấp nập",
    descriptionEn: "Young woman in crop top walking Bui Vien Western Street Saigon at night, neon lights and bustling bars",
    cameraStyle: "DOCUMENTARY",
    time: "night",
    mood: ["edgy", "urban", "vibrant"],
    emoji: "🌃",
  },

  // ============================================================================
  // ===== LIFESTYLE — Đời thường VN (~25 themes new) =====
  // ============================================================================
  {
    id: "life_nhau_via_he",
    category: "lifestyle",
    name: "Nhậu vỉa hè cụng ly 1-2-3 dzô",
    description: "Nhóm bạn ngồi nhậu bia vỉa hè Sài Gòn, cụng ly bia vàng giơ cao hô '1, 2, 3 dzô', mồi tươi và nồi lẩu trên bàn",
    descriptionEn: "Group of friends drinking beer at Saigon sidewalk pub, raising golden beer glasses high to clink and shout '1, 2, 3 cheers', fresh seafood and hotpot on table",
    cameraStyle: "DOCUMENTARY",
    time: "night",
    mood: ["lively", "social", "joyful"],
    emoji: "🍻",
  },
  {
    id: "life_seafood_long_hai",
    category: "lifestyle",
    name: "Nhậu hải sản Long Hải",
    description: "Cặp đôi ngồi nhậu hải sản tại quán bãi biển Long Hải, ghẹ luộc và bia lon, hoàng hôn phía sau",
    descriptionEn: "Couple eating seafood at Long Hai beach restaurant, boiled crab and canned beer, sunset behind",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["romantic", "casual", "summer"],
    emoji: "🦀",
  },
  {
    id: "life_bia_hoi_ta_hien",
    category: "lifestyle",
    name: "Bia hơi Tạ Hiện",
    description: "Nhóm bạn ngồi bia hơi vỉa hè Tạ Hiện Hà Nội, ghế nhựa thấp, ly bia vàng đầy bọt, đèn vàng phố cổ",
    descriptionEn: "Group of friends drinking draft beer on sidewalk of Ta Hien Street Hanoi, low plastic stools, frothy golden beer, warm yellow old quarter lights",
    cameraStyle: "DOCUMENTARY",
    time: "night",
    mood: ["lively", "iconic", "local"],
    emoji: "🍺",
  },
  {
    id: "life_lau_thai_rainy",
    category: "lifestyle",
    name: "Lẩu Thái ngày mưa",
    description: "Nhóm bạn ngồi ăn lẩu Thái nồi đỏ rực bốc khói tại quán nhỏ ngày mưa Sài Gòn, mưa nhẹ ngoài cửa",
    descriptionEn: "Group of friends eating spicy red Thai hotpot steaming hot at a small restaurant on a rainy Saigon day, light rain outside window",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["cozy", "warm", "social"],
    emoji: "🍲",
  },
  {
    id: "life_kbbq",
    category: "lifestyle",
    name: "BBQ Hàn Quốc",
    description: "Nhóm bạn nướng BBQ Hàn Quốc tại nhà hàng, thịt sườn nướng trên bếp than, kim chi và soju",
    descriptionEn: "Group of friends grilling Korean BBQ at restaurant, marinated short ribs over charcoal grill, kimchi and soju",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["lively", "trendy", "social"],
    emoji: "🍖",
  },
  {
    id: "life_tra_da",
    category: "lifestyle",
    name: "Trà đá vỉa hè",
    description: "Cô gái ngồi trà đá vỉa hè Hà Nội buổi chiều, ghế nhựa thấp, ly trà đá đá lạnh, hóng mát phố cổ",
    descriptionEn: "Young woman at sidewalk iced tea spot in Hanoi afternoon, low plastic stool, glass of iced tea, cooling off in old quarter",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["local", "casual", "authentic"],
    emoji: "🧊",
  },
  {
    id: "life_caphe_coc",
    category: "lifestyle",
    name: "Cà phê cóc vỉa hè",
    description: "Anh chàng ngồi uống cà phê đen đá tại cà phê cóc vỉa hè Sài Gòn buổi sáng, ghế nhựa thấp, người dân qua lại",
    descriptionEn: "Young man drinking iced black coffee at sidewalk coffee stall in Saigon morning, low plastic stool, locals passing by",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["local", "authentic", "casual"],
    emoji: "☕",
  },
  {
    id: "life_chay_bo_park",
    category: "lifestyle",
    name: "Chạy bộ công viên sáng",
    description: "Anh chàng chạy bộ buổi sáng tại công viên Tao Đàn Sài Gòn, đồ thể thao Nike, ánh nắng vàng xuyên qua hàng cây",
    descriptionEn: "Young man jogging in morning at Tao Dan Park Saigon, Nike sportswear, golden morning light through tree-lined path",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["energetic", "fresh", "healthy"],
    emoji: "🏃",
  },
  {
    id: "life_chay_bo_west_lake",
    category: "lifestyle",
    name: "Chạy bộ ven Hồ Tây",
    description: "Cô gái chạy bộ ven Hồ Tây Hà Nội buổi sáng sớm, sương mờ trên mặt hồ, áo thể thao gọn gàng",
    descriptionEn: "Young woman jogging along West Lake in Hanoi early morning, mist over the water, athletic outfit",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["fresh", "peaceful", "healthy"],
    emoji: "🏃‍♀️",
  },
  {
    id: "life_metro_saigon",
    category: "lifestyle",
    name: "Đi MRT Bến Thành Suối Tiên",
    description: "Cô gái ngồi trên ga MRT Sài Gòn tuyến Bến Thành Suối Tiên, ghế xanh hiện đại, cửa kính lớn",
    descriptionEn: "Young woman on MRT train of Saigon Ben Thanh-Suoi Tien line, modern blue seats, large glass doors",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["modern", "urban", "clean"],
    emoji: "🚇",
  },
  {
    id: "life_xe_buyt",
    category: "lifestyle",
    name: "Đi xe buýt Sài Gòn",
    description: "Cô gái sinh viên cầm balo đứng tại trạm xe buýt Sài Gòn chờ xe, biển xe buýt và phố sá",
    descriptionEn: "Young female student with backpack at Saigon bus stop waiting, bus signs and street scene",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["everyday", "youthful", "urban"],
    emoji: "🚌",
  },
  {
    id: "life_grab_bike",
    category: "lifestyle",
    name: "Grab bike đường phố",
    description: "Cô gái đeo balo ngồi sau xe Grab bike màu xanh chạy trên phố Sài Gòn, áo bảo hiểm xanh trên tay",
    descriptionEn: "Young woman with backpack on back of green Grab bike riding through Saigon streets, green helmet in hand",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["modern", "urban", "everyday"],
    emoji: "🛵",
  },
  {
    id: "life_wedding_traditional",
    category: "lifestyle",
    name: "Đám cưới truyền thống bê tráp",
    description: "Cô dâu áo dài đỏ và chú rể áo dài đen đứng giữa đoàn bê tráp 7 mâm, không khí lễ ăn hỏi truyền thống",
    descriptionEn: "Bride in red ao dai and groom in black ao dai with 7-tray engagement procession, traditional Vietnamese engagement ceremony atmosphere",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["traditional", "festive", "ceremonial"],
    emoji: "💒",
  },
  {
    id: "life_wedding_modern",
    category: "lifestyle",
    name: "Tiệc cưới hiện đại sảnh tiệc",
    description: "Cô dâu áo cưới trắng phương Tây và chú rể áo vest đen đi vào sảnh tiệc cưới sang trọng, hoa và đèn lung linh",
    descriptionEn: "Bride in white Western wedding dress and groom in black tuxedo entering luxurious wedding hall, flowers and sparkling lights",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["luxe", "romantic", "ceremonial"],
    emoji: "👰‍♀️",
  },
  {
    id: "life_le_an_hoi",
    category: "lifestyle",
    name: "Lễ ăn hỏi 5 mâm tráp",
    description: "Cô gái mặc áo dài đỏ ngồi giữa nhà với 5 mâm tráp lễ ăn hỏi, gia đình hai bên xung quanh",
    descriptionEn: "Young woman in red ao dai sitting at home with 5 traditional engagement trays, families gathered around",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["traditional", "ceremonial", "family"],
    emoji: "🎁",
  },
  {
    id: "life_vincom_shopping",
    category: "lifestyle",
    name: "Vincom shopping mall",
    description: "Cô gái cầm túi shopping đi giữa Vincom Center Sài Gòn hiện đại, cửa hàng thời trang sang trọng hai bên",
    descriptionEn: "Young woman carrying shopping bags at modern Vincom Center Saigon, luxury fashion shops on both sides",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["luxe", "modern", "lifestyle"],
    emoji: "🛍",
  },
  {
    id: "life_cinema",
    category: "lifestyle",
    name: "Xem phim CGV / Lotte",
    description: "Cặp đôi ngồi xem phim trong rạp CGV/Lotte Sài Gòn, bắp rang bơ trên tay, màn hình lớn phía trước",
    descriptionEn: "Young couple watching movie at CGV/Lotte cinema in Saigon, popcorn in hand, large screen in front",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["romantic", "modern", "leisure"],
    emoji: "🎬",
  },
  {
    id: "life_karaoke",
    category: "lifestyle",
    name: "Karaoke phòng neon",
    description: "Nhóm bạn hát karaoke trong phòng neon hồng tím, micro trên tay, màn hình hiện lời bài hát",
    descriptionEn: "Group of friends singing karaoke in pink-purple neon room, microphone in hand, lyrics on screen",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["fun", "social", "vibrant"],
    emoji: "🎤",
  },
  {
    id: "life_rooftop_bar",
    category: "lifestyle",
    name: "Rooftop bar Sài Gòn",
    description: "Cô gái mặc đầm đen cầm cocktail tại rooftop bar Sài Gòn, view tòa nhà cao tầng đêm phía xa",
    descriptionEn: "Young woman in black dress holding cocktail at Saigon rooftop bar, high-rise city skyline view at night",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["luxe", "sophisticated", "urban"],
    emoji: "🍸",
  },
  {
    id: "life_bun_dau",
    category: "lifestyle",
    name: "Bún đậu mắm tôm",
    description: "Cô gái ngồi ăn bún đậu mắm tôm vỉa hè Hà Nội, đậu hũ rán vàng, chả cốm và rau sống đầy đĩa",
    descriptionEn: "Young woman eating bun dau mam tom at Hanoi sidewalk, golden fried tofu, cha com and fresh herbs on plate",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["local", "authentic", "lively"],
    emoji: "🥢",
  },
  {
    id: "life_che_via_he",
    category: "lifestyle",
    name: "Chè vỉa hè",
    description: "Cô gái ngồi ăn chè ba màu trong cốc thủy tinh tại quán chè vỉa hè Sài Gòn buổi tối",
    descriptionEn: "Young woman eating tri-color che in glass cup at Saigon sidewalk dessert stall in evening",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["sweet", "local", "casual"],
    emoji: "🍧",
  },
  {
    id: "life_buffet",
    category: "lifestyle",
    name: "Ăn buffet sang",
    description: "Cô gái áo đẹp đứng tại quầy buffet nhà hàng sang trọng, hải sản và sushi tươi đầy ắp",
    descriptionEn: "Stylishly dressed young woman at upscale restaurant buffet station, fresh seafood and sushi abundantly displayed",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["luxe", "social", "celebratory"],
    emoji: "🍣",
  },
  {
    id: "life_park_walk_family",
    category: "lifestyle",
    name: "Gia đình dạo công viên",
    description: "Gia đình 4 người dạo công viên Tao Đàn Sài Gòn buổi chiều, bố mẹ và 2 con nhỏ, không khí ấm cúng",
    descriptionEn: "Family of 4 walking Tao Dan Park Saigon in afternoon, parents with 2 young children, warm intimate atmosphere",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["family", "warm", "happy"],
    emoji: "👨‍👩‍👧‍👦",
  },
  {
    id: "life_supermarket",
    category: "lifestyle",
    name: "Đi siêu thị",
    description: "Cô gái đẩy xe đẩy mua sắm tại siêu thị Co-op Mart hoặc WinMart, kệ hàng đầy ắp đồ",
    descriptionEn: "Young woman pushing shopping cart at Co-op Mart or WinMart supermarket, fully stocked shelves",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["everyday", "casual", "modern"],
    emoji: "🛒",
  },
  {
    id: "life_gym_evening",
    category: "lifestyle",
    name: "Gym buổi tối",
    description: "Anh chàng tập tạ tại phòng gym hiện đại buổi tối sau giờ làm, đèn vàng và gương lớn",
    descriptionEn: "Young man lifting weights at modern gym in evening after work, warm lighting and large mirrors",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["athletic", "focused", "strong"],
    emoji: "💪",
  },

  // ============================================================================
  // ===== LIFESTYLE — Đồng quê (~10 themes) =====
  // ============================================================================
  {
    id: "life_xuong_ba_la",
    category: "lifestyle",
    name: "Chèo xuồng ba lá miền Tây",
    description: "Cô gái áo bà ba và nón lá chèo xuồng ba lá trên kênh nước miền Tây, hai bên là vườn cây trái sum sê",
    descriptionEn: "Young woman in ao ba ba and conical hat rowing three-plank boat through Mekong Delta canal, fruit orchards on both banks",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["rural", "iconic", "peaceful"],
    emoji: "🛶",
  },
  {
    id: "life_hai_sen",
    category: "lifestyle",
    name: "Hái sen đầm Đồng Tháp",
    description: "Cô gái áo bà ba hồng cầm bó sen vừa hái trên đầm sen Đồng Tháp Mười, sen hồng nở rộ xung quanh",
    descriptionEn: "Young woman in pink ao ba ba holding freshly picked lotus on Dong Thap Muoi lotus pond, pink lotus blooming around",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["rural", "serene", "traditional"],
    emoji: "🪷",
  },
  {
    id: "life_thu_hoach_lua",
    category: "lifestyle",
    name: "Thu hoạch lúa miền Tây",
    description: "Cô gái áo bà ba đứng giữa cánh đồng lúa chín đang thu hoạch, máy gặt phía sau và lúa vàng",
    descriptionEn: "Young woman in ao ba ba in golden rice field during harvest, combine harvester behind and golden rice",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["rural", "warm", "authentic"],
    emoji: "🌾",
  },
  {
    id: "life_cay_lua_north",
    category: "lifestyle",
    name: "Cấy lúa ruộng Bắc Bộ",
    description: "Cô gái áo bà ba và nón lá cấy lúa trên ruộng nước miền Bắc, cò trắng bay phía xa",
    descriptionEn: "Young woman in ao ba ba with conical hat planting rice in Northern Vietnamese paddy field, white herons flying in distance",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["rural", "traditional", "labor"],
    emoji: "🌱",
  },
  {
    id: "life_dua_nuoc",
    category: "lifestyle",
    name: "Rừng dừa nước Bến Tre",
    description: "Cô gái áo bà ba ngồi xuồng đi qua rừng dừa nước Bến Tre, lá dừa rủ xuống mặt nước trong vắt",
    descriptionEn: "Young woman in ao ba ba on small boat through water coconut forest of Ben Tre, fronds drooping over crystal water",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["serene", "tropical", "magical"],
    emoji: "🌴",
  },
  {
    id: "life_dap_lua_san",
    category: "lifestyle",
    name: "Phơi lúa sân nhà",
    description: "Cô gái áo bà ba đảo lúa phơi trên sân gạch quê miền Tây, mặt trời chiếu vàng rực hạt lúa",
    descriptionEn: "Young woman in ao ba ba turning rice spread to dry on brick courtyard of Mekong country home, sun making golden grains shine",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["rural", "warm", "traditional"],
    emoji: "🌾",
  },
  {
    id: "life_trau_buffalo",
    category: "lifestyle",
    name: "Cưỡi trâu đồng quê",
    description: "Cô bé áo bà ba ngồi trên lưng trâu nước đi qua đồng làng quê Việt Nam, hoàng hôn vàng cam",
    descriptionEn: "Young girl in ao ba ba riding water buffalo across Vietnamese countryside village field, golden orange sunset",
    cameraStyle: "DOCUMENTARY",
    time: "golden_hour",
    mood: ["rural", "iconic", "warm"],
    emoji: "🐃",
  },
  {
    id: "life_cho_que_morning",
    category: "lifestyle",
    name: "Chợ quê sáng sớm",
    description: "Cô gái áo bà ba mua rau tại chợ quê miền Tây sáng sớm, sạp hàng bày rau củ tươi và hoa quả",
    descriptionEn: "Young woman in ao ba ba shopping vegetables at rural Mekong morning market, fresh vegetable and fruit stalls",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["rural", "lively", "authentic"],
    emoji: "🥬",
  },
  {
    id: "life_san_lua_vuon",
    category: "lifestyle",
    name: "Vườn cây ăn trái",
    description: "Cô gái áo bà ba hái sầu riêng trong vườn cây ăn trái Lái Thiêu Bình Dương, cây sai trĩu trái",
    descriptionEn: "Young woman in ao ba ba picking durian in fruit orchard of Lai Thieu Binh Duong, trees heavy with fruits",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["rural", "tropical", "warm"],
    emoji: "🍈",
  },
  {
    id: "life_que_grandma_kitchen",
    category: "lifestyle",
    name: "Bà ngoại bếp lửa quê",
    description: "Bà ngoại tóc bạc đeo khăn rằn ngồi bên bếp lửa quê miền Tây nấu cơm, khói bếp và nồi cơm gang",
    descriptionEn: "Silver-haired grandmother with traditional scarf cooking by Mekong country wood-fire kitchen, smoke and cast iron rice pot",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["nostalgic", "warm", "authentic"],
    emoji: "🔥",
  },

  // ============================================================================
  // ===== TRAVEL (5 more) =====
  // ============================================================================
  {
    id: "travel_vinpearl",
    category: "travel",
    name: "Vinpearl resort",
    description: "Cô gái áo tắm trắng đứng tại hồ bơi vô cực Vinpearl Phú Quốc, biển xanh và hoàng hôn phía sau",
    descriptionEn: "Young woman in white swimsuit at Vinpearl Phu Quoc infinity pool, blue sea and sunset behind",
    cameraStyle: "BOKEH",
    time: "golden_hour",
    mood: ["luxe", "tropical", "summer"],
    emoji: "🏖",
  },
  {
    id: "travel_homestay_sapa",
    category: "travel",
    name: "Homestay Sapa",
    description: "Cô gái mặc áo len ngồi ban công homestay nhà sàn Sapa nhìn ruộng bậc thang, sương sớm",
    descriptionEn: "Young woman in wool sweater on balcony of Sapa stilt-house homestay overlooking rice terraces, early morning mist",
    cameraStyle: "BOKEH",
    time: "overcast",
    mood: ["cozy", "ethereal", "rural"],
    emoji: "🏔",
  },
  {
    id: "travel_dalat_train",
    category: "travel",
    name: "Ga tàu Đà Lạt cổ",
    description: "Cô gái áo dài cách tân đứng tại sân ga Đà Lạt cổ, kiến trúc Pháp và đầu tàu hơi nước",
    descriptionEn: "Young woman in modern ao dai at vintage Da Lat train station, French architecture and steam locomotive",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["vintage", "romantic", "nostalgic"],
    emoji: "🚂",
  },
  {
    id: "travel_dalat_lake",
    category: "travel",
    name: "Hồ Xuân Hương Đà Lạt",
    description: "Cô gái mặc áo khoác dạo bộ ven Hồ Xuân Hương Đà Lạt, sương mù trên mặt hồ buổi sáng",
    descriptionEn: "Young woman in coat strolling along Xuan Huong Lake Da Lat, morning mist on water surface",
    cameraStyle: "BOKEH",
    time: "overcast",
    mood: ["romantic", "misty", "serene"],
    emoji: "🌫",
  },
  {
    id: "travel_passport_airport",
    category: "travel",
    name: "Cầm passport sân bay",
    description: "Cô gái cầm passport và vé máy bay tại sảnh check-in sân bay Tân Sơn Nhất, vali kéo phía sau",
    descriptionEn: "Young woman holding passport and boarding pass at Tan Son Nhat airport check-in hall, rolling suitcase behind",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["travel", "modern", "anticipation"],
    emoji: "🛂",
  },

  // ============================================================================
  // ===== SPORT (3 more) =====
  // ============================================================================
  {
    id: "sport_marathon",
    category: "sport",
    name: "Marathon Sài Gòn",
    description: "Anh chàng chạy marathon Sài Gòn HCMC, áo bib số trên ngực, nhiều người chạy phía sau",
    descriptionEn: "Young man running Saigon HCMC marathon, race bib on chest, many runners behind",
    cameraStyle: "DOCUMENTARY",
    time: "midday",
    mood: ["athletic", "energetic", "communal"],
    emoji: "🏃‍♂️",
  },
  {
    id: "sport_swimming_pool",
    category: "sport",
    name: "Bơi hồ bơi indoor",
    description: "Cô gái mặc đồ bơi đen kính bơi đứng cạnh hồ bơi Olympic indoor, làn bơi dài phía sau",
    descriptionEn: "Young woman in black swimsuit and goggles by Olympic indoor swimming pool, long lap lanes behind",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["athletic", "focused", "clean"],
    emoji: "🏊‍♀️",
  },
  {
    id: "sport_badminton",
    category: "sport",
    name: "Cầu lông sân chuyên nghiệp",
    description: "Cô gái mặc đồ thể thao đánh cầu lông sân chuyên nghiệp, vợt trên tay đang đập cầu",
    descriptionEn: "Young woman in sportswear playing badminton on professional court, racket smashing shuttlecock",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["athletic", "energetic", "competitive"],
    emoji: "🏸",
  },

  // ============================================================================
  // ===== CAREER (3 more) =====
  // ============================================================================
  {
    id: "career_chef",
    category: "career",
    name: "Đầu bếp chuyên nghiệp",
    description: "Anh chàng đầu bếp mặc áo trắng đầu bếp đang xào lửa tại bếp nhà hàng cao cấp, lửa bùng lên",
    descriptionEn: "Young male chef in white chef coat stir-frying with flames at upscale restaurant kitchen, flames rising",
    cameraStyle: "DOCUMENTARY",
    time: "indoor",
    mood: ["professional", "energetic", "craft"],
    emoji: "👨‍🍳",
  },
  {
    id: "career_lawyer",
    category: "career",
    name: "Luật sư văn phòng",
    description: "Cô gái luật sư mặc đồ đen cầm hồ sơ tại văn phòng luật, kệ sách luật phía sau",
    descriptionEn: "Young female lawyer in black suit holding file folders at law office, law book shelves behind",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["professional", "confident", "scholarly"],
    emoji: "⚖️",
  },
  {
    id: "career_pilot",
    category: "career",
    name: "Cơ trưởng máy bay",
    description: "Anh chàng cơ trưởng mặc đồng phục Vietnam Airlines đứng cạnh máy bay, tay cầm mũ phi công",
    descriptionEn: "Young male pilot in Vietnam Airlines uniform beside aircraft, holding pilot cap in hand",
    cameraStyle: "BOKEH",
    time: "midday",
    mood: ["professional", "confident", "iconic"],
    emoji: "✈️",
  },

  // ============================================================================
  // ===== TIME (2 more) =====
  // ============================================================================
  {
    id: "time_dawn_pier",
    category: "time",
    name: "Bình minh cầu cảng",
    description: "Cô gái mặc áo trắng đứng trên cầu cảng cá miền Trung lúc bình minh, thuyền cá quay về",
    descriptionEn: "Young woman in white on Central Vietnam fishing pier at dawn, fishing boats returning",
    cameraStyle: "DOCUMENTARY",
    time: "golden_hour",
    mood: ["serene", "fresh", "rural"],
    emoji: "🌅",
  },
  {
    id: "time_neon_district",
    category: "time",
    name: "Đèn neon phố Nhật Bản",
    description: "Cô gái áo dài cách tân dạo phố Lê Thánh Tôn 'Little Tokyo' Sài Gòn đêm, đèn neon Nhật Bản đỏ vàng",
    descriptionEn: "Young woman in modern ao dai walking Le Thanh Ton 'Little Tokyo' street Saigon at night, Japanese red and yellow neon",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["edgy", "vibrant", "urban"],
    emoji: "🏮",
  },

  // ============================================================================
  // ===== CINEMA (2 more) =====
  // ============================================================================
  {
    id: "cinema_french_colonial",
    category: "cinema",
    name: "Đông Dương Pháp thuộc",
    description: "Cô gái mặc đầm trắng cổ điển kiểu Đông Dương đứng trong nhà cổ Pháp thuộc, quạt trần và cửa lá sách",
    descriptionEn: "Young woman in classic white Indochine dress in French colonial house, ceiling fan and louvered shutters",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["nostalgic", "vintage", "cinematic"],
    emoji: "🎞",
  },
  {
    id: "cinema_dao_keo",
    category: "cinema",
    name: "Đảo Kéo Hong Kong 90s",
    description: "Cô gái áo dài cổ Tàu đứng tại quán mì cổ Hong Kong style 90s, đèn neon đỏ phản chiếu trên vách",
    descriptionEn: "Young woman in qipao at vintage Hong Kong-style noodle shop 90s, red neon reflecting on walls",
    cameraStyle: "BOKEH",
    time: "night",
    mood: ["noir", "vintage", "moody"],
    emoji: "🥢",
  },

  // ============================================================================
  // ===== VEHICLE (2 more) =====
  // ============================================================================
  {
    id: "vehicle_classic_lambretta",
    category: "vehicle",
    name: "Lambretta cổ Sài Gòn",
    description: "Cặp đôi mặc đồ vintage ngồi trên Lambretta cổ màu xanh dương đậu trước nhà thờ Đức Bà",
    descriptionEn: "Vintage-styled couple on classic blue Lambretta scooter parked before Notre-Dame Cathedral Saigon",
    cameraStyle: "BOKEH",
    time: "afternoon",
    mood: ["vintage", "romantic", "iconic"],
    emoji: "🛵",
  },
  {
    id: "vehicle_grab_helmet",
    category: "vehicle",
    name: "Áo Grab giao đồ ăn",
    description: "Anh chàng mặc áo xanh Grab giao đồ ăn cầm hộp đứng trước cửa nhà, balo Grab xanh sau lưng",
    descriptionEn: "Young man in green Grab uniform delivering food box at apartment door, green Grab backpack on back",
    cameraStyle: "DOCUMENTARY",
    time: "afternoon",
    mood: ["everyday", "modern", "urban"],
    emoji: "🛵",
  },

  // ============================================================================
  // ===== STYLE (1 more) =====
  // ============================================================================
  {
    id: "style_business_male",
    category: "style",
    name: "Doanh nhân vest đen",
    description: "Anh chàng doanh nhân mặc vest đen áo sơ mi trắng cravat đứng giữa sảnh tòa nhà công sở hiện đại",
    descriptionEn: "Young businessman in black suit, white shirt and tie in modern corporate building lobby",
    cameraStyle: "BOKEH",
    time: "indoor",
    mood: ["professional", "luxe", "modern"],
    emoji: "👔",
  },
];
