/**
 * AI Storyboard Frame Generator v0.6.5
 *
 * Reads user's idea + product + industry context → generates tailored frames.
 * Supports multiple AI providers (Gemini + OpenAI) for user comparison.
 *
 * Output frames are in Vietnamese (user's input language) for easy editing.
 * They get translated to English at prompt assembly time.
 */

import type { PromptProject } from "../../types";
import { callGemini } from "../gemini";
import { callOpenAI } from "../openai";
import type { GridFormat } from "./arcs";
import { FORMAT_CONFIGS } from "./arcs";

export type AIProvider = "gemini" | "openai";

export interface AIGenerateOptions {
  project: PromptProject;
  /** AI provider to use */
  provider: AIProvider;
  /** Force specific format, or "auto" to let AI decide */
  formatPreference?: GridFormat | "auto";
  /** Brand name from storyboard settings */
  brandName?: string;
  /** Tagline */
  tagline?: string;
}

export interface AIGeneratedFrame {
  num: number;
  timing: string;
  /** Role label (Hook/Problem/Reveal/Apply/Result/Hero/Logo etc) */
  role: string;
  /** Action description in Vietnamese (user can edit) */
  actionVi: string;
  /** English translation generated by AI for prompt assembly */
  actionEn: string;
}

export interface AIGeneratedArc {
  format: GridFormat;
  totalDuration: number;
  frames: AIGeneratedFrame[];
  /** AI's reasoning about why this format/structure was chosen */
  reasoning?: string;
}

/**
 * Build the system prompt that instructs the AI how to generate frames.
 */
function buildSystemPrompt(): string {
  return `You are a senior creative director at a top advertising agency (Ogilvy, BBDO, Wieden+Kennedy level). You design TVC (television commercial) storyboards for Vietnamese-language commercials.

Your job: Read a user's TVC idea + product info, then design a frame-by-frame storyboard for it. Each frame represents one scene/shot in the commercial.

OUTPUT FORMAT: You must output ONLY valid JSON (no markdown, no preamble) matching this exact schema:

{
  "format": "2x2" | "3x2" | "3x3" | "4x3",
  "totalDuration": <integer seconds>,
  "reasoning": "<short explanation in Vietnamese why this format was chosen>",
  "frames": [
    {
      "num": <integer 1-12>,
      "timing": "<MM:SS-MM:SSs format, e.g. '0:00-0:03s'>",
      "role": "<short English role label like Hook/Problem/Product Reveal/Apply/Result/Confidence/Hero Shot/Logo End>",
      "actionVi": "<detailed action description in Vietnamese, 1-2 sentences>",
      "actionEn": "<English translation of actionVi, optimized for AI image generation prompt>"
    },
    ...
  ]
}

FORMAT SELECTION GUIDE:
- 2x2 (4 frames, ~12s) → for very simple ideas, TikTok ngắn
- 3x2 (6 frames, ~18s) → for moderately developed ideas, Reels vừa
- 3x3 (9 frames, ~27s) → STANDARD TVC (default for most ideas)
- 4x3 (12 frames, ~36s) → for complex narratives, multi-step demos, longer TVC

Each frame is 3 seconds. Choose format based on the idea's complexity:
- 1-3 key beats → 2x2
- 4-6 key beats → 3x2
- 6-9 key beats → 3x3 (most common)
- 10-12 key beats → 4x3

NARRATIVE STRUCTURE:
A good TVC follows a story arc. Common patterns:

1. Problem-Solution (skincare, healthcare):
   Hook → Problem → Product Reveal → Apply → Result → Confidence → Hero → Logo

2. Desire-Satisfy (F&B, indulgence):
   Craving → See product → Open/Pour → First taste → Reaction → Share → Lifestyle → Hero → Logo

3. Pain-Capability (tech, gadgets):
   Daily life → Pain point → Discover product → Setup → Use → Achievement → Hero → Logo

4. Aspiration-Reality (fashion, luxury):
   Get ready → Outfit choice → Walk out → Confidence → Detail → Lifestyle → Hero → Logo

5. Journey-Memory (travel, experiences):
   Departure → Arrival → Explore → Highlight → Connection → Sunset → Hero → Brand

But you should ADAPT to the specific idea, not force these patterns. If user's idea naturally calls for a different structure (vlog style, testimonial, before/after), use that.

CONSISTENCY REQUIREMENTS:
- Same person across ALL frames (don't introduce new characters)
- Same outfit unless idea specifies costume changes
- Same product packaging
- Same environment style/lighting feel

CULTURAL NUANCES (Vietnamese audience):
- Family bonds, social warmth highly valued
- Humor and lightness preferred over dramatic intensity
- Local settings (Đà Lạt, Hội An, Sài Gòn, Hà Nội) feel more relatable
- Vietnamese cuisine, áo dài, phở etc. — keep these as-is in actionVi

LAST FRAME (LOGO):
Always end with a brand logo frame. If brandName is provided, include it. If tagline is provided, include it.

LANGUAGE:
- actionVi: Detailed Vietnamese, 1-2 sentences, vivid and specific
- actionEn: Direct English translation, optimized for image generation prompts (vivid descriptors, specific lighting, mood, camera framing)
- role: Short English label (Hook, Problem, Product Reveal, Apply, etc.)
- timing: MM:SS-MM:SSs format starting at 0:00

REASONING (in Vietnamese):
1-2 sentences explaining why you chose this format and structure based on the idea. Help user understand your creative decision.`;
}

/**
 * Build user prompt with all context from project.
 */
function buildUserPrompt(opts: AIGenerateOptions): string {
  const { project, formatPreference, brandName, tagline } = opts;

  const idea = project.idea?.raw || "";
  const productDescs = project.references?.productDescriptions?.filter(Boolean) || [];
  const industry = (project as any).industry || "general";
  const mode = (project as any).mode || "lifestyle";
  const isFilmMode = mode === "film";
  const filmGenre = (project as any).filmGenre || "drama";
  const animationStyle = (project as any).animationStyle || "live_action";
  const filmCharacters = (project as any).filmCharacters || [];
  const filmSubjectMode = (project as any).filmSubjectMode || "simple";
  const cameraStyle = project.cameraStyle || "BOKEH";
  const aspectRatio = project.aspectRatio || "9:16";

  const lines = [
    isFilmMode ? `# FILM IDEA (in Vietnamese):` : `# TVC IDEA (in Vietnamese):`,
    idea || (isFilmMode
      ? "(không có ý tưởng — generate generic short film)"
      : "(không có ý tưởng — generate generic TVC)"),
    "",
    `# CONTEXT:`,
  ];

  if (isFilmMode) {
    lines.push(`- Mode: Short Film / Narrative`);
    lines.push(`- Genre: ${filmGenre}`);
    lines.push(`- Animation Style: ${animationStyle.replace("_", " ")}`);
    lines.push(`- Story structure: 3-act (Setup/Conflict/Resolution)`);
    lines.push(`- Camera style: ${cameraStyle === "BOKEH" ? "BOKEH cinematic" : "DOCUMENTARY natural"}`);
    lines.push(`- Aspect ratio: ${aspectRatio}`);
  } else {
    lines.push(`- Industry/Ngành: ${industry}`);
    lines.push(`- Camera style: ${cameraStyle === "BOKEH" ? "BOKEH cinematic" : "DOCUMENTARY natural"}`);
    lines.push(`- Aspect ratio: ${aspectRatio} (vertical for Reels/TikTok)`);
  }

  // v0.8.0: Film characters context
  if (isFilmMode && filmSubjectMode === "characters" && filmCharacters.length > 0) {
    lines.push("");
    lines.push(`# CAST (${filmCharacters.length} characters):`);
    filmCharacters.forEach((c: any, i: number) => {
      lines.push(
        `${i + 1}. ${c.name} (${c.role})${c.description ? ` — ${c.description}` : ""}`
      );
    });
    lines.push(``);
    lines.push(`Frames should reference characters by name when relevant. Multiple characters can appear in same frame.`);
  }

  if (productDescs.length > 0) {
    lines.push("");
    lines.push(`# PRODUCT(S):`);
    productDescs.forEach((desc, i) => {
      lines.push(`${i + 1}. ${desc}`);
    });
  }

  if (brandName) {
    lines.push("");
    lines.push(`# BRAND NAME (for logo frame): ${brandName}`);
  }

  if (tagline) {
    lines.push(`# TAGLINE (for logo frame): "${tagline}"`);
  }

  lines.push("");
  lines.push(`# FORMAT PREFERENCE:`);
  if (formatPreference && formatPreference !== "auto") {
    lines.push(`User wants ${formatPreference} format (${FORMAT_CONFIGS[formatPreference].cells} frames). Use this format.`);
  } else {
    lines.push(`AUTO — you decide the best format based on the idea complexity. Choose 2x2, 3x2, 3x3, or 4x3 based on how many key beats the story needs.`);
  }

  lines.push("");
  lines.push(`# YOUR TASK:`);
  lines.push(`Design a frame-by-frame storyboard for this TVC. Output ONLY the JSON object specified in the system prompt. No markdown, no preamble, no code fences.`);

  return lines.join("\n");
}

/**
 * Main entry point: AI-generate storyboard from project context.
 */
export async function generateStoryboardWithAI(
  opts: AIGenerateOptions
): Promise<AIGeneratedArc> {
  const systemPrompt = buildSystemPrompt();
  const userPrompt = buildUserPrompt(opts);

  let raw: string;
  if (opts.provider === "openai") {
    raw = await callOpenAI(systemPrompt, userPrompt, 0.7, 4096);
  } else {
    raw = await callGemini(systemPrompt, userPrompt, 0.7, 4096);
  }

  // Strip markdown code fences if AI included them despite instructions
  let cleaned = raw.trim();
  if (cleaned.startsWith("```json")) cleaned = cleaned.slice(7);
  if (cleaned.startsWith("```")) cleaned = cleaned.slice(3);
  if (cleaned.endsWith("```")) cleaned = cleaned.slice(0, -3);
  cleaned = cleaned.trim();

  let parsed: any;
  try {
    parsed = JSON.parse(cleaned);
  } catch (e) {
    console.error("AI response was not valid JSON:", raw);
    throw new Error(
      `AI trả về dạng không hợp lệ. Thử lại hoặc đổi provider. Detail: ${(e as Error).message}`
    );
  }

  // Validate basic shape
  if (!parsed.format || !Array.isArray(parsed.frames) || parsed.frames.length === 0) {
    throw new Error("AI response thiếu format hoặc frames. Thử lại.");
  }

  // Normalize and validate frames
  const frames: AIGeneratedFrame[] = parsed.frames.map((f: any, idx: number) => ({
    num: typeof f.num === "number" ? f.num : idx + 1,
    timing: f.timing || formatTiming(idx),
    role: f.role || "Scene",
    actionVi: f.actionVi || "",
    actionEn: f.actionEn || f.actionVi || "",
  }));

  return {
    format: parsed.format as GridFormat,
    totalDuration: parsed.totalDuration || frames.length * 3,
    frames,
    reasoning: parsed.reasoning,
  };
}

function formatTiming(idx: number, secPerFrame: number = 3): string {
  const start = idx * secPerFrame;
  const end = (idx + 1) * secPerFrame;
  const fmt = (s: number) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;
  return `${fmt(start)}-${fmt(end)}s`;
}
