/**
 * KSP Image v0.9.0 — TVC Concept Section
 *
 * 8-field treatment editor for TVC mode (Mockup of Concept):
 * 1. Logline
 * 2. Synopsis
 * 3. Tone & Mood (chips)
 * 4. Target Audience (3 sub-fields)
 * 5. Key Messages
 * 6. Visual References
 * 7. Brand Voice
 * 8. CTA / Logo End
 *
 * AI generate from idea, variation regeneration, versioning.
 * Used in TVC mode only.
 */

import React, { useState } from "react";
import { useAppStore } from "../store/useAppStore";
import { migrateProjectToV09 } from "../store/migration_v09";
import * as actions from "../store/v09_actions";
import { generateTvcConcept } from "../engine/aiRuntime";
import type { TvcConcept, ProjectModeV2 } from "../types/v0_9_0";

export function TvcConceptSection() {
  const project = useAppStore((s) => s.currentProject);
  const updateProject = useAppStore((s) => s.updateCurrentProject);
  const showToast = useAppStore((s) => s.showToast);

  if (!project) return null;
  const migrated = migrateProjectToV09(project);
  const mode = (migrated.settingV2?.mode ?? "photos") as ProjectModeV2;
  if (mode !== "tvc_commercial") return null;

  const concept = migrated.concept;
  const setting = migrated.settingV2!;
  const idea = (project as any).idea ?? "";
  const brandName = (project as any).brandName;
  const tagline = (project as any).tagline;
  const products = (project as any).productImageIds ?? [];

  const [generating, setGenerating] = useState(false);
  const [showVersions, setShowVersions] = useState(false);

  function patch(updates: Partial<typeof migrated>) {
    updateProject(updates as any);
  }

  async function handleGenerate(asVariation = false) {
    if (!idea.trim()) {
      showToast("Anh nhập ý tưởng trước", "error");
      return;
    }

    if (asVariation && concept) {
      patch(actions.snapshotConceptVersion(migrated, "Before variation"));
    }

    setGenerating(true);
    try {
      const { concept: newConcept, reasoning } = await generateTvcConcept(
        {
          ideaRaw: idea,
          industry: setting.industry ?? "general",
          brand: brandName,
          productDescription: products.length > 0 ? `${products.length} product(s)` : undefined,
          aspectRatio: setting.aspectRatio,
          durationSeconds: setting.durationMinutes ? setting.durationMinutes * 60 : 30,
        },
        setting.aiProviders.conceptWriter
      );

      patch(actions.setConcept(migrated, newConcept));
      showToast(
        `✓ Concept generated${reasoning ? ` · ${reasoning.slice(0, 60)}...` : ""}`,
        "success"
      );
    } catch (err: any) {
      showToast(`Lỗi AI: ${err.message}`, "error");
    } finally {
      setGenerating(false);
    }
  }

  return (
    <section className="ksp-section ksp-concept-section" data-mode={mode}>
      <header className="ksp-section-header">
        <span className="ksp-section-icon">📋</span>
        <h2 className="ksp-section-title">2. CONCEPT (Treatment)</h2>
        {concept?.aiProvider && <span className="ksp-script-meta">Generated by {concept.aiProvider}</span>}
      </header>

      <div className="ksp-script-actions">
        <button
          className="ksp-btn ksp-btn-orange"
          onClick={() => handleGenerate(false)}
          disabled={generating}
        >
          {generating ? "⚙ Generating..." : concept ? "✨ AI viết lại Concept" : "✨ AI viết Concept từ idea"}
        </button>
        {concept && (
          <button
            className="ksp-btn ksp-btn-orange-ghost"
            onClick={() => handleGenerate(true)}
            disabled={generating}
          >
            ↻ Variation
          </button>
        )}
        {concept && (concept.versions?.length ?? 0) > 0 && (
          <button
            className="ksp-btn ksp-btn-ghost"
            onClick={() => setShowVersions(!showVersions)}
          >
            📜 Versions ({concept.versions?.length ?? 0})
          </button>
        )}
      </div>

      {showVersions && concept && (
        <div className="ksp-script-versions">
          {(concept.versions ?? []).slice().reverse().map((v) => (
            <div key={v.id} className="ksp-script-version-item">
              <span>{v.label}</span>
              <span>{new Date(v.timestamp).toLocaleString("vi")}</span>
            </div>
          ))}
        </div>
      )}

      {!concept && !generating && (
        <div className="ksp-script-empty">
          <p>Chưa có Concept. Nhập Idea → click "✨ AI viết Concept" để bắt đầu.</p>
        </div>
      )}

      {concept && (
        <ConceptForm concept={concept} onUpdate={(p) => patch(actions.updateConceptField(migrated, p))} />
      )}

      <div className="ksp-info-banner">
        💡 Concept feed: <strong>Storyboard frames</strong> (tone consistency) ·{" "}
        <strong>Image gen</strong> (visual references) · <strong>Voice AI</strong> (brand voice) ·{" "}
        <strong>Music</strong> (mood progression)
      </div>
    </section>
  );
}

function ConceptForm({
  concept,
  onUpdate,
}: {
  concept: TvcConcept;
  onUpdate: (patch: Partial<TvcConcept>) => void;
}) {
  return (
    <div className="ksp-concept-form">
      {/* Field 1: Logline */}
      <Label text="📌 Logline (1) — 1 sentence hook">
        <textarea
          className="ksp-input ksp-textarea"
          rows={2}
          value={concept.loglineEn}
          onChange={(e) => onUpdate({ loglineEn: e.target.value })}
        />
      </Label>

      {/* Field 2: Synopsis */}
      <Label text="📖 Synopsis (2) — 3-5 sentence narrative">
        <textarea
          className="ksp-input ksp-textarea"
          rows={4}
          value={concept.synopsisEn}
          onChange={(e) => onUpdate({ synopsisEn: e.target.value })}
        />
      </Label>

      {/* Field 3: Tone (chips) */}
      <ToneChips
        tone={concept.tone}
        onChange={(tone) => onUpdate({ tone })}
      />

      {/* Field 4: Audience */}
      <details className="ksp-collapsible-inline">
        <summary>👥 Target Audience (4)</summary>
        <div className="ksp-collapsible-inline-content">
          <Label text="Demographic">
            <input
              className="ksp-input"
              value={concept.audience.demographic}
              onChange={(e) =>
                onUpdate({ audience: { ...concept.audience, demographic: e.target.value } })
              }
              placeholder="e.g. Vietnamese women 22-35, dry/combo skin, mid-high income"
            />
          </Label>
          <Label text="Psychographic">
            <input
              className="ksp-input"
              value={concept.audience.psychographic}
              onChange={(e) =>
                onUpdate({ audience: { ...concept.audience, psychographic: e.target.value } })
              }
              placeholder="e.g. interested in scientific skincare, watch Reels/TikTok"
            />
          </Label>
          <Label text="Platform">
            <input
              className="ksp-input"
              value={concept.audience.platform}
              onChange={(e) =>
                onUpdate({ audience: { ...concept.audience, platform: e.target.value } })
              }
              placeholder="e.g. Reels, TikTok, Web"
            />
          </Label>
        </div>
      </details>

      {/* Field 5: Key Messages */}
      <details className="ksp-collapsible-inline" open>
        <summary>🔑 Key Messages (5)</summary>
        <div className="ksp-collapsible-inline-content">
          {concept.keyMessages.map((msg, i) => (
            <div key={i} className="ksp-array-line">
              <input
                className="ksp-input"
                value={msg}
                onChange={(e) => {
                  const next = [...concept.keyMessages];
                  next[i] = e.target.value;
                  onUpdate({ keyMessages: next });
                }}
              />
              <button
                className="ksp-btn ksp-btn-sm ksp-btn-danger-ghost"
                onClick={() => onUpdate({ keyMessages: concept.keyMessages.filter((_, x) => x !== i) })}
              >
                ×
              </button>
            </div>
          ))}
          <button
            className="ksp-btn ksp-btn-sm ksp-btn-ghost"
            onClick={() => onUpdate({ keyMessages: [...concept.keyMessages, ""] })}
          >
            + Add message
          </button>
        </div>
      </details>

      {/* Field 6: Visual References */}
      <details className="ksp-collapsible-inline">
        <summary>🎬 Visual References (6)</summary>
        <div className="ksp-collapsible-inline-content">
          {concept.visualReferences.map((ref, i) => (
            <div key={i} className="ksp-array-line">
              <input
                className="ksp-input"
                value={ref}
                onChange={(e) => {
                  const next = [...concept.visualReferences];
                  next[i] = e.target.value;
                  onUpdate({ visualReferences: next });
                }}
                placeholder="e.g. Estée Lauder ANR campaign, La Roche-Posay TVC 2024"
              />
              <button
                className="ksp-btn ksp-btn-sm ksp-btn-danger-ghost"
                onClick={() => onUpdate({ visualReferences: concept.visualReferences.filter((_, x) => x !== i) })}
              >
                ×
              </button>
            </div>
          ))}
          <button
            className="ksp-btn ksp-btn-sm ksp-btn-ghost"
            onClick={() => onUpdate({ visualReferences: [...concept.visualReferences, ""] })}
          >
            + Add reference
          </button>
        </div>
      </details>

      {/* Field 7: Brand Voice */}
      <details className="ksp-collapsible-inline">
        <summary>🗣️ Brand Voice (7)</summary>
        <div className="ksp-collapsible-inline-content">
          <textarea
            className="ksp-input ksp-textarea"
            rows={3}
            value={concept.brandVoice}
            onChange={(e) => onUpdate({ brandVoice: e.target.value })}
            placeholder="2-3 sentences describing how the brand speaks..."
          />
        </div>
      </details>

      {/* Field 8: CTA / Logo End */}
      <details className="ksp-collapsible-inline">
        <summary>🏷 CTA / Logo End (8)</summary>
        <div className="ksp-collapsible-inline-content">
          <textarea
            className="ksp-input ksp-textarea"
            rows={2}
            value={concept.ctaLogoEnd}
            onChange={(e) => onUpdate({ ctaLogoEnd: e.target.value })}
            placeholder="Final frame description with logo + tagline"
          />
        </div>
      </details>
    </div>
  );
}

// ============================================================================
// TONE CHIPS
// ============================================================================

function ToneChips({
  tone,
  onChange,
}: {
  tone: string[];
  onChange: (tone: string[]) => void;
}) {
  const [input, setInput] = useState("");

  function addChip() {
    const trimmed = input.trim().toLowerCase();
    if (!trimmed) return;
    if (tone.includes(trimmed)) return;
    onChange([...tone, trimmed]);
    setInput("");
  }

  return (
    <div className="ksp-tone-chips-block">
      <div className="ksp-label-text">🎨 Tone &amp; Mood (3) — chips</div>
      <div className="ksp-tone-chips">
        {tone.map((t) => (
          <span key={t} className="ksp-tone-chip">
            {t}
            <button
              type="button"
              className="ksp-tone-chip-remove"
              onClick={() => onChange(tone.filter((x) => x !== t))}
            >
              ×
            </button>
          </span>
        ))}
        <div className="ksp-tone-chip-input">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                addChip();
              }
            }}
            placeholder="+ add tone (Enter)"
          />
        </div>
      </div>
    </div>
  );
}

function Label({ text, children }: { text: string; children: React.ReactNode }) {
  return (
    <label className="ksp-label">
      <span className="ksp-label-text">{text}</span>
      {children}
    </label>
  );
}
